deegree/deegree3

- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/xml/stax/XMLStreamUtils.java
- deegree-core/deegree-core-cs/src/main/java/org/deegree/cs/persistence/CRSManager.java
Improved resource handling of crs manager.
> Improve resource handling in CRSManager to close XmlStreamReader

- deegree-core/deegree-core-protocol/deegree-protocol-wms/src/main/java/org/deegree/protocol/wms/client/WMSClient.java
Extended wms client by enabling "text/xml" format for GetFeatureInfo requests.
> Modify default format for GetFeatureInfo request for RemoteWMS

- deegree-spring/pom.xml
- pom.xml
To prevent duplicate Libraries in build i had enhanced/corrected the excludes.
Actually ther were two  diferent versions of wodstox (ASF 4.1.4 / LGP 4.2.0) and two different commons-logging libraries (commons-logging/jcl-over-slf4j) 
In addition to that change i found out that the dependecy from batik-transcoder to fop has changed and the old exclude of fop:fop didn't work nowadays.
For reference here the dependency:tree output for woodstox/commons-logging:
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ deegree-core-commons ---
[INFO] org.deegree:deegree-core-commons:jar:3.4-pre16-SNAPSHOT
[INFO] +- org.deegree:deegree-core-workspace:jar:3.4-pre16-SNAPSHOT:compile
[INFO] |  \- org.deegree:deegree-core-annotations:jar:3.4-pre16-SNAPSHOT:compile
[INFO] |     +- …
> Bugfix / enhancement: Prevent duplicate libraries

- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/utils/GMLObjectVisitor.java
- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/utils/GMLObjectWalker.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-memory/src/main/java/org/deegree/feature/persistence/memory/MemoryFeatureStoreTransaction.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-memory/src/main/java/org/deegree/feature/persistence/memory/StoredFeatures.java
Add support for non-feature/non-geometry object types to the GMLObjectWalker and GMLObjectVisitor utility classes. This is needed for full traversal of object graphs that contain TimeSlice and TimeObject instances.
> GMLObjectWalker: Add support for non-feature/non-geometry object types

- deegree-core/deegree-core-commons/src/test/java/org/deegree/commons/index/RTreeTest.java
The hardcoded path /tmp/rtree.txt is (usually) not available on non Unix systems, breaking the build.
> Resolves hardcoded temp file replaced with File.createTempFile call

- deegree-core/deegree-core-base/src/main/java/org/deegree/feature/xpath/GMLObjectNavigator.java
Happened on empty primitive-valued elements, e.g. when evaluating aixm:name/text() on
```xml
<aixm:name xsi:nil="true"/>
```
> Fix NPE in XPath evaluation

- deegree-services/deegree-webservices/src/main/resources/META-INF/console/resourceprovider/org.deegree.tile.persistence.filesystem.FileSystemTileStoreProvider
During startup following error appears:
[11:20:50] ERROR: [ResourceProviderMetadata] Configuration example file '/META-INF/schemas/datasource/tile/filesystem/3.2.0/example.xml' is missing on classpath.
...
[11:41:38] ERROR: [JsfUtils] Internal error: Example template missing!?
Also, no filesystem tile store can be created with the GUI as there is no template referenced.
This pull request fixes the path to the template.
> Fixed path to filesystem tile store template

- deegree-services/deegree-webservices/src/main/resources/META-INF/console/resourceprovider/org.deegree.tile.persistence.gdal.GdalTileStoreProvider
Creation of a GdalTileStore via GUI fails as there is no template available.
This fix adds the missing GdalTileStoreProvider resource provider referencing the templates.
> Fixed creation of GdalTileStore via GUI

- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/context/ImageRenderContext.java
- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/context/Java2DRenderContext.java
- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/context/LazyImageRenderContext.java
- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/context/RenderContext.java
- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/context/SvgRenderContext.java
- deegree-layers/deegree-layers-gdal/src/main/java/org/deegree/layer/persistence/gdal/GdalLayerData.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/WMSController.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/WmsCapabilities111MetadataWriter.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/WmsCapabilities130MetadataWriter.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/plugins/DefaultOutputFormatProvider.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/plugins/OutputFormatProvider.java
This pull adds support for SVG to the WMS. Based on a proof of concept implementation by @erikorbons.
It required a change in the GDAL layer implementation that might hurt performance in some cases.
> Add SVG support to WMS

- deegree-services/deegree-webservices/src/main/resources/META-INF/console/resourceprovider/org.deegree.layer.persistence.gdal.GdalLayerStoreProvider
Creation of a GdalLayerStore via console fails as there is no template available.
This fix adds the missing GdalLayerStoreProvider resource provider referencing the templates.
> Fixed creation of GdalLayerStore via console

- deegree-services/deegree-webservices/src/main/java/org/deegree/console/connection/remoteows/CreateRemoteOwsBean.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/datastore/coverage/CreateCoverageBean.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/datastore/feature/CreateFeatureStoreBean.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/datastore/metadata/CreateMetadataStoreBean.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/datastore/tile/CreateTileStoreBean.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/layer/layer/CreateLayerBean.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/layer/style/CreateStyleBean.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/layer/theme/CreateThemeBean.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/process/CreateProcessBean.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/webservices/CreateServiceBean.java
Fixes the dreaded "j_idt78:j_idt87: Validation Error: Value is not valid" when creating new resources.
This was caused by the wrong scope for the managed beans. Due to Ajax-updating of the templates-drop-down menu, request scope is not enough. Changed relevant JSF beans to view scope.
Fixes #340, #341, #343, #344, #345
> Fixed creation of new resources via console

- deegree-datastores/deegree-tilestores/deegree-tilestore-merge/src/main/resources/META-INF/schemas/datasource/tile/merge/3.4.0/example.xml
- deegree-services/deegree-webservices/src/main/resources/META-INF/console/resourceprovider/org.deegree.tile.persistence.merge.MergingTileStoreProvider
MergingTileStores could not be created via console as the template was missing.
This pull request fixes the issue by creating a MergingTileStore resource provider and an example.xml (was automatically generated from schema).
> Fixed creation of MergingTileStore via console

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStore.java
Prior to this patch, for features queried by id in BLOB mode, the resolver was always set to a new instance of FeatureStoreGMLIdResolver.
> SQLFeatureStore: Respect configured feature resolver in BLOB mode

- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/WMSController.java
- deegree-services/deegree-services-wms/src/main/resources/META-INF/schemas/services/wms/3.4.0/wms_configuration.xsd
- deegree-services/deegree-webservices-handbook/src/main/sphinx/webservices.rst
With this pull request it is possible to configure supported output formats for GetMap requests. Only configured image formats are supported as output format. If no format has been configured, all formats are supported.
For requests with unsupported output formats, deegree will respond with an exception (```XML```, ```INIMAGE```).
> Enhance WMS GetMap response for unsupported image formats and make the supported image output format configurable

- .travis.yml
This Pull Request tests the new container-based infrastructure of travis which enables public repositories to use a faster an cacheing enabled build environment [1]. 
[1] http://docs.travis-ci.com/user/workers/container-based-infrastructure
[2] http://docs.travis-ci.com/user/caching
Before this pull Request can be used, the travis build result has to be checked.
> Switch travis to new container-based infrastructure and enable caching

- deegree-core/deegree-core-layer/src/main/java/org/deegree/layer/config/ConfigUtils.java
- deegree-core/deegree-core-layer/src/main/java/org/deegree/layer/metadata/LayerMetadata.java
- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/context/MapOptions.java
- deegree-layers/deegree-layers-coverage/src/main/java/org/deegree/layer/persistence/coverage/CoverageLayer.java
- deegree-layers/deegree-layers-feature/src/main/java/org/deegree/layer/persistence/feature/FeatureLayer.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/MapService.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/WmsCapabilities111ThemeWriter.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/WmsCapabilities130ThemeWriter.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/theme/LayerMetadataQueryable.java
This Pull Requests fixes the the issue #517 by
* correcting the loading of the layer options (correct the `enabled=false`)
* enhancement of handling of the three states of the feature info radius
* < 0 ==> default (as specified in service endpoint)
* = 0 ==> disabled
* > 0 ==> user specified radius
* porting the 3.4 layer analiesis method to a single helper class to make a Layer in WMS/GetCapabilties only `queryable=0` if all layers in the sub structure are not queryable
> 3.3 bugfix featureinfo queryable

- deegree-core/deegree-core-layer/src/main/java/org/deegree/layer/config/ConfigUtils.java
- deegree-core/deegree-core-layer/src/main/java/org/deegree/layer/metadata/LayerMetadata.java
- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/context/MapOptions.java
- deegree-layers/deegree-layers-coverage/src/main/java/org/deegree/layer/persistence/coverage/CoverageLayer.java
- deegree-layers/deegree-layers-feature/src/main/java/org/deegree/layer/persistence/feature/FeatureLayer.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/MapService.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/theme/LayerMetadataMerger.java
This Pull Requests fixes the the issue #516 by
* correcting the loading of the layer options (correct the `enabled=false`)
* enhancement of handling of the three states of the feature info radius
* < 0 ==> default (as specified in service endpoint)
* = 0 ==> disabled
* > 0 ==> user specified radius
* fixing the `LyerMetadateMerger` to make a Layer in WMS/GetCapabilties only `queryable=0` if all layers in the sub structure are not queryable
> 3.4 bugfix featureinfo queryable

- deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/persistence/DefaultCoverageBuilder.java
- deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/persistence/pyramid/PyramidCoverageBuilder.java
- deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/utils/RasterBuilder.java
- deegree-core/deegree-core-coverage/src/main/resources/META-INF/schemas/datasource/coverage/raster/3.1.0/pyramid.xsd
- deegree-services/deegree-webservices-handbook/src/main/sphinx/coveragestores.rst
Until now, pyramid configurations did not provide a way to set a nodata value. That results in unexpected images, if the bounding box is not completely covered by the provided image or i.e. the image is cut with the elevation parameter.
Pixels not covered by the image or cut out are assigned a value of 0, but that is not neccessarily the nodata value of the image. So it may be rendered in an unexpected colour.
This pull request provides the possibility to configure the value set for nodata pixels. If it is set to the appropriate value (like nodata or background colour in style configuration), it will be rendered as expected.
> Enhance handling of nodata values in coverages

- deegree-services/deegree-webservices/pom.xml
- pom.xml
Modifies the maven plugin to run the web application to the official Apache Tomcat Maven plugin.
To use the plugin run
```deegree-services/deegree-webservices> mvn tomcat7:run```
or
```deegree-services/deegree-webservices> mvn tomcat7:run-war```
and then open <http://localhost:8080/> to access the deegree console.
> Replace the outdated codehaus plugin by the official Apache Tomcat Maven plugin

- deegree-core/deegree-core-base/src/main/java/org/deegree/feature/xpath/GMLObjectNavigator.java
In Pull Request #466 a JDK 6 the Collections.emptyIterator() was used which is not available in JDK6 see [1].
The class also used the Jaxen.EMPTY_ITERATOR constant, so i switched to this and i also harmonized the use of the constant.
[1] http://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#emptyIterator%28%29
> Bugfix/3.4 fix JDK 6 compatibility

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStore.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStoreTransaction.java
Prior to this patch, multi-part transactions against the SQLFeatureStore could lead to lost updates. Here's an example of such a transaction (in the form of a WFS 2.0 transaction):
```
<?xml version="1.0"?>
<wfs:Transaction xmlns:fes="http://www.opengis.net/fes/2.0" xmlns:wfs="http://www.opengis.net/wfs/2.0" xmlns:aixm="http://www.aixm.aero/schema/5.1" xmlns:gml="http://www.opengis.net/gml/3.2" version="2.0.0" service="WFS">
<wfs:Update typeName="aixm:Airspace">
<wfs:Property>
<wfs:ValueReference action="insertBefore">aixm:timeSlice[1]</wfs:ValueReference>
<wfs:Value>
<aixm:AirportHeliportTimeSlice gml:id="TEST_11111111-1111-1111-1111-111111111111_3">
<gml:validTime>
<gml:TimePeriod gml:id="TEST_11111111-1111-1111-1111-111111111111_4"> …
```
> SQLFeatureStore: Fix lost updates in multi-part transactions

- deegree-core/deegree-core-base/src/main/java/org/deegree/feature/xpath/TypedObjectNodeXPathEvaluator.java
- deegree-core/deegree-core-base/src/main/java/org/deegree/feature/xpath/node/TimePositionAdapter.java
- deegree-core/deegree-core-base/src/test/java/org/deegree/feature/xpath/TimePeriodXPathTest.java
- deegree-core/deegree-core-base/src/test/resources/org/deegree/time/gml/reader/time_period_indeterminate.gml
- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/tom/sql/DefaultPrimitiveConverter.java
This patch improves the support for accessing XML nodes inside of TimeInstant/TimePeriod objects.
Consider that the following GML example has been parsed into deegree's object model:
```
<TimePeriod gml:id="p1" xmlns="http://www.opengis.net/gml/3.2" xmlns:gml="http://www.opengis.net/gml/3.2">
<beginPosition>2001-05-23</beginPosition>
<endPosition indeterminatePosition="unknown" />
</TimePeriod>
```
Before the patch, it was not possible to access the value of the "indeterminatePosition" attribute. After the patch xpaths that target this attribute are properly evaluated, e.g.
```
gml:TimePeriod/gml:endPosition/@indeterminatePosition
```
> Improve XPath support for TimeInstant/TimePeriod objects

- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/GMLStreamReader.java
- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/commons/AbstractGMLObjectReader.java
- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/feature/GMLFeatureReader.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/rules/FeatureBuilderRelational.java
Prior to this patch, a GML object other than a feature or a geometry would be recreated as GenericXMLElement by a relational-mode SQLFeatureStore. After this patch, such objects are transformed to the respective GMLObject subtype (e.g. TimeSlice or TimeObject). This is important for in-memory filtering on these kinds of objects.
> SQLFeatureStore: Support all GMLObject types in relational mode feature building

- deegree-core/deegree-core-sqldialect/deegree-sqldialect-oracle/src/main/java/org/deegree/sqldialect/oracle/OracleGeometryConverter.java
The caught throwable in the OracleGeometryConverter are now thrown as Stack of a new IllegalArgument Exception.
This was made to:
* Arrive the same goal as #430 to allow a better logging including original Exception information
* Keep the same Code workflow (throw IllegalArgumentException)
> Removed catch (Throwable) in OracleSqlDialect to improve error handling and logging on (rework)

- deegree-core/deegree-core-base/src/main/java/org/deegree/feature/property/GenericProperty.java
- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/GMLStreamReader.java
- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/commons/AbstractGMLObjectReader.java
- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/feature/GMLFeatureReader.java
- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/feature/GMLFeatureWriter.java
- deegree-core/deegree-core-base/src/main/java/org/deegree/time/gml/reader/GmlTimePeriodReader.java
- deegree-core/deegree-core-base/src/main/java/org/deegree/time/gml/writer/GmlTimePeriodWriter.java
- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/tom/sql/DefaultPrimitiveConverter.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/FeatureBuilder.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStore.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStoreTransaction.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/blob/FeatureBuilderBlob.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/config/AbstractMappedSchemaBuilder.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/config/MappedSchemaBuilderGML.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/ddl/DDLCreator.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/expressions/Function.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/insert/InsertRowManager.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/rules/FeatureBuilderRelational.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/rules/SqlExpressionMapping.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/xpath/MappedXPath.java
Prior to this patch, it was possible to use database column names or constants in the mapping attribute of primitive particles, e.g.:
```
<Primitive path="@nilReason" mapping="nil_reason"/"
```
or
```
<Primitive path="@nilReason" mapping="'unknown'"/"
```
After this patch, it's also possible to use arbitrary SQL expressions in the mapping of a primitive particle. Here's an example that maps a gml:validTime property. In this case, it either contains a TimeInstant, a TimePeriod or has attribute 'nilReason' set to 'unknown'. The attribute is set in case both the gml_validtime_gml_timeinstant and the gml_validtime_gml_timeperiod columns are NULL:
```
<Complex path="gml:validTime">
<Primitive path="@nilReason" mapping="(CASE WHEN $0.gml_validtime_gml_timeinstant IS NULL AND …
```
> SQLFeatureStore: Allow arbitrary SQL expressions in primitive particle mappings

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStore.java
This bug fix allows !GetFeature-requests with resultType="hits" in a SQLFeatureStore configuration with multiple tables where two or more tables have columns with the same name.
The alias of the root table is added in the select clause, to avoid SQLExceptions.
> Fixed SQL-Statement generated for resultType="hits" where column names are not unique

- deegree-datastores/deegree-coveragestores/deegree-coveragestore-oracle-georaster/pom.xml
- deegree-datastores/deegree-coveragestores/deegree-coveragestore-oracle-georaster/src/main/java/org/deegree/coverage/raster/io/oraclegeoraster/OracleGeorasterMetadata.java
- deegree-datastores/deegree-coveragestores/deegree-coveragestore-oracle-georaster/src/main/java/org/deegree/coverage/raster/io/oraclegeoraster/OracleGeorasterProvider.java
- deegree-datastores/deegree-coveragestores/deegree-coveragestore-oracle-georaster/src/main/java/org/deegree/coverage/raster/io/oraclegeoraster/OracleGeorasterReader.java
- deegree-datastores/deegree-coveragestores/deegree-coveragestore-oracle-georaster/src/main/java/org/deegree/coverage/raster/io/oraclegeoraster/utils/OracleGeorasterBuilder.java
- deegree-datastores/deegree-coveragestores/deegree-coveragestore-oracle-georaster/src/main/resources/META-INF/console/resourceprovider/org.deegree.coverage.raster.io.oraclegeoraster.OracleGeorasterProvider
- deegree-datastores/deegree-coveragestores/deegree-coveragestore-oracle-georaster/src/main/resources/META-INF/schemas/datasource/coverage/oraclegeoraster/3.4.0/example.xml
- deegree-datastores/deegree-coveragestores/deegree-coveragestore-oracle-georaster/src/main/resources/META-INF/schemas/datasource/coverage/oraclegeoraster/3.4.0/oraclegeoraster.xsd
- deegree-datastores/deegree-coveragestores/deegree-coveragestore-oracle-georaster/src/main/resources/META-INF/services/org.deegree.coverage.persistence.CoverageProvider
- deegree-datastores/deegree-coveragestores/pom.xml
- deegree-services/deegree-webservices-handbook/src/main/sphinx/coveragestores.rst
- deegree-services/deegree-webservices-handbook/src/main/sphinx/javamodules.rst
- pom.xml
This Pull Request adds the deegree-coveragestore-oracle-georaster and a intermediate deegree-coveragestores module.
The Oracle GeoRaster module builds on top of the Oracle GeoRaster API for Java an enables deegree to access single coverages stored in the Oracle Database.
Documentation, a example configuration and a META-INF for the console is included.
The module is targeted for Oracle 11.2 drivers which can connect to 11g and 10g databases and only builds if the `oracle` profile is activated.
> Oracle GeoRaster Support for 3.4

- deegree-core/deegree-core-sqldialect/deegree-sqldialect-commons/src/main/java/org/deegree/sqldialect/filter/islike/PlainText.java
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-commons/src/test/java/org/deegree/sqldialect/filter/IsLikeStringTest.java
When a PropertyIsLike filter is used in a GetFeature request, an exception is thrown if the Literal contains a single quote (').
This error results from a wrong escaping of this character: A backslash (\) is used instead of an additional single quote ('). Since postgres 9.1, in an oracle db and mysql quotes are always escaped by another quote.
This fix changes the escaping of single quotes to an additional single quote.
Example request body for testing:
```xml
<GetFeature xmlns="http://www.opengis.net/wfs" xmlns:ogc="http://www.opengis.net/ogc" xmlns:gmd="http://www.isotc211.org/2005/gmd"
xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gml="http://www.opengis.net/gml" xmlns:test="http://www.test.de/test"
xmlns:iso19112="http://www.opengis.net/iso19112" …
```
> Fixed bug in escaping of single quotes in PropertyIsLike filter

- deegree-core/deegree-core-layer/pom.xml
- deegree-core/deegree-core-layer/src/main/java/org/deegree/layer/config/ConfigUtils.java
- deegree-core/deegree-core-layer/src/test/java/org/deegree/layer/config/ConfigUtilsTest.java
- deegree-core/deegree-core-layer/src/test/resources/org/deegree/layer/config/styleRefs_DefaultWithoutLegendStyle.xml
- deegree-core/deegree-core-layer/src/test/resources/org/deegree/layer/config/styleRefs_DifferentDefaultAndSimple.xml
- deegree-core/deegree-core-layer/src/test/resources/org/deegree/layer/config/styleRefs_EqualDefaultAndSimple.xml
- deegree-core/deegree-core-layer/src/test/resources/org/deegree/layer/config/styleRefs_OnlyOneWithLegendStyle.xml
Following scenario explains the inconsistency between Capabilities and GetLegendGraphic response:
Styles section of Capabilities:
```xml
<Style>
<Name>style</Name>
<Title>style</Title>
<LegendURL width="150" height="234">
<Format>image/png</Format>
<OnlineResource xlink:type="simple" xlink:href="style.png"/>
</LegendURL>
</Style>
<Style>
<Name>default</Name>
<Title>default</Title>
<LegendURL width="204" height="189">
<Format>image/png</Format>
<OnlineResource xlink:type="simple" xlink:href="style.png"/>
</LegendURL>
</Style>
<Style>
<Name>legend_style</Name>
<Title>legend_style</Title>
<LegendURL width="204" height="189">
<Format>image/png</Format>
<OnlineResource xlink:type="simple" xlink:href="http://localhost:8080/services/wms?request=GetLegendGraphic&amp;version=1.3.0&amp;service=WMS&a …
```
> Fixes inconsistencies between styles in Capabilities and GetLegendGraphic response

- deegree-core/deegree-core-protocol/deegree-protocol-commons/src/main/java/org/deegree/protocol/ows/OWSCommonKVPAdapter.java
- deegree-core/deegree-core-protocol/deegree-protocol-wfs/src/test/java/org/deegree/protocol/wfs/getfeature/kvp/GetFeatureKVPAdapterTest.java
- deegree-core/deegree-core-protocol/deegree-protocol-wfs/src/test/resources/org/deegree/protocol/wfs/getfeature/kvp/wfs200/example_bbox_explicit_crs.kvp
Fixes #539.
Prior to this patch, the WFS would ignore the CRS information in KVP-encoded 2.0.0 BBOX-queries, always assuming the configured default CRS.
Example: The following request would not return the number of expected features (1248), but zero:
http://demo.deegree.org/utah-workspace/services?service=WFS&version=2.0.0&request=GetFeature&typeNames=DominantVegetation&bbox=-180,-90,180,90,EPSG:4326&resultType=hits
After this patch, the WFS respects the CRS information in the BBOX parameter and the example request returns 1248 (all features, as BBOX covers the earth).
Unit-Test included.
3.4-version: #556
> WFS: Evaluate CRS in BBOX parameter for version 2.0.0 KVP-queries

- deegree-core/deegree-core-protocol/deegree-protocol-wms/src/main/java/org/deegree/protocol/wms/ops/RequestBase.java
The request parameter "SLD_BODY" did not work as the style/filter/layer maps in RequestBase were never filled when parsing the sld. This fix enables the filling of those maps.
This pull request was also created for the master (#523).
> Fixed bug in sld_body request parameter

- deegree-core/deegree-core-style/src/main/java/org/deegree/style/styling/components/LinePlacement.java
Before it was not possible to position a label to a line centered, when using a function for the distance between line and label within perpendicular offset for the label.
With these changes it is possible!
> Improved positioning from labels of lines

- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/gml/request/GmlDescribeFeatureTypeHandler.java
When dynamic schemas are disabled in WFS services configuration (DisableDynamicSchema=true), deegree still generates dynamic schemas (when using DescribeFeatureType) if more than one feature store is configured.
This pull request extends this functionality by allowing more than one configured feature store:
If a namespace or a specific feature type is requested by a DescribeFeatureType request, deegree now includes the schema of the first feature store providing this namespace or feature type. As there cannot be configured multiple feature stores with the same feature type in deegree, no additional error handling is required. If the included schema does not provide all required schemas (e.g. GML) the reexport functionality is used instead (dynamic schemas are not disabled). The same …
> Improvement enabling support of extended configuration option 'DisableDynamicSchema' when more than one store is configured

- deegree-services/deegree-services-commons/pom.xml
- deegree-services/deegree-services-commons/src/api/java/org/deegree/services/controller/OGCFrontController.java
- deegree-services/deegree-services-commons/src/api/java/org/deegree/services/controller/RequestContext.java
- deegree-services/deegree-services-commons/src/test/java/org/deegree/services/controller/OGCFrontControllerTest.java
- deegree-services/deegree-webservices-handbook/src/main/sphinx/webservices.rst
- pom.xml
This enhancement enables following functionality:
If an incoming request contains the header "X-Forwarded-Host", the DCP URLs in the capabilities document are replaced by the value of the header. If the header is not present, the old mechanism is used.
The enhancement allows, for example, that a deegree service which can be accessed by multiple URLs returns the correct DCP URLs if the "X-Forwarded-Host" header is set.
> Use X-Forwarded-Host from header as HTTP GET and POST DCP URL if available

- deegree-workspaces/deegree-workspace-utah/src/main/workspace/services/wfs110.xml
- deegree-workspaces/deegree-workspace-utah/src/main/workspace/services/wfs110_metadata.xml
A new WFS 1.1.0 endpoint was added to the utah demo workspace, which passes all CITE WFS 1.1.0 basic profile tests. This new testsuite is data-agnostic and can be found at http://cite.opengeospatial.org/teamengine/about/wfs/1.1.0/site/.
> Added new WFS 1.1.0 endpoint to utah demo passing all CITE WFS 1.1.0 basic profile tests

- deegree-services/deegree-services-commons/src/main/java/org/deegree/services/metadata/OWSMetadataProvider.java
- deegree-services/deegree-services-commons/src/main/java/org/deegree/services/metadata/provider/DefaultOWSMetadataProvider.java
- deegree-services/deegree-services-commons/src/test/java/org/deegree/services/metadata/provider/DefaultOWSMetadataProviderTest.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/GetCapabilitiesHandler.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/Capabilities111XMLAdapter.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/WmsCapabilities111ThemeWriter.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/WmsCapabilities130ThemeWriter.java
Currently, just one metadataUrl is set for each Layer/FeatureType in the capabilities document of the WMS and WFS, even if multiple metadataUrls are configured for a Layer/FeatureType (if this is the case, just the last one is written in the capabilities document).
This fix allows to configure multiple metadataUrls for a single Layer/FeatureType and returns them in the capabilities response. The fix has been tested for WMS 1.3.0, WMS 1.1.1, WFS 1.1.0 and WFS 2.0.0.
In addition, two general adjustments were done:
* Previously, the WFS just returned FeatureTypes with metadataUrls in the capabilities document if metadataUrls were set. This behaviour was changed and now always all FeatureTypes are returned (even if metadataUrls are set).
* Previously, the metadataUrls of the first layer were …
> Enhancement allowing to set more than one MetadataURL for each Layer/FeatureType

- deegree-layers/deegree-layers-gdal/src/main/java/org/deegree/layer/persistence/gdal/GdalLayerStoreBuilder.java
When multiple GDAL files are configured to be used as single GDAL layer a new envelope enclosing all  those files is supposed to be calculated. This calculation was not implemented correctly resulting in an incorrect layer envelope.
> correctly merge envelopes of multiple gdal files

- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/feature/GMLFeatureWriter.java
GMLFeatureWriter: sometimes in our test the children of the ElementNode was null throwing a NullPointerException. Thus, we added a guard to it.
Please note that the integration tests are already broken on the deegree:master.
> Fix NPE in GML feature writer

- deegree-datastores/deegree-tilestores/deegree-tilestore-merge/src/main/java/org/deegree/tile/persistence/merge/MergingTile.java
When the 'upstream' tilestores are providing tiles with an alpha layer we have to remove this alpha layer before we create a jpeg file from the merged buffered image. Currently the case where we have no color data for certain pixels (= all tilestores provide a fully transparent pixel) is not explicitly handled resulting in unexpected black pixels. This pull requests suggests to explicitly paint the canvas white and subsequently paint the merged tile on top of that.
> Improve tilestore-merge to paint canvas background in white

- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/gml/request/AbstractGmlRequestHandler.java
Prior to this patch, it was possible that circular references caused the AdditionalObjects section of a WFS 2.0.0 response to contain wfs:member elements with xlinked content, e.g.
```
<wfs:FeatureCollection...>
...
<wfs:additionalObjects>
...
<wfs:member xlink:href="#uuid.bedfbe9d-cb04-4915-9e72-3f09b2940e7b" />
...
</wfs:additionalObjects>
<wfs:FeatureCollection/>
```
This is not schema-valid and also doesn't make sense: The additionalObjects section is supposed to contain "real" features, not references.
> WFS: Omit already exported features in additional objects section

- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/feature/GMLFeatureWriter.java
- deegree-core/deegree-core-base/src/test/java/org/deegree/gml/feature/GMLFeatureWriterTest.java
The GML subsystem tries to preserve original text representations whenever possible, e.g. if a numeric value of "0.10" is read, it should be exported as "0.10" and not as "0.1". I removed a forced reencoding via toString() for the case of decimal values. It had the effect that an xs:decimal value of "0.00000009" was re-encoded as "9E-8". This is not only a violation of the faithful encoding principle, but also invalid according to schema type xs:decimal.
Test case included.
> GML-Writer: Encode decimal values faithfully

- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/Java2DTextRenderer.java
- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/strokes/HaloStroke.java
- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/strokes/TextStroke.java
The follwing TextSymbolizer was not applied corerctly. Only the Halo or LinePlacement works, if both are enabled Halo was not rendered. 
``` xml
<TextSymbolizer uom="meter">
<Label>
<ogc:PropertyName>app:LABEL<ogc:PropertyName>
</Label>
<Font>
<SvgParameter name="font-family">Arial</SvgParameter>
<SvgParameter name="font-family">Sans-Serif</SvgParameter>
<SvgParameter name="font-weight">bold</SvgParameter>
<SvgParameter name="font-size">8</SvgParameter>
</Font>
<LabelPlacement> 
<LinePlacement>
<PerpendicularOffset>-10</PerpendicularOffset> 
<IsRepeated>false</IsRepeated>
<InitialGap>10</InitialGap> 
<PreventUpsideDown>true</PreventUpsideDown> 
<Center>true</Center> 
<WordWise>false</WordWise> 
</LinePlacement> 
</LabelPlacement>
<Halo>
<Radius>5</Radius>
<Fill>
<SvgParameter …
```
> Support of Halos with LinePlacement for line geometries

- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/GetCapabilitiesHandler.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/WebFeatureService.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/gml/request/GmlDescribeFeatureTypeHandler.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/Capabilities111XMLAdapter.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/Capabilities130XMLAdapter.java
In the CapabilitiesHandler the export of the Capabilities was finished with writer.writeEndDocument(), this leads to a NPE if the SOAP tags are closed later.
Request:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
<soapenv:Body>
<wfs:GetCapabilities xmlns:wfs="http://www.opengis.net/wfs/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ows="http://www.opengis.net/ows/1.1" service="WFS" xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd" />
</soapenv:Body>
</soapenv:Envelope>
```
Response:
```xml
<ows:ExceptionReport …
```
> Fixed NPE in WFS and WMS Capabilities request with SOAP, corrected ContentType of response and added NamespaceBinding to DescribeFeatureType response

- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/gml/request/GmlGetFeatureHandler.java
When a StoredQuery filter is used in a GetFeature request and GmlFormats are configured following erroneous response is returned:
```xml
<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd" version="2.0.0">
<ows:Exception exceptionCode="NoApplicableCode">
<ows:ExceptionText>Trying to write a namespace declaration when there is no open start element.</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>
```
The namespace bindings of GmlFormats are added, although no FeatureCollection element was opened. This error was fixed in this pull request.
> Fixed bug in StoredQuery filter when GmlFormats are configured

- deegree-core/deegree-core-base/src/main/java/org/deegree/filter/temporal/Before.java
- deegree-core/deegree-core-base/src/main/java/org/deegree/filter/temporal/During.java
- deegree-core/deegree-core-base/src/main/java/org/deegree/filter/xml/FilterCapabilitiesExporter.java
- deegree-core/deegree-core-base/src/main/java/org/deegree/time/operator/AfterOperator.java
- deegree-core/deegree-core-base/src/main/java/org/deegree/time/operator/BeforeOperator.java
- deegree-core/deegree-core-base/src/main/java/org/deegree/time/operator/TimeCompareUtils.java
- deegree-core/deegree-core-base/src/test/java/org/deegree/time/operator/AfterOperatorTest.java
- deegree-core/deegree-core-base/src/test/java/org/deegree/time/operator/BeforeOperatorTest.java
- deegree-core/deegree-core-base/src/test/java/org/deegree/time/operator/TimeCompareUtilsTest.java
Implemented the temporal operators "After", "Before" and "During" for WFS 2.0.0.
Temporal operators can be used to filter GetFeature requests.
The support of those operators is described in the capabilities and the constraints "ImplementsMinTemporalFilter" and "ImplementsTemporalFilter" are set to true.
> Implemented Temporal Operators After, Before und During for WFS 2.0.0

- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/GetCapabilitiesHandler.java
This pull request enables the export of keywords configured in the metadata configuration as keywords for feature types in WFS 2.0.0 capabilities.
> Implemented Export of Keywords for FeatureTypes in WFS 2.0.0 Capabilities

- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/tom/ResolveParams.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/GetCapabilitiesHandler.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/WebFeatureService.java
- deegree-services/deegree-services-wfs/src/main/resources/META-INF/schemas/services/wfs/3.4.0/wfs_configuration.xsd
- deegree-services/deegree-webservices-handbook/src/main/sphinx/webservices.rst
This pull requests adds a configuration option to the wfs configuration to configure the ResolveTimeOut in GetFeature, GetFetaureWithLock and GetPropertyValue request when the KVP/XML value is missing.
The configured value is exported as contraint 'ResolveTimeoutDefault' in the WFS 2.0.0 capabilities.
>  Enhanced WFS configuration supporting the option to set a default ResolveTimeOut

- deegree-core/deegree-core-metadata/src/main/java/org/deegree/metadata/iso/parsing/ParseIdentificationInfo.java
- deegree-core/deegree-core-metadata/src/main/java/org/deegree/metadata/iso/parsing/RecordPropertyParser.java
- deegree-core/deegree-core-metadata/src/main/java/org/deegree/protocol/csw/CSWConstants.java
- deegree-core/deegree-core-metadata/src/test/java/org/deegree/metadata/iso/ISORecordTest.java
- deegree-core/deegree-core-metadata/src/test/resources/org/deegree/metadata/iso/sds-example.xml
- deegree-datastores/deegree-mdstores/deegree-mdstore-iso/src/main/java/org/deegree/metadata/iso/persistence/ISOMetadataStore.java
- deegree-datastores/deegree-mdstores/deegree-mdstore-iso/src/main/java/org/deegree/metadata/iso/persistence/inspectors/FIInspector.java
- deegree-services/deegree-services-csw/src/main/java/org/deegree/services/csw/exporthandling/TransactionHandler.java
This pull requests adds the support of metadata records describing INSPIRE Spatial Data Service (TG for INSPIRE Spatial Data Services, v 3.1: ​​http://inspire.ec.europa.eu/documents/Spatial_Data_Services/TG_for_INSPIRE_SDS_3_1.pdf).
Metadata records describing INSPIRE Spatial Data Service as specified in ​http://inspire-geoportal.ec.europa.eu/schemas/inspire/inspire_sds/1.0/ can be inserted, removed and requested.
> Added support of metadata records describing INSPIRE Spatial Data Service in CSW

- deegree-core/deegree-core-layer/src/main/java/org/deegree/layer/config/DimensionConfigBuilder.java
Setup:
* deegree WMS is used which has a dimension configured in the layer configuration.
* The configured dimension is not "time" or "elevation" but a custom other dimension.
* A default value is configured for the custom other dimension.
Before this fix an error occurred during startup of deegree (or workspace reload).
Exception:
```
Could not parse layer configuration file: java.lang.String cannot be cast to java.util.List
```
> Fixed DimensionConfigBuilder to use defaultList for other dimensions

- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/ows/exception/OWSException.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/TransactionHandler.java
An InvalidValues exception should be thrown by WFS 2.0.0  transaction if unknown FeatureType is inserted:
* WFS 2.0.0 Specification, Table 3 - WFS exception codes, P.16:
* InvalidValue: "A Transaction (see Clause 15) has attempted to insert or change the value of a data component in a way that violates the schema of the feature."
This fix changes the exception code to "InvalidValues" if an unknown FeatureType is inserted by WFS 2.0.0 transaction.
> Fixed exception code if unknown FeatureType is inserted by WFS 2.0.0 transaction

- deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/metadata/SpatialMetadata.java
- deegree-core/deegree-core-geometry/src/test/java/org/deegree/geometry/metadata/SpatialMetadataTest.java
- deegree-core/deegree-core-layer/src/main/java/org/deegree/layer/metadata/LayerMetadata.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/Capabilities130XMLAdapter.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/theme/LayerMetadataMerger.java
Previously, the BBOX of the first requestable layer was identical to the BBOX of the root layer.
This pull request fixes this issue and now the first layer has its own, (according to the data) correct BBOX.
> Fixed BBOX of first layer in WMS capabilities

- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/WebFeatureService.java
In the WFS 2.0.0 the resultType parameter of GetFeatureWithLock requests is specified as follows (13.2.4.3
resultType parameter, p. 78):
```
The only valid value for the resultType attribute for a GetFeatureWithLock request shall 
be "results". If a client specifies a value of "hits" the server shall raise an 
InvalidParameterValue exception (see 7.5).
```
This pull requests fixes deegree WFS 2.0.0 to behave as specified and tested by the WFS 2.0.0 cite Testsuite (org.opengis.cite.iso19142.locking.GetFeatureWithLockTests, lockQueryResults_hits()).
> Fixed handling of GetFeatureWithLock requests and resultType 'hits' (according the WFS 2.0.0 specification)

- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/MapService.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/WMSController.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/WMSControllerBase.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/Capabilities111XMLAdapter.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/Capabilities130XMLAdapter.java
- deegree-services/deegree-services-wms/src/main/resources/META-INF/schemas/services/wms/3.4.0/wms_configuration.xsd
- deegree-services/deegree-webservices-handbook/src/main/sphinx/webservices.rst
This pull requests allows the user to set the sequence manually in the service configuration. In the following example the UpdateSequence was configured to 10, in the Capabilities this version is returned. If the configuration option is missing 0 is assumed and exported in the capabilities (old behaviour) 
Example:
```xml
<wms:deegreeWMS xmlns:wms="http://www.deegree.org/services/wms" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:dgws="http://www.deegree.org/webservices" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" configVersion="3.2.0" xsi:schemaLocation="http://www.deegree.org/services/wms http://schemas.deegree.org/services/wms/3.2.0/wms_configuration.xsd">
<wms:SupportedVersions>
<wms:Version>1.3.0</wms:Version>
</wms:SupportedVersions> …
```
> Enhanced WMS to configure the UpdateSequence in the service configuration

- deegree-core/deegree-core-base/src/main/java/org/deegree/filter/xml/Filter200XMLDecoder.java
- deegree-core/deegree-core-base/src/test/java/org/deegree/filter/xml/Filter200XMLDecoderTest.java
- deegree-core/deegree-core-base/src/test/resources/org/deegree/filter/xml/v200/unexectedTestfilter.xml
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/WebFeatureService.java
This pull requests lets the Filter200XmlDecoder throw an XMLParsingException if a Literal with gml-Geometry is detected. The handling of the WFS 2.0.0 is changed to throw an OperationProcessingFailed in case of a XMLParsingException.
The WFS 2.0.0 cite Testsuite is fixed by this pull request (Testclass org.opengis.cite.iso19142.basic.filter.ComparisonOperatorTests, Method invalidOperand_boundedBy()).
> Enhanced Filter200XmlDecoder to throw an Exception if a Literal with gml-Geometry subelement is parsed

- deegree-tests/deegree-compliance-tests/pom.xml
- deegree-tests/deegree-csw-bkg/pom.xml
- deegree-tests/deegree-testservice/pom.xml
- deegree-tests/deegree-wms-remoteows-tests/pom.xml
- deegree-tests/deegree-wms-similarity-tests/pom.xml
- deegree-tests/deegree-wms-tiling-tests/pom.xml
- deegree-tests/deegree-wmts-tests/pom.xml
- deegree-tests/deegree-workspace-tests/pom.xml
The maven GAV for the Maven Tomcat plugin were not in line with the project root POM which was changed in PR #478. This PR fixes this.
> Fixes the groupId and artifactId for Tomcat Maven Plugin 

- deegree-datastores/deegree-mdstores/deegree-mdstore-iso/src/main/resources/org/deegree/metadata/iso/persistence/postgis/create.sql
PostGIS 2 requires this parameter to be an integer. For PostGIS 1.5 the
value should be -1 when the srid is unknown. In PostGIS 2 providing a negative
value for srid is equivalent to providing 0, which is the PostGIS 2 value
for an unknown srid.
PostGIS versions tested:
- 1.5
- 2.1
Test performed:
```sql
create table test(id serial);
select AddGeometryColumn('public', 'test', 'geometry', -1, 'GEOMETRY', '2');
select srid from public.geometry_columns where f_table_name = 'test';
```
Test result:
- 1.5: srid = -1
- 2.1: srid = 0
Todo: also test in 2.0
fixes #531
> changed srid from text to integer

- deegree-core/deegree-core-commons/pom.xml
- deegree-spring/pom.xml
- deegree-workspaces/deegree-workspace-wps-jrxml/pom.xml
- pom.xml
The following direct or transitive dependencies had security vulnerabilities as documented by the  [Open Web Application Security Project (OWASP)] (https://www.owasp.org/index.php/Main_Page):
* org.springframework:spring-context:3.2.3.RELEASE
* org.apache.httpcomponents: httpclient: 4.2.3
* xalan: xalan:2.7.1
* com.lowagie: itext: 4.2.0
* org.powermock:powermock-module-junit4:1.6.2 used outdated org.javassist: javassist
This PR updates all those dependencies and adds the maven ```dependency-check-maven```plugin to create the report.
> Updated dependencies for which security vulnerabilities have been reported

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SqlFeatureStoreBuilder.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SqlFeatureStoreProvider.java
This pull requests fixes the creation of new SQLFeatureStores in the deegree console by correcting the version in the path of the CONFIG_SCHEMA. Currently an exception 'null' occurs and the file  is not created in the file system. 
Furthermore the exception handling is improved if the configured database connection is not available or not valid.
> Fixed creation of new SQLFeatureStore in deegree console

- deegree-core/deegree-core-protocol/deegree-protocol-wms/src/main/java/org/deegree/protocol/wms/ops/GetLegendGraphic.java
As described in #643 a NPE occurred if the style parameter is empty . This pull request fixes this by adding an additional check and using the default style name if missing.
> FIxed GetLegendGraphic with empty style parameter

- deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/metadata/SpatialMetadata.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/Capabilities130XMLAdapter.java
When WMS 1.3.0 capabilities are created a NullPointerException occurs if a layer does not have a CRS configured.
As the CRS is not mandatory (see [1]; there is a ref to group SpatialMetadata) there should not be thrown any exception.
This fix prevents the previously thrown NullPointerException.
[1] http://schemas.deegree.org/commons/spatialmetadata/3.1.0/spatialmetadata.xsd
> Fixed possible NullPointerException during creation of WMS 1.3.0 capabilities

- deegree-core/deegree-core-style/src/main/java/org/deegree/style/se/parser/GraphicSymbologyParser.java
- deegree-core/deegree-core-style/src/main/resources/META-INF/schemas/se/1.1.0/symbology.xsd
- deegree-core/deegree-core-style/src/main/resources/META-INF/schemas/se/1.1.0/text.xml
- deegree-services/deegree-webservices-handbook/src/main/sphinx/renderstyles.rst
deegree already supports ExternalGraphics with Expression as follows:
```xml
<ExternalGraphic>
<OnlineResource>
<ogc:PropertyName>app:icon</ogc:PropertyName>
</OnlineResource>
<Format>image/png</Format> 
</ExternalGraphic>	 
```
This pull requests enhanced this by the support of svgs. 
Furthermore an explanation in the documentation was added and the symbology.xsd enhanced.
> enhanced external graphics with expressions by support of svg

- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/GetCapabilitiesHandler.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/WebFeatureService.java
The value of the constraint "SOAPEncoding" in WFS capabilities is always "FALSE", even if SOAP encoding is activated.
This pull request fixes this behaviour and sets "SOAPEncoding" to "TRUE" if SOAP is activated.
> Fixed bug that value of constraint "SOAPEncoding" in WFS capabilities is always "FALSE"

- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/GetCapabilitiesHandler.java
Currently, the LatLongBoundingBox of a FeatureType is always exported in EPSG:4326 in WFS 1.0.0.
If the SRS of a FeatureType differs from EPSG:4326, the LatLongBoundingBox should be exported in that SRS (defined in WFS 1.0.0 Specification; Chapter 12.3.5).
Excerpt of WFS 1.0.0 Specification:
> The LatLongBoundingBox element is used to indicate the edges of an
> enclosing rectangle in the SRS of the associated feature type. Its purpose is
> to facilitate geographic searches by indicating where instances of the
> particular feature type exist. Since multiple LatLongBoundingBoxes can
> be specified, a WFS can indicate where various clusters of data may exist.
This fix corrects this behaviour in WFS 1.0.0 and exports LatLongBoundingBoxes in the corresponding FeatureType SRS.
> Fixed LatLongBoundingBox in WFS 1.0.0 capabilities to use SRS of FeatureType

- deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/io/WKBWriter.java
- deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/io/WKTWriter.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/config/MappedSchemaBuilderGML.java
Added check for crs-dimension before writing.
> Fix to allow inserting 3d

- deegree-core/deegree-core-cs/src/main/resources/org/deegree/cs/persistence/deegree/d3/config/crs-definitions.xml
- deegree-core/deegree-core-cs/src/main/resources/org/deegree/cs/persistence/deegree/d3/config/projection-definitions.xml
According to "1.3.3.2 Popular Visualisation Pseudo Mercator" in EPSG Guidance Note 7-2 (http://www.iogp.org/pubs/373-07-2.pdf), epsg:3857 should use a spherical formula.
* Split epsg:3857 and epsg:3395 into two seperate crs-definitions.
* Altered epsg:3857 to use a spherical formula.
* Added epsg:3856 to projection-definitions.
Ref comment in issue:
https://github.com/deegree/deegree3/issues/653
> Altered epsg:3857 to use a spherical formula

- pom.xml
- uncoupled/deegree-jaxb-resolver/pom.xml
- uncoupled/deegree-jaxb-resolver/src/main/java/org/deegree/uncoupled/jaxb/CatalogResolver.java
This pull request fixes #649 by replaceing the currently used classpath resolver from the jaxb plugin with a custom one.
The resolver tries to lookup all schemas first in `CLASSPATH:META-INF/schemas` and if not found falls back to the default behavior, online lookup.
**This resolver is not a final solution for the overall schema situation**, but the TMC agreed on 09.08.2016 that this PR is used as intermediate soultion until a rework of the build / jaxb handling was made.
On Updates to the resolver the builds have to be done manually by:
1.  Updateing the version
2.  Locally building, ideally with the oldest supported jdk (currently 1.6)
3.  Upload the artifact to the deegree repository on repo.deegree.org in the section for public 3rd party artefacts. Or by submitting the artefact to the …
> 3.4 Resolve deegree schema files localy if possible

- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/ows/exception/OWSException.java
- deegree-services/deegree-services-commons/src/api/java/org/deegree/services/controller/OGCFrontController.java
- deegree-services/deegree-services-commons/src/main/java/org/deegree/services/controller/exception/serializer/XMLExceptionSerializer.java
- deegree-services/deegree-services-commons/src/main/java/org/deegree/services/ows/OWS110ExceptionReportSerializer.java
Previously, an exception status code 500 was returned if a service with the requested identifier is not available.
Example:
* http://cite.deegree.org/deegree-webservices-3.4-RC1/services/wmts100/nonesuch
The WMTS 1.0.0 specification references in A.3.1.1 the HTTP/1.1 specification: http://www.ietf.org/rfc/rfc2616
Status code 404 is fitting more than 500:
```
10.4.5 404 Not Found
The server has not found anything matching the Request-URI. No
indication is given of whether the condition is temporary or
permanent. The 410 (Gone) status code SHOULD be used if the server
knows, through some internally configurable mechanism, that an old
resource is permanently unavailable and has no forwarding address.
This status code is commonly used when the server does not wish to
reveal exactly why the …
```
> Fixed exception status code to 404 if service with the requested identifier is not available

- deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/validation/GeometryFixer.java
- deegree-core/deegree-core-geometry/src/test/java/org/deegree/geometry/validation/GeometryFixerTest.java
The method invertOrientation in the GeometryFixer inverts the orientation of each curve segment but not the orientation of the  list of curve segments. Afterwards the curve is invalid. This pull requests provides a simple fix for this.
> Fixed orientation of inverted curves in the GeometryFixer

- deegree-core/deegree-core-gdal/src/main/java/org/deegree/commons/gdal/GdalDataset.java
This pull requests implements the support of datasets with only one band and integrated color table. Previously this datasets could was not rendered by deegree as expected.
> Enhanced GdalDatasets for support of datasets with only one band and integrated color table

- deegree-core/deegree-core-sqldialect/deegree-sqldialect-commons/src/main/java/org/deegree/sqldialect/filter/AbstractWhereBuilder.java
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-postgis/src/main/java/org/deegree/sqldialect/postgis/PostGISWhereBuilder.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStore.java
Previously, when a geometry operand was not a geometry property a NoApplicableCode exception was thrown.
Example request:
```
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs/2.0"
count="10" service="WFS" startIndex="0" version="2.0.0">
<wfs:Query xmlns:ns55="http://www.deegree.org/app" typeNames="ns55:gns_iceland">
<fes:Filter xmlns:fes="http://www.opengis.net/fes/2.0">
<fes:BBOX>
<fes:ValueReference xmlns:tns="http://www.opengis.net/gml/3.2">tns:description</fes:ValueReference>
<gml:Envelope xmlns:gml="http://www.opengis.net/gml/3.2"
srsName="urn:ogc:def:crs:EPSG::4326">
<gml:lowerCorner>62 -26</gml:lowerCorner>
<gml:upperCorner>67.11 -6</gml:upperCorner>
</gml:Envelope>
</fes:BBOX>
</fes:Filter>
</wfs:Query>
</wfs:GetFeature>
```
The FE 2.0.0 specification (OGC 09-026r1 and ISO …
> Fixed exception of WFS if geometry operand is not a geometry property

- deegree-core/deegree-core-protocol/deegree-protocol-wfs/src/main/java/org/deegree/protocol/wfs/query/xml/QueryXMLAdapter.java
Previously, when an unsupported SRS was requested via WFS 2.0 a NoApplicableCode exception was thrown.
Example request:
```
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs/2.0" count="10" service="WFS" startIndex="0" version="2.0.0"> <wfs:Query
xmlns:ns4="http://www.deegree.org/app" srsName="urn:ogc:def:crs:EPSG::32690" typeNames="ns4:gns_iceland"/> </wfs:GetFeature>
```
The WFS 2.0 specification (09-025r1) states that an InvalidParameterValue exception is expected:
```
7.6.5.5 srsName parameter
...
If the specified CRS is not supported for the specified feature type, the WFS shall raise an
InvalidParameterValue exception (see Table 3).
...
```
This fix corrects the thrown exception for the pictured case.
Following test of the OGC CITE WFS 2.0 test suite [1] is now passed due to …
> Fixed exception of WFS if unsupported SRS is requested

- deegree-core/deegree-core-base/src/main/java/org/deegree/feature/types/AppSchemaGeometryHierarchy.java
- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/geometry/GML3GeometryReader.java
Previously, CompositeSurfaces in hierarchies were not parsed for GML 3 and led to following exception:
```
XMLParsingException: Unhandled surface geometry element: '{http://www.opengis.net/gml}CompositeSurface'.
```
This fix enables parsing of CompositeSurfaces in geometry hierarchies for GML 3.
> Fixed parsing of CompositeSurfaces in hierarchies for GML 3

- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/legends/LegendBuilder.java
- deegree-layers/deegree-layers-remotewms/src/main/java/org/deegree/layer/persistence/remotewms/RemoteWmsLayerBuilder.java
This pull requests enables support of GetLegendGraphic from RemoteWMSLayer. Previously a NPE was thrown cause the legend of the RemoteWMSLayer was not available. This NPE was fixed by checking if the legend is null (e.g. not readable from remote service). Furthermore  the RemoteWMSLayerBuilder was enhanced to provide the legends from the remote service.
> Fixed GetLegendGraphic from RemoteWMSLayer

- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/tom/primitive/XMLValueMangler.java
Previously, the handling of BigDecimal data type was not correct in deegree as exponents could be returned in a GML response. For example, following property value is possible in a GetFeature response: "5.4578635E+10".
This pull request fixes that BigDecimal are always exported as plain text (without exponent).
> Fixed handling of BigDecimal data type

- deegree-datastores/deegree-featurestores/deegree-featurestore-memory/src/main/java/org/deegree/feature/persistence/memory/MemoryFeatureStoreTransaction.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStoreTransaction.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/insert/FeatureRow.java
- deegree-services/deegree-webservices-handbook/src/main/sphinx/webservices.rst
Previously, when idGenMode useExisting was not activated, a replace transaction of the WFS 2.0.0 generated a new gml:id for the replaced feature (technically, a delete and insert operation is executed).
This is not conform to the specification as a replace transaction should replace an existing feature and not create a new one.
This behaviour was fixed by always activating the UseExisting option for replace transactions. This makes replacements of existing features possbile even if idGenMode useExisting is not activated.
When discussing this pull request, it has to be considered, that the current behaviour of deegree is modified. Now, a replace transaction with disabled UseExisting option uses the gml:id of the feature of the request instead of generating a new gml:id.
In addition, …
> Updated behaviour of replace transaction in WFS 2.0.0

- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/TransactionHandler.java
This fix targets the transaction functionality of WFS 2.0.0.
Previously, when a ValueReference was updated by an update transaction the namespace was not considered. Instead, the default namespace of the FeatureType was used.
For example (POST body of update request):
```
<wfs:Transaction xmlns:wfs="http://www.opengis.net/wfs/2.0" xmlns:gml="http://www.opengis.net/gml/3.2" service="WFS"
version="2.0.0">
<wfs:Update xmlns:ns30="http://www.deegree.org/app" typeName="ns30:ft">
<wfs:Property>
<wfs:ValueReference>gml:name[1]</wfs:ValueReference>
<wfs:Value>Ce n&amp;apos;est pas Vieux-Port de Montr&amp;#xe9;al!</wfs:Value>
</wfs:Property>
<fes:Filter xmlns:fes="http://www.opengis.net/fes/2.0">
<fes:ResourceId rid="ft_411196921" />
</fes:Filter>
</wfs:Update>
</wfs:Transaction>
```
In the …
> Fixes namespace bindings of ValueReference when updating property in WFS-T 2.0.0

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStoreTransaction.java
This fix targets the locking functionality of WFS 2.0.0.
Previously, it was possible to delete locked features by transaction (via delete operation).
The fix corrects this behaviour by preventing deletion of locked features in WFS 2.0.0 (a check if features are not locked was introduced).
In addition, deegree now passes following tests of the CITE WFS 2.0 test suite (Locking CC) [1]:
* "Lock Feature And Attempt Delete"
[1] http://cite.opengeospatial.org/teamengine/
> Fixed that locked features cannot be removed by delete operation

- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/TransactionHandler.java
This fix targets the transaction functionality of WFS 2.0.0.
Previously, when transactions were done with invalid geometries, the WFS 2.0.0 threw an NoApplicableCode exception with status code 500.
The specification says that following is expected:
* status code: 400
* exception code:  InvalidValue
Excerpt from WFS 2.0.0 specification:
```
15.2.5.2.1 Property element
In all cases, if the specified action results in invalidating the feature instance 
according to the feature type schema obtained using a DescribeFeatureType operation 
(see Clause 9), the server shall raise a InvalidValue exception (see 7.5).
```
This fix corrects the status and exception codes to implement the expected behaviour.
In addition, deegree now passes following test of the CITE WFS 2.0 test suite (Transactional …
> Fixed exception code and status code of response when invalid geometry is inserted

- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/strokes/TextStroke.java
The following style renders the labels in a center of a line with at least 10 initialGap.
```xml
<LabelPlacement> 
<LinePlacement> 
<PerpendicularOffset>-10</PerpendicularOffset> 
<IsRepeated>false</IsRepeated>
<InitialGap>10</InitialGap> 
<PreventUpsideDown>true</PreventUpsideDown> 
<Center>true</Center> 
<WordWise>false</WordWise> 
</LinePlacement>
</LabelPlacement>
```
Currently the text is also rendered if the length of the label with initialGap (if center is not possible) is longer than the line width, which leads to truncated text.
This pull requests fixes this by not rendering this labels.
> Fixed rendering of text with initialGap and center

- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/WebFeatureService.java
This pull request enhanced #642 to throw the correct exception for WFS 2.0.0 SOAP requests. In case of an XMLParsingException an OperationProcessingFailed should be thrown instead of an InvalidParameterValue.
> Fixed exception code to OperationProcessingFailed (WFS 2.0.0, SOAP)

- deegree-core/deegree-core-base/src/main/java/org/deegree/feature/Features.java
Currently, features are lost if they have the same sort position.
This is fixed by using a list instead of a set.
> Fixed sort mechanism for features to keep all features being at the same sort position

- deegree-services/deegree-services-wfs/pom.xml
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/WebFeatureService.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/gml/GmlFormat.java
Currently the WFS service sends the configured mime-type as content type to the client as it got read from the configuration.
Under Weblogic this reults to a problem if the configuration is formated like the following example: 
```xml
<GMLFormat gmlVersion="GML_2">
<MimeType>
<![CDATA[text/xml; subtype="gml/2.1.2"]]>
</MimeType>
<MimeType>
<![CDATA[text/xml; subtype=gml/2.1.2]]>
</MimeType>
<GetFeatureResponse>
<DisableStreaming>true</DisableStreaming>
</GetFeatureResponse>
</GMLFormat>
```
This configuration fragment introduced additional white-space/control characters before or after the content-type so that a java/httpclient software faild to handle the transfer encoding of the result of deegree.
The effect could be fixed by removing the xml formatting, which is not a good solution as …
> 3.4 Bugfix: prevent control characters in content-type that break the transfer encoding

- deegree-core/deegree-core-base/src/main/java/org/deegree/filter/xml/Filter200XMLEncoder.java
- deegree-core/deegree-core-base/src/test/java/org/deegree/filter/xml/Filter200XMLEncoderParameterizedTest.java
- deegree-core/deegree-core-base/src/test/resources/org/deegree/filter/xml/v200/testfilter8.xml
PropertyIsNil filter fails if ResponsePaging is activated:
```
<ows:Exception exceptionCode="NoApplicableCode">
<ows:ExceptionText>Encoding of operator subtype COMPARISON is not supported yet!</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>
```
This bug was fixed by adding the missing encoding of PropertyIsNil to Filter200XMLEncoder.
> Fixed bug causing PropertyIsNil filter to fail if ResponsePaging is activated

- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/LockFeatureHandler.java
When a WFS is used to request LockFeature via SOAP, a NPE occurs:
```
<ows:ExceptionReport xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd" version="2.0.0" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<ows:Exception exceptionCode="InvalidRequest">
<ows:ExceptionText>java.lang.NullPointerException</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>
```
This pull request fixes this so that a valid response is returned (equal to the one retrieved by POST).
> Fixed NullPointerException occuring when LockFeature (WFS) is requested via SOAP

- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/WMSController130.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/WMSControllerBase.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/exceptions/ExceptionsManager.java
If HTML is configured as output format for capabilities, the service returns an empty page due to a not closed xml writer.
This pull requests fixes this issue.
> Fixed bug leading to erroneous HTML capabilities

- deegree-services/deegree-services-commons/src/main/java/org/deegree/services/controller/exception/serializer/SOAPExceptionSerializer.java
- deegree-services/deegree-services-commons/src/main/java/org/deegree/services/controller/exception/serializer/XMLExceptionSerializer.java
- deegree-services/deegree-services-commons/src/main/java/org/deegree/services/ows/OWS110ExceptionReportSerializer.java
- deegree-services/deegree-services-commons/src/main/java/org/deegree/services/ows/PreOWSExceptionReportSerializer.java
- deegree-services/deegree-services-commons/src/test/java/org/deegree/services/controller/exception/serializer/SOAPExceptionSerializerTest.java
- deegree-services/deegree-services-csw/src/main/java/org/deegree/services/csw/CswExceptionReportSerializer.java
Serialization of SOAP 1.1 exceptions fails:
```
Caused by: java.lang.UnsupportedOperationException
at org.apache.axiom.soap.impl.llom.soap11.SOAP11Factory.createSOAPFaultValue(SOAP11Factory.java:170)
at org.deegree.services.controller.exception.serializer.SOAPExceptionSerializer.serializeExceptionToXML(SOAPExceptionSerializer.java:143)
at org.deegree.services.controller.exception.serializer.XMLExceptionSerializer.serializeException(XMLExceptionSerializer.java:65)
at org.deegree.services.controller.AbstractOWS.sendException(AbstractOWS.java:447)
... 23 more
```
In addition, the OWS110 exception codes are erroneous (always 200 instead of 400/403/500).
Both issues are fixed by this pull request.
> Fixed serialization and status code of SOAP 1.1 exceptions

- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/ows/exception/OWSException.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-commons/src/main/java/org/deegree/feature/persistence/lock/DefaultLockManager.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-commons/src/main/java/org/deegree/feature/persistence/lock/LockHasExpiredException.java
- deegree-services/deegree-services-commons/src/main/java/org/deegree/services/ows/OWS110ExceptionReportSerializer.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/WebFeatureService.java
This fix targets the locking functionality of WFS 2.0.0.
Previously, when LockFeature was requested with a non existent lockId, the WFS 2.0.0 threw an InvalidParameterValue exception with status code 400.
The specification says that following is expected:
* status code: 403
* exception code: LockHasExpired
Excerpt from WFS 2.0.0 specification:
```
12.2.4.2 lockId parameter
A lockId parameter specified within a LockFeature operations shall be used to reset the expiry time of an existing lock.
...
Such a LockFeature operation shall be executed before the specified lock has expired; otherwise the server shall raise a LockHasExpired exception (see Table 3).
...
```
This fix corrects the status and exception codes to implement the expected behaviour.
In addition, deegree now passes following …
> Fixed exception code and status code of response when non existent lock is requested

- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/Java2DLabelRenderer.java
Using the function  _InteriorPoint_ to render a label causes a NullPointerException if the calculated point is outside the map extent.  A null check was introduced to fix this problem on a very low level and to avoid further problems with other configurations.
> Fixed NPE if geoemtry to render is outside the requested map extent

- deegree-services/deegree-webservices/src/main/java/org/deegree/console/webservices/ServiceConfig.java
Resolves #712
Fixed path to metadata example URL. Now, new metadata for a service can be created via deegree console.
Previously, a NullPointerException occured as documented in #712.
> Fixed path to metadata example url

- deegree-services/deegree-webservices/src/main/java/org/deegree/console/Config.java
Resolves  #750
Previously, when resource was deactivated via deegree console it disappeared until workspace reload was executed.
Fix adds the resource to ResourceManager again after it has been destroyed. Due to this the resource is still displayed in the deegree console after is is was deactivated (no reload necessary).
This fix is more a workaround as the OGCFrontController (for service resource; corresponding classes exist for other resources) should check if a resource has the state deactivated and skip the resource if this is the case. The destroying of the resource may become obsolete when this check is implemented.
> Fixed removal of deactivated resources from deegree console

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStore.java
This pull request enhances PR #719 which has already been merged.
Previously, if a WFS was requested with result type hits and there is a geometry operand which is not a geometry property status code 500 was still returned.
This pull request fixes the behaviour and corrects the exception to InvalidParameterValue for the case resultType=hits by passing the exception (explanation why InvalidParameterValue is correct can be found in #719).
> Fixed exception of WFS if geometry operand is not a geometry property for result type hits

- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/xml/stax/XMLStreamUtils.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/TransactionHandler.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/WebFeatureService.java
This PR fixes an exception thrown cause of an unexpected event type of the XMLStreamReader by skipping the START_DOCUMENT.
Previously the following exception was thrown:
```
<soapenv:Envelope xsi:schemaLocation="http://schemas.xmlsoap.org/soap/envelope http://schemas.xmlsoap.org/soap/envelope" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<soapenv:Body>
<soapenv:Fault>
<faultcode>Sender</faultcode>
<faultstring>Required type START_ELEMENT, actual type START_DOCUMENT</faultstring>
<detail>
<ows:ExceptionReport xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd" version="2.0.0" xmlns:ows="http://www.opengis.net/ows/1.1">
<ows:Exception …
```
> Fixed Transactions requests with SOAP encoding  

- deegree-core/deegree-core-protocol/deegree-protocol-commons/src/main/java/org/deegree/protocol/wps/client/process/ProcessExecution.java
- deegree-core/deegree-core-protocol/deegree-protocol-commons/src/test/java/org/deegree/protocol/wps/client/WPSClientTest.java
- deegree-core/deegree-core-protocol/deegree-protocol-commons/src/test/resources/org/deegree/protocol/wps/client/curve.xml
Currently, if something is wrong with a WPS request sent from the deegree WPS client (e.g. a required WPS input parameter is missing) I get a java.io.IOException:
java.io.IOException: Server returned HTTP response code: 400 for URL: http://localhost:8088/deegree-webservices/services/wps
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
at org.deegree.protocol.wps.client.process.ProcessExecution.sendExecute(ProcessExecution.java:356)
at org.deegree.protocol.wps.client.process.ProcessExecution.executeAsync(ProcessExecution.java:186)
I find it more useful to get the OWSExceptionReport instead, like so:
org.deegree.protocol.ows.exception.OWSExceptionReport: …
> WPS client: Avoid java.io.IOException if server returns HTTP error code, rather get the OWSException

- deegree-core/deegree-core-protocol/deegree-protocol-commons/src/main/java/org/deegree/protocol/wps/client/process/ProcessExecution.java
- deegree-core/deegree-core-protocol/deegree-protocol-commons/src/test/java/org/deegree/protocol/wps/client/WPSClientTest.java
- deegree-core/deegree-core-protocol/deegree-protocol-commons/src/test/resources/org/deegree/protocol/wps/client/curve.xml
This pull request contains the same changes as #739 but for the stable development branch. (I hope I understood your branches correctly.)
> stable WPS client: Avoid java.io.IOException if server returns HTTP error code, rather get the OWSException

- deegree-core/deegree-core-base/src/main/java/org/deegree/feature/stream/EmptyFeatureInputStream.java
In an previous pull request java 1.7 or newer api was used this pull requests fixed that.
http://download.deegree.org/documentation/3.4-RC2/html/installation.html#f1
> 3.4 Fix compability issues with jdk6

- deegree-core/deegree-core-protocol/deegree-protocol-commons/src/main/java/org/deegree/protocol/wps/client/wps100/ExecuteResponse100Reader.java
When parsing complex WPS outputs, the client doesn't recognize mimetype "application/gml+xml" as an XML output and treats it as binary instead.
According to [MIME Media Types for GML](https://portal.opengeospatial.org/files/?artifact_id=37743), "application/gml+xml" is the mimetype for GML.
This change lets the client recognize all mimetypes as XML outputs that contain "xml" as a separate word .
> Fix WPS client to support xml sub-mimetypes like gml+xml

- LICENSE.txt
- README.md
To prevent that we loose contributions due to missing license file added license section in README and in Maven default license.txt.
An example where a contribution was revoked is in https://github.com/deegree/deegree3/pull/687#issuecomment-195004790
> Added LGPL v2.1 license file and section into README.md file

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/MappingContextManager.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/java/org/deegree/feature/persistence/sql/mapper/MappingContextManagerTest.java
Previously, the maxLength set in MappingContextManager was not evaluated correctly leading to column names exceeding the length set by this parameter.
Issue was reported in https://github.com/deegree/deegree3/issues/827.
This fix enables that the column names are always truncated to the length specified by maxLength.
> Fix MappingContextManager to evaluate maxLength correctly

- deegree-services/deegree-webservices-handbook/src/main/sphinx/renderstyles.rst
The recode function in the deegree -webservices-handbook does not work as documented in the example. The example was fixed.
> Fixed example of the recode function

- deegree-client/deegree-jsf-core/src/main/java/org/deegree/client/core/filter/InputFileFilter.java
Previously, special characters in configuration files were broken after editing and saving with the deegree console. This PR sets UTF-8 explicitly as character encoding to avoid broken characters.
PR for 3.4: #790
> Fixed broken characters caused by the deegree console

- deegree-core/deegree-core-base/src/main/java/org/deegree/filter/xml/FilterCapabilitiesExporter.java
This pull request fixes the namespace bindings of GeometryOperands for GML 3.2 in the WFS 2.0.0 capabilities  
**Before**
```
<fes:GeometryOperands xmlns:gml="http://www.opengis.net/gml"
xmlns:gml32="http://www.opengis.net/gml">
<fes:GeometryOperand name="gml:Box"/>
<fes:GeometryOperand name="gml:Envelope"/>
...
<fes:GeometryOperand name="gml:CompositeSurface"/>
<fes:GeometryOperand name="gml32:Envelope"/>
<fes:GeometryOperand name="gml32:Point"/>
...
</fes:GeometryOperands>
```
**Fixed**
```
<fes:GeometryOperands xmlns:gml="http://www.opengis.net/gml" 
xmlns:gml32="http://www.opengis.net/gml/3.2">
<fes:GeometryOperand name="gml:Box"/>
<fes:GeometryOperand name="gml:Envelope"/>
...
<fes:GeometryOperand name="gml32:Envelope"/>
<fes:GeometryOperand name="gml32:Point"/>
... …
```
> Fixed namespace binding of GeometryOperands in WFS 2.0.0 capabilities

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/config/SQLFeatureStoreConfigWriter.java
- deegree-services/deegree-webservices-handbook/src/main/sphinx/featurestores.rst
- deegree-services/deegree-webservices-handbook/src/main/sphinx/filterencoding.rst
This enhancement allows to pass a list of properties to handle as primitive xlink:href mappings instead of feature mappings.
Furthermore the documentation was improved to explain the difference between xlink:href and feature mapping against the background of fiitering on xlink:href attributes.
> Enhance SQLFeatureStoreConfigWriter to differentiate between feature and xlink:href mapping 

- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/feature/GMLFeatureWriter.java
Fix for #781.
The exception occurred cause of a missing namespace of the attribute `xsi:nil`. This is fixed by a adding special handling of `xsi:nil`and writing the attribute with namespace.
> Fixed XSLT transformation in GetFeatureInfo request if GML contains a xsi:nil property 

- deegree-core/deegree-core-base/src/main/java/org/deegree/feature/Features.java
- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/GMLStreamReader.java
- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/commons/AbstractGMLObjectReader.java
- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/reference/FeatureReference.java
- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/tom/Reference.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/insert/InsertRowManager.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/TransactionHandler.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/WebFeatureService.java
- deegree-services/deegree-services-wfs/src/main/resources/META-INF/schemas/services/wfs/3.4.0/wfs_configuration.xsd
- deegree-services/deegree-webservices-handbook/src/main/sphinx/webservices.rst
A new optional attributes can be configured in EnableTransactions element: allowFeatureReferencesToDatastore
If allowFeatureReferencesToDatastore is true it is allowed to insert features with references to already inserted features, default is false.
Solves issue #749.
> Enhance WFS-T by being able to insert features that reference features which are already inserted

- deegree-core/deegree-core-protocol/deegree-protocol-commons/src/test/resources/org/deegree/protocol/wps/client/curve.xml
Fixing bug #772: Avoid usage of default namespace in curve.xml
> Avoid usage of default namespace in curve.xml

- .travis.yml
- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/utils/ArrayUtils.java
- deegree-core/deegree-core-commons/src/test/java/org/deegree/commons/utils/ArrayUtilsTest.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/id/IdAnalyzer.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/java/org/deegree/feature/persistence/sql/id/IdAnalyzerTest.java
Hi,
this PR supersedes #850.
It reduces the PR to the actual changed files and relevant commits.
Fore actual content details, please have a look at https://github.com/deegree/deegree3/pull/850
Regards
Martin
> Fix #848 - new [SQLFeatureStore] Deleting features fails for certain feature type prefix configurations

- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/WebFeatureService.java
- deegree-services/deegree-services-wfs/src/main/resources/META-INF/schemas/services/wfs/3.4.0/wfs_configuration.xsd
- deegree-services/deegree-webservices-handbook/src/main/sphinx/webservices.rst
Fixes #868 
The new idGenMode is named **UseExistingResolvingReferencesInternally**. Example:
````
<EnableTransactions idGen="UseExistingResolvingReferencesInternally" >true</EnableTransactions>
```
> Replaced WFS configuration option allowFeatureReferencesToDatastore by new idGenMode

- deegree-core/deegree-core-base/src/main/java/org/deegree/feature/xpath/GMLObjectNavigator.java
- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/feature/GMLFeatureWriter.java
- deegree-core/deegree-core-base/src/test/java/org/deegree/feature/xpath/GMLObjectXPathTest.java
- deegree-core/deegree-core-base/src/test/resources/org/deegree/gml/misc/feature/CustomPropertiesGml32.xml
- deegree-core/deegree-core-base/src/test/resources/org/deegree/gml/misc/schema/CustomPropertiesGml32.xsd
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStore.java
This pull requests fixes several bugs concerning xlink:href attributes as primitive mapping instead of feature mapping. This is used in mappings for INSPIRE schemas if the xlink:href attribute contains codelists instead of feature references. 
Fixed bugs in detail:
* Fixes #875
* Missing xlink:href attributes in WFS GetFeature response are fixed
*  Fixes #866
* Missing nilReason attributes in WFS GetFeature response are fixed
* Fixes #587
* Filtering of xlink:href in SLD or FeatureLayer configurations are applied in relational and blob mode
This pull requests reverts changes from pull request #527 in SQLFeatureStore. The changes in #527 result in empty GetFeature responses in case a SQLFeatureStore with blob mode is configured and the request contains a filter. The filter is applied to …
> Fixes several bugs concerning xlink:href attribute

- deegree-core/deegree-core-base/src/main/java/org/deegree/feature/types/DynamicFeatureType.java
- deegree-core/deegree-core-base/src/main/java/org/deegree/feature/types/FeatureType.java
- deegree-core/deegree-core-base/src/main/java/org/deegree/feature/types/GenericFeatureCollectionType.java
- deegree-core/deegree-core-base/src/main/java/org/deegree/feature/types/GenericFeatureType.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/rules/FeatureBuilderRelational.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/WfsFeatureStoreManager.java
Currently, a FeatureType defined in the application schema and configured in SQLFeatureStore is not available (does not exist in capabilities, GetFeature is not supoorted, ...) if a property of Type AbstractFeatureMemberType is configured.
Example from http://www.locationframework.eu/schemas/AdministrativeUnits/1.0/AdministrativeUnits.xsd:
```
...
<element name="AdministrativeUnit" substitutionGroup="au:AdministrativeUnit" type="elf-au:AdministrativeUnitType"/>
<complexType name="AdministrativeUnitType">
...
<element maxOccurs="unbounded" minOccurs="0" name="adminUnitArea">
<annotation>
<appinfo>
<reversePropertyName xmlns="http://www.opengis.net/gml/3.2">elf-au:adminUnit</reversePropertyName>
</appinfo>
</annotation>
<complexType>
<complexContent>
<extension …
```
> Enabled support of FeatureCollections as FeatureTypes

- CONTRIB.md
Transferred contribution guidelines and project structures and procedures from old wiki http://wiki.deegree.org/deegreeWiki/GettingInvolved and http://wiki.deegree.org/deegreeWiki/StructuresAndProcedures
Partly updated to GitHub infrastructure and committee activities.
> #603 Transferred content from old wiki 

- deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/io/imageio/geotiff/GeoTiffWriter.java
- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/ImageSerializer.java
- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/context/ImageRenderContext.java
- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/context/RenderingInfo.java
- deegree-services/deegree-services-wms/pom.xml
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/WMSController.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/plugins/ImageSerializerGeoTiff.java
- deegree-services/deegree-services-wms/src/main/resources/META-INF/schemas/services/wms/3.4.0/wms_configuration.xsd
- deegree-services/deegree-webservices-handbook/src/main/sphinx/webservices.rst
Modified the custom format implementation of WMS. For FeatureInfo the xml-schema supports properties and for GetMap CustomGetMapFormats can be added by implementing the ImageSerializer. 
In the ImageSerializerGeoTiff a custim GetMap-Format is added for GeoTIFF.
> Wms custom format cleanup

- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/xml/stax/XMLInputFactoryUtils.java
During parsing of GML being imported, string values may be split into different child elements. This leads to the behaviour that only one of those child elements is saved into database and thus just a truncated value is returned by services.
E.g. property gml:identifier with value ```https://test-request.test/test-path/featuretype-identifier/feature_71``` is part of the imported GML.
This value is parsed into two childs by GML parser:
* ```https://test-request.test/test-path/featuretype-identifier/feature_7```
* ```1```
Just the value ```1``` is saved into database.
This fix prevents splitting of string values during parsing of GML when XMLInputFactoryUtils is used and thus values are not truncated in database and service output.
> WFS-T import leads to truncated values in string properties

- deegree-spring/pom.xml
- pom.xml
The OSWAP Maven Plugin has detected known vulnerabilities in used dependencies. This PR fixes some of them by upgrading to more recent versions.
> Update dependencies with known vulnerabilities

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStore.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/blob/FeatureBuilderBlob.java
Previously, when a requested feature (by resourceid) did not match the requested feature type (by typenames) a FeatureCollection was returned.
The WFS 2.0 specification (09-025r1) states that an InvalidParameterValue exception is expected (Chapter 7.9.2.4.1 typeNames parameter, page 34):
```
For KVP-encoded ad hoc query expressions the typeNames parameter shall be encoded 
using the TYPENAMES keyword (see Table 8). The TYPENAMES parameter is mandatory 
in all cases except when the RESOURCEID parameter is specified. In this case the 
TYPENAMES parameter may be omitted because each feature instance can be 
identified by its resource identifier alone (see 7.2). If both the TYPENAMES and
RESOURCEID parameters are specified then all the feature instances identified by 
the RESOURCEID parameter …
```
> Fixed exception of WFS if requested feature (by resourceid) does not match the requested feature type (by typenames)

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/rules/FeatureBuilderRelational.java
A SQLFeatureStore configuration with a gml:TimePeriod results in empty properties in GetFeature-Response. Example for the configuration:  
**SQLFeatureStore**:
```
<Complex path="app:period">
<Complex path="gml:TimePeriod">
<Primitive path="@gml:id" mapping="osm_timestamp_modified_id" />
<Primitive path="gml:beginPosition" mapping="osm_timestamp" type="dateTime"/>
<Primitive path="gml:endPosition" mapping="osm_timestamp_modified" type="dateTime"/>
</Complex>
</Complex>
```
**Application schema**:
```
<element name="period" minOccurs="0" type="gml:TimePeriodPropertyType" />
```
**Service**:
DisableDynamicSchema = true is required to avoid an exception in DescribeFeatureTypes
```
<GMLFormat gmlVersion="GML_32">
<MimeType>application/gml+xml; version=3.2</MimeType>
<MimeType>text/xml; …
```
> Fixed creation of gml time properties

- deegree-layers/deegree-layers-remotewms/src/main/java/org/deegree/layer/persistence/remotewms/RemoteWMSLayer.java
Configuring the WMS [1]  as a remote service leads to unexpected (empty) GetMap responses. in the theme configuration the layers are merged into one Theme:
```
<Theme>
<Identifier>ALK</Identifier>
<d:Title>ALK (B1 - B6)</d:Title>
<Layer>adv_alkis_tatsaechliche_nutzung</Layer>
<Layer>adv_alkis_gewaesser</Layer>
<Layer>adv_alkis_vegetation</Layer>
<Layer>adv_alkis_verkehr</Layer>
<Layer>adv_alkis_siedlung</Layer>
<Layer>adv_alkis_gesetzl_festlegungen</Layer>
<Layer>adv_alkis_bodensch</Layer>
<Layer>adv_alkis_oeff_rechtl_sonst_festl</Layer>
<Layer>adv_alkis_weiteres</Layer>
<Layer>adv_alkis_bauw_einricht</Layer>
<Layer>adv_alkis_gebaeude</Layer>
<Layer>adv_alkis_flurstuecke</Layer>
</Theme>
```
The service contains layers 
1. with three style "Farbe", "Gelb" and "Grau" (e.g. …
> Fixed unexpected GetMap responses from remote WMS

- deegree-core/deegree-core-protocol/deegree-protocol-wfs/src/main/java/org/deegree/protocol/wfs/query/kvp/QueryKVPAdapter.java
This allows GetFeature (GET) requests with multiple typenames. Previously the request was interpreted as Join.
Fixes #666
> Fixed parsing of multiple type names from GET GetFeature request if filter is null

- deegree-services/deegree-webservices-handbook/src/main/sphinx/installation.rst
Added links to ZIP distribution bundle, Docker Image and other improvements which are relevant to Java SE 8. See issue #905 for example.
> Updated deegree web services handbook chapter 2. Installation

- deegree-tools/pom.xml
Moved module  `deegree-tools-config`to Maven `oracle` profile.
> Fixes build issue on travis-ci missing access to oracle libraries

- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/GeometryClipper.java
- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/Java2DLabelRenderer.java
If the requested bounding box in a GetMap request splits the geometry feature into a multpolygon  (e.g. a 'banana'-geometry into the two ends of the 'banana') the label is rendered in the center of the original geometry, which may be somewhere outside the geometry (e.g. between the two ends of the 'banana').
This pull requests fixes this by calculating points into the visible parts of the geometry in the map  if **auto="true"** is configured.
Example 
```
<?xml version="1.0" encoding="UTF-8"?>
<FeatureTypeStyle
version="1.1.0"
xmlns="http://www.opengis.net/se"
xmlns:wupp="http://www.deegree.org/app"
xmlns:ogc="http://www.opengis.net/ogc"
xmlns:sed="http://www.deegree.org/se"
xmlns:deegreeogc="http://www.deegree.org/ogc"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" …
```
> Improves the rendering of labels in polygons

- .travis.yml
Current builds on Travis-ci either reached 50 minutes timeout or log output reached maximum of 4MB log output (see https://docs.travis-ci.com/user/common-build-problems/#log-length-exceeded).
This change is setting maven output to quiet using the `-q` option and add the `-C` option to check the checksums strictly.
> Changed maven build to produce no output

- deegree-core/deegree-core-protocol/deegree-protocol-csw/src/main/java/org/deegree/protocol/csw/client/CSWClient.java
- deegree-core/deegree-core-protocol/deegree-protocol-csw/src/test/java/org/deegree/protocol/csw/client/CSWClientTest.java
CSW client:
- Adding getIsoRecords method that takes a constraint (current getIsoRecords methods ignore constraint and replace it with null).
- Attaching cause to exceptions thrown during XML export to better track problems.
- Adding basic integration test for CSW client. It needs the demo_csw_url property set in $HOME/.deegree-test.properties to a CSW URL.
> CSW client changes: getIsoRecords method with constraints & integration test

- deegree-services/deegree-services-config/src/main/java/org/deegree/services/config/actions/Upload.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/workspace/WorkspaceBean.java
- deegree-services/deegree-webservices/src/main/webapp/console/client/download.jsp
Adds additional error handling to uploading and downloading files.
> Improve uploading/downloading files in deegree console

- deegree-datastores/deegree-featurestores/deegree-featurestore-commons/src/main/java/org/deegree/feature/persistence/BBoxTracker.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-commons/src/main/java/org/deegree/feature/persistence/cache/BBoxPropertiesCache.java
This PR improves the exception handling concerning bbox cache properties in case the coordinate system of a geometry is not set.
> Improve exception handling concerning bbox cache properties

- CONTRIB.md
- CONTRIBUTORS.md
- README.md
This PR updates the legal section to align with [OSGeo Project Graduation Checklist
Version 2.0](https://www.osgeo.org/resources/project-graduation-checklist/) and general OSS recommendations and furthermore adding a section with the list of current copyright holders.
> Updated legal section in Contribution Guidelines

- deegree-services/deegree-webservices/pom.xml
- deegree-services/deegree-webservices/src/main/resources/log4j.properties
Fixes #962 by disabling the `deegree-maven-plugin` goal `assemble-log4j` and provides a default `log4j.properties` configuration file matching current log4j 1.2 provider.
This is considered as a temporary fix.
> Fixes #962 by disabling the deegree-maven-plugin goal assemble-log4j 

- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/TransactionHandler.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/WebFeatureService.java
This pull request removes the check of area of use of CRS during insert.
This solves #969 partly.
Pull request #971 adds a configuration option to enable the check of area of use of CRS during insert by configuration.
> Remove check of area of use of CRS during insert

- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/proxy/ProxySettings.java
**Scenario:**
User wants to use deegree with a forwarding proxy for outgoing requests.
The user configures HTTP proxy host, HTTP proxy port, HTTP proxy user and HTTP proxy password in `proxy.xml`.
Used workspace contains GML schema referencing external resources. Also, a remote WMS is configured.
**Status without this pull request:**
HTTP proxy host and HTTP proxy port are used correctly during initialisation of workspace.
However, HTTP proxy user and HTTP proxy password are not considered during initialisation of FeatureStore using GML schema referencing external resources and of remote WMS. Instead, HTTP status code 407 is returned by proxy.
**Fix provided by this pull request:**
Authenticator is implemented enabling proxy authentication for above described scenario.
Fixes #947.
> Fix incomplete implementation of proxy authentication

- deegree-services/deegree-services-commons/src/main/java/org/deegree/services/ows/PreOWSExceptionReportSerializer.java
Fixes an NPE when an exception is serialized and the message is null (concerns WMS 1.3, WFS 1.0).
> Fix NPE in exception serializer if exception is NPE

- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/GMLInputFactory.java
If DisabledResources are disabled in the WFS configuration an error may occur during insert:
```
[13:05:23] ERROR: [AbstractOWS] An error occurred while trying to send an exception: java.io.FileNotFoundException: /usr/local/tomcat/webapps/deegree-webservices/WEB-INF/lib/deegree-services-wmts-3.4.1.jar (Too many open files)
java.lang.IllegalStateException: java.io.FileNotFoundException: /usr/local/tomcat/webapps/deegree-webservices/WEB-INF/lib/deegree-services-wmts-3.4.1.jar (Too many open files)
at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.getArchiveEntry(AbstractSingleArchiveResourceSet.java:100)
at org.apache.catalina.webresources.AbstractArchiveResourceSet.getResource(AbstractArchiveResourceSet.java:262)
at …
```
> Fixes "Too many open files" in case external resources are not available

- deegree-core/deegree-core-sqldialect/deegree-sqldialect-commons/src/main/java/org/deegree/sqldialect/filter/AbstractWhereBuilder.java
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-postgis/src/main/java/org/deegree/sqldialect/postgis/PostGISWhereBuilder.java
Previously, usage of Temporal Filter After, Before, During, TEquals with PostgreSQL did not have a effect on the returned features as the filter was not applied.
This pull requests provides an implementation of these filters for PostgreSQL.
In addition, temporal filters can now be applied with following input:
- After
- Literal
- TimeInstant
- TimePeriod
- Before
- Literal
- TimeInstant
- TimePeriod
- TEquals
- Literal
- TimeInstant
- During
- TimePeriod
> Implemented Temporal Filter After, Before, During, TEquals for PostgreSQL

- deegree-services/deegree-services-commons/src/main/java/org/deegree/services/ows/capabilities/OWSCapabilitiesXMLAdapter.java
This PR makes the configuration of extended capabilities in the WFS configuration more flexible. The enclosing ows:ExtendedCapabilities can be omitted in the configuration. Until now this leads to an invalid capabilities document.
> Enhanced export ofExtendedCapabilities in WFS 1.1.0 and 2.0.0

- deegree-layers/deegree-layers-coverage/src/main/java/org/deegree/layer/persistence/coverage/CoverageDimensionHandler.java
- deegree-layers/deegree-layers-coverage/src/main/java/org/deegree/layer/persistence/coverage/CoverageFeatureInfoHandler.java
- deegree-layers/deegree-layers-coverage/src/main/java/org/deegree/layer/persistence/coverage/CoverageFeatureTypeBuilder.java
- deegree-layers/deegree-layers-coverage/src/main/java/org/deegree/layer/persistence/coverage/CoverageLayer.java
- deegree-layers/deegree-layers-coverage/src/main/java/org/deegree/layer/persistence/coverage/CoverageLayerData.java
- deegree-layers/deegree-layers-coverage/src/main/resources/org/deegree/layer/persistence/coverage/gfiSchema.xsd
This pull request enhances the GetFeatureInfo response of a coverage layer with dimensions to additionally return the UnitsOfMeasure. The UOM is added as an attribute to the corresponding element.
Example:
```
<FeatureCollection xmlns="http://www.opengis.net/wfs" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:gml="http://www.opengis.net/gml" xsi:schemaLocation="http://www.deegree.org/app http://localhost:8080/deegree-webservices/services/wms?request=GetFeatureInfoSchema&amp;layers=test http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.0.0/WFS-basic.xsd">
<gml:boundedBy>
<gml:null>missing</gml:null>
</gml:boundedBy>
<gml:featureMember>
<app0:data xmlns:app0="http://www.deegree.org/app">
<app0:value uom="m">612</app0:value> …
```
> Enhanced GFI response of coverage layer with dimension to return UOM

- deegree-layers/deegree-layers-feature/src/main/java/org/deegree/layer/persistence/feature/FeatureLayer.java
As result of this fix, a GetFeatureInfo request against a group layer returns the result of all sub-layers instead of the result of just the first sub-layer.
Currently, this is just possible if the feature type is configured in the layer configuration.
Fixes #985.
> Fix GetFeatureInfo on group layers

- deegree-services/deegree-services-config/src/main/java/org/deegree/services/config/actions/Upload.java
By not only checking if the destination denotes a path inside the workspace directory but also if the destination path actually exists (because of utilizing FileUtils.directoryContains instead of FilenameUtils.directoryContains) the check introduced by #955 inadvertently prohibited all uploading of new configuration files via the API.
fixes #988
> Check if destination denotes a path inside the workspace directory

- deegree-core/deegree-core-gdal/pom.xml
- pom.xml
Fixes #994 - upgrade to official version 1.11.2 as preparation to move to offical 2.x version
> Upgrade gdal to official release version 2.4.x

- deegree-core/deegree-core-protocol/deegree-protocol-wfs/src/main/java/org/deegree/protocol/wfs/query/xml/QueryXMLAdapter.java
When doing a GetFeature request to the WFS endpoint via a posted XML
query, the name of the SRS that was passed into the request by the user
was not retained, but an alias from the looked-up CRS was stated in the
returned features.
This only happened in XML POST requests, not in KVP GET requests.
refs #933
> fix(#933): retain requested SRS name in CRS object for XML requests

- deegree-core/deegree-core-sqldialect/deegree-sqldialect-commons/src/main/java/org/deegree/sqldialect/AbstractSQLDialect.java
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-commons/src/main/java/org/deegree/sqldialect/SQLDialect.java
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-mssql/src/main/java/org/deegree/sqldialect/mssql/MSSQLDialect.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-commons/src/main/java/org/deegree/feature/persistence/FeatureStore.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-commons/src/main/java/org/deegree/feature/persistence/query/Query.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-memory/src/main/java/org/deegree/feature/persistence/memory/MemoryFeatureStore.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-remotewfs/src/main/java/org/deegree/feature/persistence/remotewfs/RemoteWFSFeatureStore.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-shape/src/main/java/org/deegree/feature/persistence/shape/ShapeFeatureStore.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-simplesql/src/main/java/org/deegree/feature/persistence/simplesql/SimpleSQLFeatureStore.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStore.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/gml/request/GmlGetFeatureHandler.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/query/QueryAnalyzer.java
Fixes #648 and replaces #832. This pull request enhances the paging mechanism for WFS GetFeature response processing when parameter STARTINDEX and COUNT are provided.
It uses SQL `OFFSET/ROWS FETCH NEXT` syntax which requires at least Oracle 12c, MS SQLServer 2008 or PostgreSQL 9.4. The behavior of PR  #619 is preserved.
> Enhanced implementation for WFS 2.0 response paging

- deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
Handbook was enhanced describing that Extended Capabilities are not supported by WMS 1.1.1.
Caution: This pull request bases on #1001. Thus, #1001 should be merged first.
> Update handbook regarding support of Extended Capabilities in WMS 1.1.1

- deegree-core/deegree-core-base/pom.xml
- deegree-core/deegree-core-commons/pom.xml
- deegree-core/deegree-core-commons/src/test/java/org/deegree/commons/xml/XsltUtilsTest.java
- deegree-core/deegree-core-commons/src/test/resources/org/deegree/commons/xml/feature.gml
- deegree-core/deegree-core-commons/src/test/resources/org/deegree/commons/xml/featureToHtml-Xslt10.xslt
- deegree-core/deegree-core-commons/src/test/resources/org/deegree/commons/xml/featureToHtml-Xslt20.xslt
- deegree-core/deegree-core-coverage/pom.xml
- deegree-core/deegree-core-protocol/deegree-protocol-wms/pom.xml
- deegree-services/deegree-services-wms/pom.xml
- deegree-services/deegree-services-wms/src/test/resources/org/deegree/services/wms/controller/capabilities/serialize/capabilities2html.xsl
- deegree-services/deegree-services-wms/src/test/resources/org/deegree/services/wms/controller/exceptions/exceptions2html.xsl
- deegree-tools/deegree-tools-base/pom.xml
- deegree-tools/deegree-tools-migration/src/main/java/org/deegree/tools/migration/ThemeExtractor.java
- deegree-tools/deegree-tools-migration/src/main/java/org/deegree/tools/migration/WMSMigrator.java
- pom.xml
This PR adds the support of XSLT 2.0 for the transformation to HTML of GetFeatureInfo responses as well as GetCapabilities and Exceptions.
Furthermore, the xalan dependency was removed and xerces updated.
> Added support of XSLT 2.0

- pom.xml
Fixes #1033 Downgrade to JTS 1.15.0 to resolve the failing integration testsWMSSimilarityIntegrationTest.testSimilarity
> Downgrade to JTS 1.15.0 to resolve the failing integration tests

- deegree-core/deegree-core-base/src/test/java/org/deegree/geometry/validation/GeometryValidatorTest.java
- deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/validation/event/AbstractGeometryValidationEvent.java
- deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/validation/event/ExteriorRingOrientation.java
- deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/validation/event/InteriorRingOrientation.java
Added fix for https://github.com/deegree/deegree3/issues/886 methods `hasLeftHandedSrs`, `isInterior` and `isExterior` in InteriorRingOriention and ExteriorRingOrientation respectively. The solution implemented checks the orientation of the axis for the declared Polygon patch to decide the left-handness, and uses this to check if the ring is exterior or interior.
> Fixes issue #886

- pom.xml
Reverts deegree/deegree3#1050
Fixes following test errors when building with `mvn clean install -Pintegration-tests,oracle,mssql,handbook`:
```
[ERROR] Errors: 
[ERROR]   WCSCite100IntegrationTest.getResultSnippets:58 NullPointer
[ERROR]   WFSCite110IntegrationTest.getResultSnippets:60 NullPointer
[ERROR]   WMSCite130IntegrationTest.getResultSnippets:58 NullPointer
[ERROR]   WMSCite130NewIntegrationTest.getResultSnippets:58 NullPointer
[INFO] 
[ERROR] Tests run: 600, Failures: 0, Errors: 4, Skipped: 0
```
> Revert "Change surefire settings"

- deegree-core/deegree-core-protocol/deegree-protocol-wms/src/main/java/org/deegree/protocol/wms/ops/GetFeatureInfo.java
GFI does not return the correct result if the axis order of the CRS is inverted.
For example, this is the case if WMS 1.3 is requested with CRS EPSG:4326.
Currently, when an axis aware CRS with inverted axis order is used (e.g. WMS 1.3 with CRS EPSG:4326), the axis order is inverted again without recalculating I, J, width and height.
Thus, this pull requests enables recalculation of I, J, width and height when using axis aware CRS with inverted axis order in GFI requests.
> Fix GFI for requests with CRS with inverted axis order

- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/schema/GMLAppSchemaWriter.java
- deegree-core/deegree-core-base/src/test/java/org/deegree/gml/schema/GMLAppSchemaWriterTest.java
- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/xml/schema/SchemaUtils.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/gml/request/GmlDescribeFeatureTypeHandler.java
If only one schema is configured in a FeatureStore, the schema is referenced in the local file system and DisableDynamicSchema is set to true, a DescribeFeatureType request returns the original XML schema instead of including the schema in a deegree generated schema via include.
Closes #1044.
> Export original XML schema if exactly one local schema is configured

- deegree-core/deegree-core-rendering-2d/src/test/java/org/deegree/rendering/r2d/AbstractSimilarityTest.java
- deegree-core/deegree-core-rendering-2d/src/test/java/org/deegree/rendering/r2d/Java2DRendererTest.java
- deegree-tests/deegree-wms-similarity-tests/src/test/java/org/deegree/services/wms/WMSSimilarityIntegrationTest.java
This Pull-Request disables the Test org.deegree.rendering.r2d.Java2DRendererTest.testTextStyling2() as it is unreliable on the server.
It also improves the log messages regarding the usage of base64 output, as many older versions / implementations of base64 cannot handle line breaks correctly.
See https://stackoverflow.com/questions/15490728/decode-base64-invalid-input
> Enhance Image Similarity Test

- README.md
This PR fixes the build status image and link to Jenkins at https://buildserver.deegree.org, changes all links to https plus fixing minor typos in README.md
> #1079 fixes build status image and link

- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/commons/AbstractGMLObjectReader.java
- deegree-core/deegree-core-base/src/test/java/org/deegree/gml/schema/GMLAppSchemaReaderTest.java
- deegree-core/deegree-core-protocol/deegree-protocol-wfs/src/test/java/org/deegree/protocol/wfs/describefeaturetype/xml/DescribeFeatureTypeXMLAdapterTest.java
- deegree-core/deegree-core-protocol/deegree-protocol-wfs/src/test/resources/org/deegree/protocol/wfs/describefeaturetype/xml/wfs200/DescribeFeatureType_Example01_Request.xml
- deegree-core/deegree-core-protocol/deegree-protocol-wfs/src/test/resources/org/deegree/protocol/wfs/describefeaturetype/xml/wfs200/DescribeFeatureType_Example02_Request.xml
- pom.xml
Replaces #974. Updated deegree-ogcschemas to http://repo.deegree.org/content/repositories/releases/org/deegree/deegree-ogcschemas/20191108/ and fixed test failure.
> Make gml:id attribute optional as defined in updated GML 3.2.1 schemas

- deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/cache/RasterCache.java
- deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/io/imageio/IIORasterDataReader.java
- deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/io/imageio/IIORasterReader.java
- deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/io/jai/JAIRasterReader.java
- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/legends/LegendBuilder.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/GetLegendHandler.java
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/coveragestores.adoc
This PR contains both a correction of the cache handling and a method to better control the raster cache for file base raster.
Previously there was the problem that the naming of cache files was derived from the raster data.
This could lead to unwanted errors in two situations.  
First it can happen that raster files in different directories have identical names (For example ../data/dop/overview.tif and ../data/infrared/overview.tif).  
Secodn the cache files were not distinguished between the different levels, which e.g. a geotiff can contain, and the same cache file was rewritten on every access.
> Fix cache handling of raster files

- deegree-services/deegree-webservices-handbook/pom.xml
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/basics.adoc
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/featurestores.adoc
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/filterencoding.adoc
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/renderstyles.adoc
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
- pom.xml
PR contains fixes for handbook
> Fixes some layout and formatting issue in handbook

- deegree-services/deegree-webservices/src/main/webapp/WEB-INF/faces-config.xml
- deegree-services/deegree-webservices/src/main/webapp/WEB-INF/web.xml
- deegree-services/deegree-webservices/src/main/webapp/index.xhtml
- deegree-services/deegree-webservices/src/main/webapp/layout.xhtml
- deegree-services/deegree-webservices/src/main/webapp/menu.xhtml
This PR fixes a bug in deegree's web console that a session timeout produces a stack trace. Now the browser navigates back to the main page after session timeout instead of showing a stack trace.
It also fixes also a broken link to documentation and minor typos and wording in console main page, furthermore adds a new menu entry "home" to navigate back to entry page.
> Fixes deegree web admin console showing stack trace in case of session timeout

- deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/io/WKBWriter.java
- deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/standard/multi/DefaultMultiGeometry.java
- deegree-datastores/deegree-mdstores/deegree-mdstore-ebrim-eo/src/main/java/org/deegree/metadata/persistence/ebrim/eo/EbrimEOMDStoreTransaction.java
Fix was implemented as proposed in https://github.com/deegree/deegree3/issues/1080#issuecomment-709947758.
Fixes #1080.
> Handle empty multi geometries

- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/GMLVersion.java
- deegree-core/deegree-core-base/src/test/java/org/deegree/gml/VersionFromMimeTest.java
- deegree-core/deegree-core-featureinfo/src/main/java/org/deegree/featureinfo/serializing/FeatureInfoGmlWriter.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/TransactionHandler.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/WebFeatureService.java
Lifted out some changes of #1104 in order to merge those separately.
> Add support for GML 3.2.2

- deegree-core/deegree-core-base/src/main/java/org/deegree/filter/utils/FilterUtils.java
>  Handle GenericXMLElement in FilterUtils.getGeometryValue()

- deegree-core/deegree-core-workspace/src/main/java/org/deegree/workspace/standard/DefaultWorkspace.java
Fixes #1096 
Regression of #1058 
Collecting all resource to destroy results in an unexpected status of the resource graph and problem when resources are initialized again. Therefor the old behavior was restored.
> Fix ConcurrentModificationException

- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/xml/schema/RedirectingEntityResolver.java
- deegree-core/deegree-core-commons/src/test/java/org/deegree/commons/xml/schema/RedirectingEntityResolverTest.java
Background was discussed here: https://github.com/deegree/deegree3/issues/1064
This pull request enables correct resolving of INSPIRE schemas which are now just accessible via HTTPS.
Fixes https://github.com/deegree/deegree3/issues/1064
> Redirect INSPIRE schemas from HTTP to HTTPS

- deegree-core/deegree-core-protocol/deegree-protocol-wms/src/test/java/org/deegree/protocol/wms/client/WMSClientTest.java
Fixes test org.deegree.protocol.wms.client.WMSClientTest.testWMS111InstantiationFromUrl: 
http://buildserver.deegree.org/job/deegree-3.4-pipeline/304/testReport/org.deegree.protocol.wms.client/WMSClientTest/testWMS111InstantiationFromUrl/
https://deegree3-demo.deegree.org:80/utah-workspace/services?request=GetCapabilities&service=WMS&version=1.1.1 returns `https://deegree3-demo.deegree.org:80:80/utah-workspace/services?request=DTD` as DTD schemaLoactaion (also 80:80 as DCP URLs).
This PR changes the URL to https and removes the port number.
> Changed access of deegree3 Demo to https

- Jenkinsfile
- pom.xml
The findbugs project was dead after the project lead left. It's successor is the spotbugs project, see https://mailman.cs.umd.edu/pipermail/findbugs-discuss/2017-September/004383.html for further information.
This PR changes the plugins and this is also required for supporting Java 11.
> Migrated findbugs plugin to spotbugs plugin

- deegree-services/deegree-webservices-handbook/pom.xml
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/installation.adoc
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/intro.adoc
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/layers.adoc
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/metadatastores.adoc
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
- pom.xml
This PR contains minor improvements of deegree webservice handbook:
> Minor improvements of deegree webservice handbook

- deegree-services/deegree-webservices/src/main/java/org/deegree/console/workspace/WorkspaceBean.java
This PR contains minor improvement of deegree console to download workspace from deegree nexus repo. This PR changes to nexus v3 REST API.
This PR relates to the changes introduced during migration to new server infrastructure as documented in issue #1130.
And download url needs to be updated to changes coming with issue #1063.
> Fixes download url using nexus 3 rest api

- deegree-core/deegree-core-protocol/deegree-protocol-wms/src/main/java/org/deegree/protocol/wms/ops/GetMap.java
- deegree-core/deegree-core-protocol/deegree-protocol-wms/src/test/java/org/deegree/protocol/wms/ops/GetMapTest.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/WMSController.java
Fixes #1184.
For details, please see the referenced issue.
> Add check of transparent parameter

- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/gml/request/AbstractGmlRequestHandler.java
This pull request implements that the correct GML version is used as described in  #1126.
Fixes #1126.
> SchemaLocation points to GML 3.2.2 when GML 3.2.1 is requested

- deegree-tests/deegree-wms-similarity-tests/src/test/resources/log4j.properties
- deegree-tests/deegree-wmts-tests/src/test/resources/log4j.properties
Currently the build console log is cluttered with Apache HttpClient debug information such as the HTTP traffic. 
This has no use for fault analysis on the CI system, thus it should be turned off. 
This PR provides the log4j config files to turn off Apache HttpClient logging on `wire`.
Example of the output:
```
[19:00:42] DEBUG: [DefaultHttpClient] Connection can be kept alive for 60000 MILLISECONDS
[19:00:42] DEBUG: [wire]  << "1458[\r][\n]"
[19:00:42] DEBUG: [wire]  << "[0x89]PNG[\r][\n]"
[19:00:42] DEBUG: [wire]  << "[0x1a][\n]"
[19:00:42] DEBUG: [wire]  << "[0x0][0x0][0x0][\r]IHDR[0x0][0x0][0x1][0xd2][0x0][0x0][0x1]\[0x8][0x6][0x0][0x0][0x0]|[0xda]?[0x9e][0x0][0x0][0x14][0x1f]IDATx[0xda][0xed][0xdd][0x8b][0x8e]#7[0xae][0x0]P}z[0xfe][0xdc][0xbb][0xc1]bf[0xa7][0xa7][0x1f][0xae]*[0xbd]H[0 …
```
> Added log4j configuration files for WMS and WMTS integration tests 

- pom.xml
This PR upgrades the dependencies Jersey to 1.19.4 (from 1.17.1) and commons-fileupload to 1.4 (from 1.3.3).
> Upgrade Jersey to 1.19.4 and commons-fileupload to 1.4

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/xpath/MappedXPath.java
Test `non Specific BBOX` of OGC CITE TEAM Engine (https://cite.opengeospatial.org/teamengine/) is failing otherwise.
> Improved handling of strict parameter only if geometry parameter is passed

- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/WMSController.java
Description of bug: https://github.com/deegree/deegree3/issues/1235
Fixes https://github.com/deegree/deegree3/issues/1235.
> WMS 1.3: Throw correct exception type when requesting erroneous version in GetMap request

- pom.xml
see https://logging.apache.org/log4j/2.x/security.html#CVE-2021-44832
> Bump log4j2 to v2.17.1 to resolve CVE-2021-44832

- deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
The example in the handbook contains a complex example of the deegreWFS configuration with is not schema valid (http://schemas.deegree.org/services/wfs/3.4.0/wfs_configuration.xsd).
This PR fixes the position of the element `SupportedRequests` in the example of the configuration.
> Fixed position of SupportedRequests in deegreeWFS configuration

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/pom.xml
- deegree-tools/deegree-tools-gml/pom.xml
Fixes #1268.
Module deegree-sqldialect-oracle is not behind a profile anymore as the dependencies are available publicly.
Problem documented in #1268 was solved by removing the profile containing artifact deegree-sqldialect-oracle and adding the artifact to the dependency list.
Also, the oracle profile in module deegree-featurestore-sql was removed.
> Remove oracle profile from deegree-tools-gml and deegree-featurestore-sql

- deegree-services/deegree-services-commons/src/main/java/org/deegree/services/controller/utils/HttpResponseBuffer.java
When response buffering is enabled in WFS and a client has requested data by sending a WFS GetFeature request and then the request is closed on the client side, the temporarily created file  `storeXXX.tmp` in the systems tmp directory are not removed. 
This pull requests ensures that these files are deleted in case of sitituations when the request is aborted.
> Ensure that tmp files are deleted with enabled buffering in WFS and when a request is closed

- deegree-datastores/deegree-featurestores/deegree-featurestore-commons/src/main/java/org/deegree/feature/persistence/lock/DefaultLockManager.java
- pom.xml
The current code does not detect, that H2 now includes an `INFORMATION_SCHEMA` which also included an internal `LOCKS` table.
This PR is a replacement for https://github.com/deegree/deegree3/pull/1270
References:
* http://h2database.com/html/migration-to-v2.html#information_schema
* http://h2database.com/html/systemtables.html#information_schema_locks
> Bump h2 from 1.3.171 to 2.1.210 and fix issue in creation of table LOCKS

- deegree-core/deegree-core-layer/src/main/java/org/deegree/layer/LayerQuery.java
- deegree-core/deegree-core-layer/src/test/java/org/deegree/layer/LayerQueryTest.java
- deegree-layers/deegree-layers-feature/pom.xml
- deegree-layers/deegree-layers-feature/src/main/java/org/deegree/layer/persistence/feature/FeatureLayer.java
- deegree-layers/deegree-layers-feature/src/main/java/org/deegree/layer/persistence/feature/FilterBuilder.java
- deegree-layers/deegree-layers-feature/src/test/java/org/deegree/layer/persistence/feature/FilterBuilderTest.java
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
This PR adds the two vendor specific parameters FILTERPROPERTY and FILTERVALUE to the deegree WMS. The parameters allows the client to filter the underlying datasource of the requested layers.
FILTERPROPERTY contains the name of the property to filter for. It is no qualified, so only the local name is considered. FILTERVALUE contains a list of values to filter for, multiple values must be comma separated. All features with the property matching one of the value are rendered.
It the layer does not base on feature datasource or does not provide a property with the given name, the filter is ignored. Same if one of the parameter is missing or the value empty.
> Enhanced WMS GetMap request by the vendor specific parameters FILTERPROPERTY and FILTERVALUE to filter the underlying data source

- deegree-core/deegree-core-protocol/deegree-protocol-commons/src/main/java/org/deegree/protocol/wps/client/process/ProcessDetails.java
A WPS LiteralInput doesn't have to have a DataType specified, it's optional (see WPS 1.0.0 standard, Table 25, page 26). Until now, the deegree WPS client just assumes that the DataType is always specified, causing an exception if that's not the case.
This change fixes the bug.
> Fixing wps client bug: LiteralInputs don't have to have a DataType specified

- deegree-datastores/deegree-featurestores/deegree-featurestore-shape/src/main/java/org/deegree/feature/persistence/shape/DbfIndexImporter.java
This PR includes a fix of the error "Table "DBF_INDEX" already exists" appearing when you change the workspace to i.e. the "deegree-workspace-utah". Origin of this error was an old database filename.
Changes were done and committed by @lgoltz.
Fixes #1297
> Fixed Error "Table "DBF_INDEX" already exists"

- deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/linearization/CurveLinearizer.java
- deegree-core/deegree-core-geometry/src/test/java/org/deegree/geometry/linearization/CurveLinearizerTest.java
This pull request ensure that at least three control points are created when curve linearization is executed.
Otherwise, problems can occur when linearizing an inner and outer ring.
With the current implementation it is possible that the the inner ring cuts the outer ring after linearization.
This pull request shall prevent such cases.
> Improve curve linearization

- deegree-core/deegree-core-base/src/main/java/org/deegree/feature/Features.java
- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/reference/GmlDocumentIdContext.java
Use SLF4J style logging placeholders and allow to disable warnings for "urn:" references.
Both optimizations improve the speed of batch import operations.
> Optimize logging for feature references to speed up batch import jobs

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStore.java
Simple change to reduce the amount of logging if an excessive amount of custom converter are used (for ex. in large import jobs).
Also use SLF4J parameter style for easier filtering, as the static log message with placeholder are easier filtered.
> Optimize logging of SQLFeaturestore in initialization phase

- pom.xml
This PR upgrades Apache log4j2 to v2.17.2 and slf4j to latest bugfix version v1.7.36
> Upgrades log4j2 to v2.17.2 and slf4j to 1.7.36

- pom.xml
This PR removes a duplicate dependency to Java Commons Logging (JCL) detected by maven enforcer ban duplicates classes plugin
> Remove duplicate JCL dependency

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/AppSchemaMapper.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/GmlReferenceData.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/ReferenceData.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/java/org/deegree/feature/persistence/sql/mapper/AppSchemaMapperTest.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/java/org/deegree/feature/persistence/sql/mapper/GmlReferenceDataTest.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/resources/org/deegree/feature/persistence/sql/mapper/schemaWithNilValues.xsd
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/cli-utility.adoc
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/config/FeatureStoreConfigWriter.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/config/LoadParameter.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/config/LoadParameterBuilder.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/config/SqlFeatureStoreConfigCreatorConfiguration.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/config/SqlFeatureStoreConfigCreatorUsagePrinter.java
This pull requests adds the option useRefDataProps to the SqlFeatureStoreConfigCreator of the GmlTool to reduce the mapping dependent of the referenceData:
* Mapping of optional properties not in the referenceData are omitted.
* Mapping of properties with xsi:nil="true" in the referenceData is reduced to the mapping of @xsi:nil and @nilReason.
> Enhance GmlTool to reduce generated mapping

- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/utils/Tunable.java
- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/utils/TunableParameter.java
- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/Java2DStrokeRenderer.java
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/appendix.adoc
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/index.adoc
Replacement of PR #1192
Original description:
This PR makes `miterLimit` configurable.
When the configured factor is exceeded portrayal changes from JOIN_MITER to JOIN_BEVEL (see https://docs.oracle.com/javase/tutorial/2d/geometry/strokeandfill.html).
Configuration can be set via JNDI-Env or System-Property.
Example:
```
<Environment name="deegree.rendering.stroke.miterlimit" value="2.66" 
type="java.lang.Float" override="false" 
description="deegree Rendering - Miter Limit Factor"/>
```
or
```
-Ddeegree.rendering.stroke.miterlimit=2.66
```
> Fix rendering of geometries in deegree

- deegree-core/deegree-connectionprovider-datasource/src/main/java/org/deegree/db/datasource/DataSourceConnectionProviderBuilder.java
- deegree-core/deegree-connectionprovider-datasource/src/main/resources/META-INF/schemas/connectionprovider/datasource/3.4.0/datasource.xsd
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/serverconnections.adoc
This enhancement allows to either override the automatic SQL dialect provider selection, for customized dialects, or to specify the correct dialect if deegree cannot determine the correct provider based on the JDBC URL.
> Allow to specify custom dialect provider on a data source level

- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/gml/GmlFormat.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/gml/GmlFormatOptions.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/gml/request/GmlDescribeFeatureTypeHandler.java
- deegree-services/deegree-services-wfs/src/main/resources/META-INF/schemas/services/wfs/3.4.0/wfs_configuration.xsd
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
This enhancement makes it possible to configure multiple schema locations to support static schemas for multiple GML versions in DescribeFeatureType responses of a single WFS.
For example, if DescribeFeatureType responses of a single WFS shall support non generated schemas for multiple GML versions, the newly introduced configuration option solves that use case.
Please also see #892 for further details.
Caution, this pull request also includes #1001. Thus, #1001 should be merged first.
Fixes #892.
> Enable configuration of multiple schema locations

- deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/cache/RasterCache.java
- deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/io/imageio/IIORasterDataReader.java
- deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/io/imageio/IIORasterReader.java
- deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/io/jai/JAIRasterReader.java
- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/legends/LegendBuilder.java
- deegree-layers/deegree-layers-coverage/src/main/java/org/deegree/layer/persistence/coverage/CoverageFeatureInfoHandler.java
- deegree-layers/deegree-layers-coverage/src/main/java/org/deegree/layer/persistence/coverage/CoverageFeatureInfoMode.java
- deegree-layers/deegree-layers-coverage/src/main/java/org/deegree/layer/persistence/coverage/CoverageLayer.java
- deegree-layers/deegree-layers-coverage/src/main/java/org/deegree/layer/persistence/coverage/CoverageLayerData.java
- deegree-layers/deegree-layers-coverage/src/main/java/org/deegree/layer/persistence/coverage/ManualCoverageLayerBuilder.java
- deegree-layers/deegree-layers-coverage/src/main/resources/META-INF/schemas/layers/coverage/3.4.0/coverage.xsd
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/GetLegendHandler.java
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/coveragestores.adoc
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/layers.adoc
This PR contains the changes from PR #1084.
Included is a configuration option to select whether a GetFeatureInfo can be configured on raster data.  
You can choose between an interpolation from a region (standard, as before) or alternatively a determination based on the grid value at the click position.
> Enhance GetFeatureInfo on raster

- uncoupled/deegree-jaxb-resolver/pom.xml
- uncoupled/deegree-jaxb-resolver/src/main/java/org/deegree/uncoupled/jaxb/CatalogResolver.java
- uncoupled/deegree-jaxb-util/pom.xml
- uncoupled/deegree-jaxb-util/src/main/java/org/deegree/uncoupled/jaxbutil/AbstractScanner.java
- uncoupled/deegree-jaxb-util/src/main/java/org/deegree/uncoupled/jaxbutil/MetaInfSchemasMigration.java
- uncoupled/deegree-jaxb-util/src/main/java/org/deegree/uncoupled/jaxbutil/UpdateSchema.java
This PR updates the catalog resolver to to implement the new xml schema version strategy https://github.com/deegree/deegree3/issues/953
It also provides utilities to update every schema reference in the source tree based on text replacements.
The branch https://github.com/deegree/deegree3/compare/master...gritGmbH:demo/new-schema-results shows what would have been changed when the migration utilities ran.
> Update schema handling and prepare migration

- deegree-core/deegree-connectionprovider-datasource/src/main/java/org/deegree/db/datasource/DataSourceConnectionProvider.java
- deegree-core/deegree-connectionprovider-datasource/src/main/resources/META-INF/schemas/connectionprovider/datasource/example_dbcp_mssql.xml
- deegree-core/deegree-connectionprovider-datasource/src/main/resources/META-INF/schemas/connectionprovider/datasource/example_dbcp_oracle.xml
- deegree-core/deegree-connectionprovider-datasource/src/main/resources/META-INF/schemas/connectionprovider/datasource/example_dbcp_postgres.xml
- deegree-core/deegree-core-commons/pom.xml
- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/jdbc/ConnectionPool.java
- deegree-core/deegree-core-db/src/main/java/org/deegree/db/legacy/LegacyConnectionProvider.java
- deegree-datastores/deegree-tilestores/deegree-tilestore-geotiff/src/main/java/org/deegree/tile/persistence/geotiff/GeoTIFFTile.java
- deegree-datastores/deegree-tilestores/deegree-tilestore-geotiff/src/main/java/org/deegree/tile/persistence/geotiff/GeoTIFFTileDataLevel.java
- deegree-datastores/deegree-tilestores/deegree-tilestore-geotiff/src/main/java/org/deegree/tile/persistence/geotiff/ImageReaderFactory.java
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/serverconnections.adoc
- pom.xml
This is the rebased version of PR #1022 
Original text:
Apache Commons DBCP and Commons Pool dependencies were upgraded to version 2.7.0.
Reason: Currently used version is outdated and not maintained by the community any more.
Also, the documentation was updated and improved in some points (e.g. for destroyMethod).
Closes https://github.com/deegree/deegree3/issues/1017.
> Upgrade to Apache Commons DBCP 2 (and Commons Pool 2)

- deegree-services/deegree-webservices-handbook/src/main/asciidoc/gdal.adoc
- pom.xml
This pull requests updates GDAL dependency to v3.0.0.
Solves #1103.
> Update GDAL dependency to v3.0.0

- pom.xml
fixes #1105 using trimmed OGC schemas zip file (PR for 3.5)
> Use trimmed OGC schemas zip file (reducing size by approx. 32 MB)

- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/context/MapOptions.java
This pull request fixes the default values of maxFeatures and featureInfoRadius.
Previously, when requesting a WFS without maxFeatures, no features were returned as 0 was set for this parameter.
This PR fixes that by setting -1 default values.
> Fix default values of maxFeatures and featureInfoRadius

- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/tom/Reference.java
- deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/primitive/Point.java
- deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/refs/PointReference.java
- deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/standard/points/JTSPoints.java
- deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/standard/points/PointsList.java
- deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/standard/primitive/DefaultPoint.java
Interface org.deegree.geometry.primitive.Point was enhanced by copy() method.
Afterwards, PointReference and DefaultPoint were enhanced by implementations of this new method.
Finally, PointsList#copy() could be implemented.
JTSPoints#copy() was also implemented.
> Implement PointsList#copy() and JTSPoints#copy()

- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/commons/AbstractGMLObjectReader.java
This pull request enhances the AbstractGMLObjectReader to ignore attribute xsi:type as it is not suppored by deegree, yet.
In addition, a warning is logged.
> Ignore attribute xsi:type and log warning

- deegree-core/deegree-core-protocol/deegree-protocol-wfs/src/main/java/org/deegree/protocol/wfs/storedquery/xml/StoredQueryDefinition200Encoder.java
- deegree-core/deegree-core-protocol/deegree-protocol-wfs/src/test/java/org/deegree/protocol/wfs/storedquery/xml/StoredQueryDefinition200EncoderTest.java
Without this pull request deegree generates content like the following when no namespace is used:
```
returnFeatureTypes=":${deegreewfs:ServedFeatureTypes}" 
```
There is an `:` in the response which should not be there.
This pull request fixes that behavior (as confirmed by the unit test).
> Fix export of returnFeatureTypes without namespace in StoredQueryDefinitionEncoder

- deegree-services/deegree-services-commons/pom.xml
- deegree-services/deegree-services-commons/src/api/java/org/deegree/services/controller/OGCFrontController.java
- deegree-services/deegree-services-commons/src/test/java/org/deegree/services/controller/exception/serializer/SOAPExceptionSerializerTest.java
- pom.xml
This PR upgrades axiom from 1.2.15 to 1.2.22 and fixes wrong use of axoim's internal API.
The usage of the SOAPFactory implementations default constructors was not correct and the non-arg default constructors have been removed, "Note that they were not part of the public API, but considered internal implementation details. Application code should always use the OMAbstractFactory APIs to get references to factory instances, and never refer to implementation classes directly." (see https://ws.apache.org/axiom/release-notes/1.2.16.html)
> Upgrades axiom from 1.2.15 to 1.2.22 

- pom.xml
Upgrades Mockito from 2.28.2 to 3.12.4 and adds "add-open for java.base" modules to surefire maven plugin (supports compile with JDK 17+)
> Bump Mockito from 2.28.2 to 3.12.4

- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/schema/GMLAppSchemaWriter.java
* e.g. gml:TemporalPeriodPropertyType is parsed by the Schema analysis
to an ObjectPropertyType - which was previously unsupported in the
GMLAppSchemaWriter, resulting in an "Unhandled property type" runtime
exception.
* This PR adds support for the ObjectPropertyType through the same
generic mechanism as used for the CustomPropertyType, i.e. exporting
the underlying XSComplexTypeDefinition, and therefore also includes
minimal code refactoring to avoid duplication of code previously only
used by the CustomPropertyType export.
> Add support for ObjectPropertyType in GMLAppSchema

- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/feature/GMLFeatureWriter.java
- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/xml/stax/StAXExportingHelper.java
In case of CustomPropertyTypes with attributes it could happen that an
attribute was written w/o a respective namespace declaration being
present.
refs #600
> fix: don't write attributes w/ unbound namespace prefix

- deegree-core/deegree-core-protocol/deegree-protocol-wms/src/main/java/org/deegree/protocol/wms/ops/GetFeatureInfo.java
- deegree-core/deegree-core-protocol/deegree-protocol-wms/src/main/java/org/deegree/protocol/wms/ops/GetMap.java
- deegree-core/deegree-core-protocol/deegree-protocol-wms/src/main/java/org/deegree/protocol/wms/ops/RequestBase.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/MapService.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/WMSController.java
- deegree-tests/deegree-wms-similarity-tests/src/test/java/org/deegree/services/wms/GetFeatureInfoIntegrationTest.java
This PR enables that GetFeatureInfo does not ignore configured PIXELSIZE and DPI.
In addition, integration tests were added.
> Fix GetFeatureInfo with non standard PIXELSIZE/DPI

- deegree-core/deegree-core-style/pom.xml
Fixes #1383 by adding batik-codec as described in https://bz.apache.org/bugzilla/show_bug.cgi?id=44682
> Fix rendering of symbolizer with external SVG graphics

- deegree-core/deegree-core-gdal/src/main/java/org/deegree/commons/gdal/GdalDataset.java
The current implementation uses a static value of -1, which is assumed to be white (as the function was named).
Furthermore, only bands 0-2 are overwritten with data, which I did not changed.
Before a customer had isses with small rasters images which showed black rectangles on the bottom and/or side of the image.
After applying the change the rectangles were gone and either transparency or background color was rendered.
* PR for 3.4 is #1382 
* GDAL Java API
*  https://gdal.org/java/org/gdal/gdal/Band.html#GetNoDataValue(java.lang.Double%5B%5D)
* GDAL C++ API
*  https://gdal.org/api/gdalrasterband_cpp.html#_CPPv4N14GDALRasterBand14GetNoDataValueEPi
> Fix background color issues with no-data sections in gdal tiles [3.5]

- deegree-core/deegree-core-gdal/src/main/java/org/deegree/commons/gdal/GdalDataset.java
The current implementation uses a static value of -1, which is assumed to be white (as the function was named).
Furthermore, only bands 0-2 are overwritten with data, which I did not changed.
Before a customer had isses with small rasters images which showed black rectangles on the bottom and/or side of the image.
After applying the change the rectangles were gone and either transparency or background color was rendered.
* PR for 3.5 is #1381 
* GDAL Java API
*  https://gdal.org/java/org/gdal/gdal/Band.html#GetNoDataValue(java.lang.Double%5B%5D)
* GDAL C++ API
*  https://gdal.org/api/gdalrasterband_cpp.html#_CPPv4N14GDALRasterBand14GetNoDataValueEPi
> Fix background color issues with no-data sections in gdal tiles [3.4]

- deegree-core/deegree-core-featureinfo/src/main/java/org/deegree/featureinfo/templating/lang/Link.java
With this pull request it is possible to use the GetFeatureInfo templating mechanism to display a xlink:href attribute as link in GFI response.
> Enhance GFI templating mechanism to convert xlink:href attribute to link

- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/utils/TunableParameter.java
- deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/cache/RasterCache.java
- deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/io/imageio/IIORasterDataReader.java
- deegree-core/deegree-core-coverage/src/test/java/org/deegree/coverage/raster/cache/TestRasterCache.java
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/appendix.adoc
This PR changed the code so that for all `deegree.*` parameters `TunableParameter` is used.
Also, documentation of previously not mentioned parameters has been added.
> Unification of tunable parameter usage and their documentation

- deegree-services/deegree-webservices-handbook/src/main/asciidoc/cli-utility.adoc
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/GmlLoaderConfiguration.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/GmlLoaderHelpUsage.java
This PR includes the option to do a dry-run without writing to the SQLFeaturestore and allows configuring the chunk size.
In addition, it is now possible to add a file which includes a list of files to be processed, which speeds up loading multiple files.
> Extend command line options for the loader tool

- pom.xml
Cherry-picked dependabot PRs we also want to merge into 3.4.
fixes #1370
> Dependency updates for deegree 3.4 (backport from 3.5)

- deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/io/WKTWriter.java
- deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/linearization/CurveLinearizer.java
- deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/standard/multi/DefaultMultiCurve.java
- deegree-core/deegree-core-geometry/src/test/java/org/deegree/geometry/io/WKTWriterSqlMMTests.java
This PR is a, reworked, part of the larger PR #1204
This changes optimize the serialization for common geometry types in SQL/MM (like CURVEPOLYGON, CIRCULARSTRING, etc.).
It also extends the linearization code to allow SQL/MM like circles which are defined through the points of the diameter.
This change extends the current code which implements the GML 3.x way of circles, which would be incompatible, to also allow circles like in SQL/MM.
Quote from the GML 3.2 specification
> A Circle is an arc whose ends coincide to form a simple closed loop. The three control points shall be distinct non-co-linear points for the circle to be unambiguously defined. The arc is simply extended past the third control point until the first control point is encountered.
Quote from the PostGIS documentation …
> Extend the serialization of SQL/MM (curved) geometries to WKT 

- deegree-core/deegree-core-sqldialect/deegree-sqldialect-oracle/src/main/java/org/deegree/sqldialect/oracle/OracleGeometryConverter.java
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-oracle/src/main/java/org/deegree/sqldialect/oracle/sdo/OracleObjectTools.java
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-oracle/src/main/java/org/deegree/sqldialect/oracle/sdo/SDOGeometry.java
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-oracle/src/main/java/org/deegree/sqldialect/oracle/sdo/SDOGeometryConverter.java
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-oracle/src/main/java/org/deegree/sqldialect/oracle/sdo/SDOInspector.java
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-oracle/src/test/java/org/deegree/sqldialect/oracle/sdo/SDOGeometryConverterExampleTests.java
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-oracle/src/test/java/org/deegree/sqldialect/oracle/sdo/SDOGeometryConverterTest.java
This Pull Request contains a new interface `org.deegree.sqldialect.oracle.sdo.SDOInspector` that can be used to interfere before a geometry is written to or after the geometry has been read from the database.
With this `org.deegree.sqldialect.oracle.sdo.SDOInspector`, which works similar as `org.deegree.feature.persistence.FeatureInspector`, it is possible to handle custom geometries and or specialized simplification with an extended dialect.
This PR is logically related to PR #1285
> Add an extension to the oracle dialect that works analog to the FeatureInspector

- deegree-services/deegree-webservices-handbook/src/main/asciidoc/serverconnections.adoc
- pom.xml
This PR updates the Oracle dependencies to version 19.9.0.0.
It also removes the duplicate/different dependency, which had previously be manually excluded from the enforcer plugin with `<ignoreClass>oracle.xml.*</ignoreClass>`.
See also Issue #1430
> Update Oracle driver to 19.9.0.0

- deegree-core/deegree-core-layer/src/main/java/org/deegree/layer/config/ConfigUtils.java
- deegree-core/deegree-core-layer/src/main/resources/META-INF/schemas/layers/base/base.xsd
- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/context/MapOptions.java
- deegree-layers/deegree-layers-coverage/src/main/java/org/deegree/layer/persistence/coverage/CoverageFeatureInfoHandler.java
- deegree-layers/deegree-layers-coverage/src/main/java/org/deegree/layer/persistence/coverage/CoverageLayer.java
- deegree-layers/deegree-layers-coverage/src/main/java/org/deegree/layer/persistence/coverage/CoverageLayerData.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/theme/LayerMetadataMerger.java
- deegree-services/deegree-services-wms/src/test/java/org/deegree/services/wms/controller/capabilities/theme/LayerMetadataMergerTest.java
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/layers.adoc
This PR extends the GetFeatureInfo configuration and adds the new attribute `decimalPlaces`.
The intended use-case is to request a fixed number of decimal digits on numerical data extracted from coverage data.
On coverage (raster) data, feature info gets sampled or aggregated, so that it is not unusual to have many decimal digits, which can lead to a false interpretation of accuracy.
**Note on MapOptions:** During the integration of the changes into the current `main` the remaining uses of MapOptions constructors was cleaned up to use the previously introduced `MapOptions.Builder`.
> Make decimal places of numeric values in GetFeatureInfo for cover configurable

- deegree-core/deegree-core-layer/src/main/java/org/deegree/layer/config/ConfigUtils.java
- deegree-core/deegree-core-layer/src/main/resources/META-INF/schemas/layers/base/base.xsd
- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/context/MapOptions.java
- deegree-layers/deegree-layers-coverage/src/main/java/org/deegree/layer/persistence/coverage/CoverageFeatureInfoHandler.java
- deegree-layers/deegree-layers-coverage/src/main/java/org/deegree/layer/persistence/coverage/CoverageLayer.java
- deegree-layers/deegree-layers-coverage/src/main/java/org/deegree/layer/persistence/coverage/CoverageLayerData.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/theme/LayerMetadataMerger.java
- deegree-services/deegree-services-wms/src/test/java/org/deegree/services/wms/controller/capabilities/theme/LayerMetadataMergerTest.java
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/layers.adoc
This is a follow up PR to #1395 which removes constructors which are not used anymore.
Needs discussion how to handle API changes / coding pattern for upcoming release.
> Cleanup API for MapOptions

- deegree-services/deegree-services-csw/src/main/java/org/deegree/services/csw/CswExceptionReportSerializer.java
- deegree-services/deegree-services-wcs/src/main/java/org/deegree/services/wcs/WCS100ServiceExceptionReportSerializer.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/WMS111ExceptionReportSerializer.java
Currently serialized NullPointerExceptions are written with a message of `null`, which should be avoided.
> Prevent serialization of exceptions with "null" message

- pom.xml
Was previously used by deegree-featurestore-geocouch which is uncoupled/oprhanded since 2013.
https://github.com/deegree/deegree3/blob/bdb3e36c2239499ab37eabd39fd1bfde7aa7ca55/uncoupled/orphaned-after-3.2/deegree-featurestore-couchbase/pom.xml#L51-L54
> Remove jettison from dependencies

- deegree-core/deegree-core-style/src/main/java/org/deegree/style/utils/UomCalculator.java
Values given in foot where previously handled incorrectly like meter.
Now uses the conversation factor of 0.3048 meter per foot as defined at the [International Yard and Pound Agreement](https://en.wikipedia.org/wiki/International_Yard_and_Pound_Agreement) in 1959.
Source: http://en.wikipedia.org/wiki/Foot_%28unit%29
> Fix conversation of foot within unit of measure handling

- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/SvgImageTranscoder.java
- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/SvgRenderer.java
This PR was part of #1202 and the SvgImageTranscoder get reworked, as it was used there i a different way.
It replaces the the current way of transcoding (SVG -> PNG-Stream -> BufferedImage) by implementing `org.apache.batik.transcoder.image.ImageTranscoder` which gives direct access to the BufferedImage instead of  using `org.apache.batik.transcoder.image.PNGTranscoder `.
A simple performance comparison was done on my local system by executing the following class five times with 100 iterations each. 
```java
package org.deegree.rendering.r2d;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import org.deegree.style.styling.components.Graphic;
public class SvgRenderPerformanceTest {
public static void main( String[] args ) {
new SvgRenderPerformanceTest().run();
} …
```
> Speed up transcoding SVG to Image

- deegree-layers/deegree-layers-gdal/src/main/java/org/deegree/layer/persistence/gdal/GdalLayerData.java
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/appendix.adoc
This pull requests changes the default configuration for GdalLayer to not delete band four by default.
It is a replacement for #1067 and introduces a configuration option to get back the old behavior.
Detailed description of problem: #1065
Closes #1067 
Closes #1065
> Enable support for 4-band raster data with GdalLayer

- deegree-services/deegree-webservices-handbook/src/main/asciidoc/cli-utility.adoc
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/FeatureStatistics.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/FeatureStoreWriter.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/GmlLoaderConfiguration.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/GmlLoaderHelpUsage.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/ReportWriter.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/Summary.java
This PR builds on top of #1293 
A new command line option has been added to specify the report file name (can include the path)
> Make report file configurable in the loader tool

- pom.xml
PR upgrades Apache DBCP 2.7.0->2.9.0 and Commons Pool 2.7.0->2.11.1
> bump dbcp2 to 2.9.0 and commons-pool2 to 2.11.1

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/ddl/PostGISDDLCreator.java
This PR fixes a bug in SqlFeatureStoreConfigCreator (part of GmlLoader) when generating the create index statement.
> Fix table name in generated create index statement

- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/commons/AbstractGMLObjectReader.java
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/appendix.adoc
This PR introduces the new option `deegree.gml.property.simple.trim` which allows disabling of the trimming of white-space characters while reading GML simple property values.
This option was implemented, as a specific data source needed to be imported as is, without the common trimming of white spaces like newlines etc..
> Allow disabling trimming of simple property values in GML reader

- deegree-services/deegree-services-commons/src/api/java/org/deegree/services/controller/OGCFrontController.java
- deegree-services/deegree-services-commons/src/main/resources/META-INF/schemas/services/controller/controller.xsd
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
Fixes #1102.
This PR adds a new element `AddDeegreeVersionToHeader` to the service controller  configuration with default `false` which disables the HTTP header `deegree-version` send in responses.
> Enhanced configuration to hide version reference in header

- deegree-services/deegree-webservices/pom.xml
This PR updates the JSF Primefaces libraries to version 12.0
See https://www.primefaces.org/primefaces-12-0-2-released/ and change log for more information: https://github.com/primefaces/primefaces/issues?q=is%3Aissue+label%3A12.0.2+is%3Aclosed
> Upgrade JSF Primefaces to v12.0

- deegree-core/deegree-core-coverage/pom.xml
- deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/data/container/CachedRasterDataContainer.java
- deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/data/container/StatisticsRetrieval.java
- deegree-datastores/deegree-tilestores/deegree-tilestore-cache/pom.xml
- deegree-datastores/deegree-tilestores/deegree-tilestore-cache/src/main/java/org/deegree/tile/persistence/cache/CachedTile.java
- deegree-datastores/deegree-tilestores/deegree-tilestore-cache/src/main/java/org/deegree/tile/persistence/cache/CachingTileMatrix.java
- deegree-datastores/deegree-tilestores/deegree-tilestore-cache/src/main/java/org/deegree/tile/persistence/cache/CachingTileStore.java
- deegree-datastores/deegree-tilestores/deegree-tilestore-cache/src/main/java/org/deegree/tile/persistence/cache/CachingTileStoreBuilder.java
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
- deegree-tests/deegree-wmts-tests/src/main/webapp/WEB-INF/workspace/ehcache.xml
- deegree-tests/deegree-wmts-tests/src/main/webapp/WEB-INF/workspace/ehcache_remotewms.xml
- pom.xml
Fixes #1157.
ehcache was updated to the recent version (3.10.8). Important note: The schema of ehcache's XML configuration files has changed!
> Upgrade ehcache to version 3.10.8

- deegree-services/deegree-webservices/pom.xml
This PR removes unused and outdated profiles, adapts existing profile for oracle to use same dependencies as root pom, and adds a profile for mssql to add the  sqldialect JAR  to WAR file if enabled.
For Oracle and MS SQL Server the JDBC drivers are NOT added to the WEB-INF/lib directory on purpose. Please note the explanations in https://download.deegree.org/documentation/current/html/#anchor-configuration-javamodules. The documentation may contain the following explanation:
The considerations to put JDBC driver JAR files into $CATALINA_HOME/lib directory are that JDBC drivers register themselves in the JVM-wide singleton [DriverManager](https://docs.oracle.com/en/java/javase/11/docs/api/java.sql/java/sql/DriverManager.html) which is shared by all web apps inside of a Tomcat/JVM …
> Reworked profiles section for building deegree-webservices WAR file

- deegree-services/deegree-webservices-handbook/src/main/asciidoc/cli-utility.adoc
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/GmlLoaderConfiguration.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/GmlLoaderHelpUsage.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/TransactionHandler.java
With this change, the object ID and references are not stored in the ExecutionContext and the check is skipped.
Additionally, the list of files, if used, is checked before starting the loading operation.
This extension can be used, if the integrity check can be skipped or done later, to work around issue #1451.
References:
- #1451
> Add option to skip reference check in GmlLoader tool

- deegree-tools/deegree-tools-gml/pom.xml
- pom.xml
This PR upgrades JAXB impl. to v2.3.7, removes overriding of version in deegree-tools-gml submodule
Should be merged with PR #1459.
> Upgrade of JAXB implementation to v2.3.7

- pom.xml
This PR fixes the broken JAXB dependencies introduced with PR #1441.
The deegree project uses the `jakarta.xml.bind:jakarta.xml.bind-api`(API) with `com.sun.xml.bind:jaxb-impl` (JAXB implementation).
The ehcache project uses `org.glassfish.jaxb:jaxb-runtime` in the version range of `[2.2,3)`. This brings duplications of types in different versions from the `com.sun.xml.bind` package into the classpath and results in build errors.
To fix this the `org.glassfish.jaxb:jaxb-runtime` dependencies introduced with ehcache are excluded from the dependencies. This shall not affect ehcache at runtime since the difference between `jaxb-impl` and the `jaxb-runtime` JAR is that the `jaxb-impl` JAR also bundles types from `com.sun.istack` and `com.sun.xml.txw2` whereas the `jaxb-runtime`  provides them …
> Fix for dependency conflicts introduced with ehcache 3.x upgrade (PR #1441)

- pom.xml
This PR upgrades json-path and json-path-assert to v2.7.0.
> Upgrade of json-path to 2.7.0

- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/GmlLoaderConfiguration.java
This PR disables the check of the references if `skipReferenceCheck=true` is set.
> Fixed skipReferenceCheck=true in GmlLoader

- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/GmlLoaderConfiguration.java
As changes for the gml-loader were separated for easier manageability, the PR #1390 missed an annotation, which is fixed in this PR.
closes #1465
> Fix Spring annotations for GMLLoader

- deegree-core/deegree-core-geometry/pom.xml
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-mssql/pom.xml
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-mssql/src/main/java/org/deegree/sqldialect/mssql/MSSQLDialect.java
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-mssql/src/main/java/org/deegree/sqldialect/mssql/MSSQLDialectProvider.java
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-mssql/src/main/java/org/deegree/sqldialect/mssql/MSSQLGeometryConverter.java
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-mssql/src/main/java/org/deegree/sqldialect/mssql/MSSQLWhereBuilder.java
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-mssql/src/test/java/org/deegree/sqldialect/mssql/MSSQLWhereBuilderTest.java
- pom.xml
Fixes #1322. PR includes refactoring of  classes from the commons moved to mssql dialect module, fixed usage of profiles in deegree-webservices module and upgraded jdbc driver to v10.2. for support of MS SQL Server 2019.
Todo
> Refactored deegree-dialect-mssql module and upgraded JDBC driver for SQL Server

- pom.xml
This PR upgrades the PostgreSQL JDBC driver to v42.5.2. 
Changelog: https://jdbc.postgresql.org/changelogs/2023-01-31-42.5.2-release/
> Upgrade of PostgreSQL JDBC driver to v42.5.2

- pom.xml
This PR upgrades the libraries of Spring Boot 2.5.12->2.5.14, Spring Batch 4.3.5->4.3.6 and Spring Core 5.3.18->5.3.20
> Upgrade Spring Boot to 2.5.14, Spring Batch 4.3.6 and Spring Core 5.3.20

- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/CommonConfiguration.java
- pom.xml
This PR upgrades the Spring dependencies:
- Spring Boot from 2.5.15 to 2.7.10 
- Spring Batch from 4.3.6 to 4.3.8
- Spring Core from 5.3.20 to 5.3.26
This fixes a known vulnerability [CVE-2023-20861: Spring Expression DoS Vulnerability](https://spring.io/security/cve-2023-20861)
> Upgrade of Spring dependencies

- deegree-core/deegree-core-commons/pom.xml
- pom.xml
This PR upgrades woodstox library to version 5.1.0 and resolves a duplication of classes introduced by `deegree-core-commons`:
```
[INFO] |  +- org.deegree:deegree-core-commons:jar:3.5.0-SNAPSHOT:compile
[INFO] |  |  +- org.codehaus.woodstox:woodstox-core-lgpl:jar:4.2.1:compile
[INFO] |  |  +- org.apache.ws.commons.axiom:axiom-api:jar:1.2.22:compile
[INFO] |  |  |  +- org.apache.geronimo.specs:geronimo-activation_1.1_spec:jar:1.1:compile
[INFO] |  |  |  +- org.apache.geronimo.specs:geronimo-stax-api_1.0_spec:jar:1.0.1:compile
[INFO] |  |  |  \- org.apache.james:apache-mime4j-core:jar:0.7.2:compile
```
It also resolves the CVE  reported for woodstox-core-lgpl-4.2.0.jar (pkg:maven/org.codehaus.woodstox/woodstox-core-lgpl@4.2.0, cpe:2.3:a:fasterxml:woodstox:4.2.0:*:*:*:*:*:*:*) : …
> Upgrade of woodstox to v5.1.0

- deegree-tests/deegree-integration-tests/pom.xml
- pom.xml
This PR upgrades the maven plugins used for testing:
- surefire
- failsafe
- jetty (running the webapps for integration testing)
- and the enforcer plugins which checks for duplicate classes.
> Upgraded maven surefire, failsafe, enforcer and jetty plugins to latest versions

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStore.java
> Apply count and startindex to queries without SORTBY/FILTER in blob mode

- deegree-core/deegree-core-sqldialect/deegree-sqldialect-commons/src/main/java/org/deegree/sqldialect/SortCriterion.java
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-commons/src/main/java/org/deegree/sqldialect/filter/AbstractWhereBuilder.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/config/AbstractMappedSchemaBuilder.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/config/MappedSchemaBuilderGML.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/config/MappedSchemaBuilderTable.java
When OrderBy is configured in SQLFeatureStore
```
</FIDMapping>
<OrderBy>
<Column name="a" />
</OrderBy>
```
A GetFeature request results in a failure because of an invalid SQL Statement:
`SELECT X2.a, X2.b. FROM table X2 ORDER BY X1.a ASC`
The failure is fixed by using the table alias order by is configured for instead of the root alias.
> Fix invalid SQL when OrderBy is configured in SQLFeatureStore 

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/pom.xml
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/MappingContextManager.java
- pom.xml
Replaced deegree version of junidecode build from https://github.com/deegree/junidecode build with https://buildserver.deegree.org/view/misc/job/internal/job/junidecode/ with official version from maven central https://central.sonatype.com/artifact/net.gcardone.junidecode/junidecode/0.4.1
> Replaced org:deegree:junidecode:0.2 with net.gcardone.junidecode:junidecode.0.4.1

- deegree-core/deegree-core-sqldialect/deegree-sqldialect-mssql/pom.xml
- deegree-core/deegree-core-sqldialect/pom.xml
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/pom.xml
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/javamodules.adoc
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/serverconnections.adoc
- deegree-services/deegree-webservices/pom.xml
- pom.xml
With this PR the list of supported database was updated based on the compatibility matrices of the respected database drivers.
Additionally the usage of the profiles mssql and oracle was reduced since the jdbc drivers are available at repo1.maven.org.
For easier usage of webservices war the sqldialects of mssql and oracle will now be included by default (Note: JDBC driver has still to be provided manually)
closes #1474
References:
* #1474  
* https://search.maven.org/artifact/com.microsoft.sqlserver/mssql-jdbc/10.2.2.jre11/jar
*  https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/10.2.2.jre11/mssql-jdbc-10.2.2.jre11.jar
> Update database information in documentation and include sqldialect for oracle and mssql in regular webservices

- Jenkinsfile
PR prepares a release build for 3.4.x line with maven release plugin integrated into Jenkinsfile.
> 3.4 main release pipeline

- pom.xml
This PR introduces the spring-javaformat-maven-plugin.
The plugin enables validation if code is formatted correctly (otherwise build fails) and formatting via Maven.
The formatter does not include formatting of imports.
Validation was commented out and can be activated as soon as formatting was executed.
Closes #1260
> Introduce spring-javaformat-maven-plugin

- Jenkinsfile
> Fixed build step for quality checks by using the warnings ng jenkins plugin

- pom.xml
This PR upgrades the maven surefire and failsafe plugins to latest version, fixing build error during execution of unit tests in deegree-core-base module.
> Upgrade of maven surefire and failsafe plugins to v3.1.0

- pom.xml
This PR bumps the versions of Spring Core to 5.3.27, Spring Boot to 2.5.15 and Spring Batch to 4.3.8 to resolve vulnerabilities.
> Upgrading Spring Core to 5.3.27, Spring Boot to 2.5.15 and Spring Batch to 4.3.8

- deegree-services/deegree-webservices/src/main/java/org/deegree/console/generic/XmlEditorBean.java
This PR changes the schema locations from fully qualified jar with inside location to only the location on the classpath (/META-INF/schemas/).
Fixes #1491
> Fix schema validation of console

- pom.xml
This PR excludes the `jai_core` dependency to resolve issues when building deegree and `jai_core` instead of `jai-core` is used. **Note:** within the project `jai-core` should be used as artifactID.
This issue occurs occasionally when building deegree with:  `mvn -T6 clean install` or different order when defining `-pl` option.
> Fix transitive dependency to jai_core to use jai-core instead

- Jenkinsfile
This PR enhances the pipeline to re-enable the publishing of artifacts created during install **and** release step.
Reverting the change introduced with #1513.
> Enhanced pipeline to publish artifacts on jenkins

- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/schema/GMLSchemaInfoSet.java
- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/xml/CommonNamespaces.java
> Removed SMIL 2.0 namespaces from appNamespaces to avoid wrapper schema

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStore.java
**Behavior of the deegree WFS**
When GetFeature request with BBOX filter is sent against a service using blob mode, the response returns an exception.
E.g.:
[WFS_ENDPOINT]?version=2.0.0&service=WFS&request=GetFeature&typenames=prefix:exampleTypename&BBOX=576500,5942536,576505,5942539
```
<wfs:FeatureCollection ...>
...
<ows:ExceptionReport xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd" version="2.0.0">
<ows:Exception exceptionCode="NoApplicableCode">
<ows:ExceptionText>
Error performing query by operator filter: ERROR: ST_Intersects: Operation on mixed SRID geometries (Point, 25832) != (Polygon, 0)
</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>
</wfs:FeatureCollection>
```
**Setup of deegree**
A SRID is …
> GetFeature request with BBOX filter returns error in blob mode

- deegree-tools/deegree-tools-gml/pom.xml
- pom.xml
- src/site/site.xml
This PR bumps maven build plugins such as jaxb2, compiler, dependency, release, deploy and site plugins such as pmd, owasp-dependency-check and project-info-report to most recent version.
This PR includes all changes introduced with PR #1532 for the `main-3.4` branch.
> Upgrading maven plugins to latest versions

- deegree-workspaces/pom.xml
- pom.xml
This PR upgrades maven plugins for surefire, failsafe, war, release, asciidoctor, buildnumber and others supporting maven build with Maven v3.9.4 and JDK 17+.
> Upgrade of maven plugins for surefire, failsafe, war, release to latest bugfix version

- deegree-services/deegree-webservices/pom.xml
This PR upgrades JSF PrimeFaces from version 12.0 to latest 13.0. Verified by build deegree webapp and deploying it to Tomcat 9 with JDK 11 and performed some actions on the console successfully.
Changes for 13.0.0 published here: https://github.com/primefaces/primefaces/releases
> Upgrade of Primefaces from 12.0 to 13.0

- deegree-workspaces/deegree-workspace-utah/src/main/resources/services/wms_metadata.xml
This pull request fixes the invalid configuration of WMS metadata file of the Utah demo workspace.
After this fix is applied the validate workspace funtion returns valid.
> Fix invalid WMS metadata configuration for Utah workspace

- deegree-core/deegree-core-base/src/test/java/org/deegree/geometry/gml/validation/GmlGeometryValidatorTest.java
- deegree-core/deegree-core-base/src/test/resources/org/deegree/gml/misc/geometry/invalid/LeftHanded_exterior_anticlockwise_interior_anticlockwise.gml
- deegree-core/deegree-core-base/src/test/resources/org/deegree/gml/misc/geometry/invalid/LeftHanded_exterior_anticlockwise_interior_clockwise.gml
- deegree-core/deegree-core-base/src/test/resources/org/deegree/gml/misc/geometry/invalid/LeftHanded_exterior_clockwise_interior_anticlockwise.gml
- deegree-core/deegree-core-base/src/test/resources/org/deegree/gml/misc/geometry/invalid/LeftHanded_exterior_clockwise_interior_clockwise.gml
- deegree-core/deegree-core-base/src/test/resources/org/deegree/gml/misc/geometry/invalid/RightHanded_exterior_anticlockwise_interior_anticlockwise.gml
- deegree-core/deegree-core-base/src/test/resources/org/deegree/gml/misc/geometry/invalid/RightHanded_exterior_anticlockwise_interior_clockwise.gml
- deegree-core/deegree-core-base/src/test/resources/org/deegree/gml/misc/geometry/invalid/RightHanded_exterior_clockwise_interior_anticlockwise.gml
- deegree-core/deegree-core-base/src/test/resources/org/deegree/gml/misc/geometry/invalid/RightHanded_exterior_clockwise_interior_clockwise.gml
A new test has been created in the [GMLGeometryValidatorTest.java](http://gmlgeometryvalidatortest.java/).
It tests the orientations of polygons declared with left-handed CRS and right-handed CRS.
We have added 8 different .gml files, considering all possible scenarios:
* CRS: left-handed, right-handed
* Exterior ring: clockwise, counterclockwise
* Interior ring: clockwise, counterclockwise
Included files are:
- LeftHanded_exterior_anticlockwise_interior_anticlockwise.gml
- LeftHanded_exterior_anticlockwise_interior_clockwise.gml
- LeftHanded_exterior_clockwise_interior_anticlockwise.gml
- LeftHanded_exterior_clockwise_interior_clockwise.gml
- RightHanded_exterior_anticlockwise_interior_anticlockwise.gml
- RightHanded_exterior_anticlockwise_interior_clockwise.gml
- …
> Improved tests for GMLGeometryValidator handling left- and right-handed CRS

- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/GmlLoaderConfiguration.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/NullWriter.java
Executing the GmlLoader with the parameter `-dryRun=true` results in 
```
ERROR o.s.batch.core.job.AbstractJob - Encountered fatal error executing job
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.step' defined in org.deegree.tools.featurestoresql.loader.GmlLoaderConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.batch.core.Step]: Factory method ‘step’ threw exception; nested exception is java.lang.IllegalStateException: ItemWriter must be provided 
```
This PR fixes the GmlLoader by adding a NullWriter.
> Fix dryRun in GmlLoader

- deegree-core/deegree-core-remoteows/deegree-remoteows-wmts/src/main/resources/META-INF/schemas/remoteows/wmts/example.xml
As mentioned in #1492, a new WMTS example was proposed. 
The example resource `https://service.pdok.nl/brt/achtergrondkaart/wmts/v2_0?request=GetCapabilities&service=WMTS` is now used.
Closes #1492
> Add new remote WMTS example resource

- deegree-tests/deegree-resource-deps-tests/src/test/resources/workspace/jdbc/simplesqlh2.xml
- pom.xml
This PR tries to solve the build issues with #1540 by changing the testing JDBC connection to be memory backed.
For details on the h2 version upgrade see #1540 
There is another variant of this PR #1583 available which also fixes misleading logging messages when logging is enabled.
Closes #1540 
Closes #1583 
References:
* #1540
* #1583
> Bump h2 from 2.1.210 to 2.2.220 and use memory baked instance while testing 

- Jenkinsfile
Include Parameter in Test Stage to let all tests run before failing (to get a more complete picture)
Solves #1580
Documentation: https://maven.apache.org/guides/mini/guide-multiple-modules.html#command-line-options
> Optimize current Build workflow to only Fail-at-end for tests

- deegree-services/deegree-webservices/pom.xml
This PR upgrades Primefaces to v13.0.2 used in deegree webservices webapp.
Changelog: https://github.com/primefaces/primefaces/releases
> Upgrade Primefaces to latest bugfix version 13.0.2

- deegree-core/deegree-core-cs/src/main/java/org/deegree/cs/transformations/TransformationFactory.java
- deegree-core/deegree-core-cs/src/test/java/org/deegree/cs/transformations/Epsg3857TransformationTest.java
We were experimenting a bit with transformations from EPSG:3857 that are producing wrong results, specifically to EPSG:31468 / EPSG:4314 where data would be moved by ~20 km.
Example:
Debugging the transformation we could not really pinpoint where the things go wrong.
So for now we here implemented a workaround to get correct results, by having WGS 84 as an intermediate step in the transformation.
This is definitely not pretty and an actual fix would be preferable, but I was wondering if something like this workaround would in principle be something that you would consider to be added to the codebase. Thanks!
> workaround for transformation from epsg:3857 with wrong results 

- deegree-tests/deegree-integration-tests/README.md
- deegree-tests/deegree-integration-tests/src/test/resources/deegree-acceptance-tests-soapui-project.xml
In order to test the new default configuration of the response header **not** showing the deegree version a new SoapUI integration test was written. The used request method is GET with GetFeature request on WFS 2.0.0.
> Add new integration test for the deegree version response header default configuration

- pom.xml
Without setting the encoding explicitly some unittest fail on systems that do not use UTF-8 as platform encoding.
> Enforce UTF-8 as platform encoding in unit tests

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/ddl/PostGISDDLCreator.java
Fixes #1578 
The SQL created with `java -jar deegree-tools-gml-3.5.4-SNAPSHOT.jar SqlFeatureStoreConfigCreator -schemaUrl=https://inspire.ec.europa.eu/schemas/ps/4.0/ProtectedSites.xsd -format=all -srid=25833 -idtype=uuid -mapping=blob` contains the srid as expected:
```
SELECT ADDGEOMETRYCOLUMN('public', 'feature_types','bbox','25833','GEOMETRY',2);
...
SELECT ADDGEOMETRYCOLUMN('public', 'gml_objects','gml_bounded_by','25833','GEOMETRY',2);
```
> Added srid in created SQL for blob mode and PostgreSQL

- SECURITY.md
This PR sets the version 3.4 to deprecated and stating that no security fixes will be provided anymore, see https://github.com/deegree/deegree3/security/policy.
Related to #1365
> Updating security policy 

- deegree-services/deegree-services-commons/src/main/java/org/deegree/services/controller/utils/HttpResponseBuffer.java
- deegree-services/deegree-services-commons/src/test/java/org/deegree/services/controller/utils/HttpResponseBufferTest.java
While working on #1618 I found this issue, that when response buffering is active, a single record CSV output was suppressed.
This was boiling down to the point that a Writer was created in `HttpResponseBuffer` but not flushed when `flushBuffer()` is called like it is done for the `xmlWriter`.
To work around the issue of a possible closed writer instead of `flush()`, which raises an exception on an already closed stream, the `checkError()` was used which only flushes if the writer is still open (see [1]).
References:
1. https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/io/PrintWriter.html#checkError()
> Fix buffer issue when response buffering is active and a short results

- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/SvgRenderer.java
- deegree-core/deegree-core-rendering-2d/src/test/java/org/deegree/rendering/r2d/SvgRendererTests.java
This PR prevents errors when SVG should be rendered to a size smaller than one pixel.
Probably one of the last batik version updates introduced this issue.
Without this workaround, the following exception occurs:
```
org.apache.batik.transcoder.TranscoderException: null
Enclosed Exception: 
negative or zero width
```
Manual tests on existing workspaces showed that even a sub pixel image won't turn into rendering problems as 1×1 images are ignored or rendered correctly scaled (smaller).
References:
* #1575 
* #1267
* #1263
> Fix regression with SVG that would be rendered smaller than one pixel

- pom.xml
This is the “sledgehammer” method to provide a logger while running JUnit tests.
Needs to be discussed in a TMC meeting because of possible side efects.
pro
* does not require modification of every module
con
* does not work when running tests in IDE 
* may interfere with modules which have a logger configured
Probably the only alternative in my opinion is to create a module like `deegree-core-test` with a `src/main/ressources/simplelogger.properties` and a compile-time dependency to `org.slf4j:slf4j-simple` which is manually added to each module (see #1606). 
References 
- #1587 
- #1606 
closes #1587
> Re-enable logging when running tests in maven build

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/GmlReferenceData.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/java/org/deegree/feature/persistence/sql/mapper/GmlReferenceDataTest.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/resources/org/deegree/feature/persistence/sql/mapper/data/Inspire-Adress_withInlineFeature.xml
> Ensure mapping for inline features (deegree 3.5)

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/GmlReferenceData.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/java/org/deegree/feature/persistence/sql/mapper/GmlReferenceDataTest.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/resources/org/deegree/feature/persistence/sql/mapper/data/Inspire-Adress_withInlineFeature.xml
Currently the SQLFeatureStoreCreator considers only feature type with features explicitly configured as featureMembers in the referenceData. This PRs ensures that mapping is written also for inline features.
> Ensure mapping for inline features (deegree 3.6)

- pom.xml
This PR upgrades dependencies and maven plugins to latest version including `gson` and `commons-collections` for `main` branch.
PR for `3.5-main` #1663
> Upgrade dependencies gson, commons-collections4 and maven plugins (3.6)

- deegree-core/deegree-connectionprovider-datasource/src/main/resources/META-INF/schemas/connectionprovider/datasource/example_dbcp_mssql.xml
- deegree-core/deegree-connectionprovider-datasource/src/main/resources/META-INF/schemas/connectionprovider/datasource/example_dbcp_oracle.xml
- deegree-core/deegree-connectionprovider-datasource/src/main/resources/META-INF/schemas/connectionprovider/datasource/example_dbcp_postgres.xml
- pom.xml
This PR upgrades the dependencies of Apache commons pool, Apache DBCP2 and the related logging APIs slf4j and log4j2 to latest versions.
The [slf4j 2.0 migration guide](https://www.slf4j.org/faq.html#changesInVersion200) indicates no API changes and upgrading to 2.0.x shoud be a drop-in replacement. 
Also the PR adds the close method to all JDBC connection templates to avoid incomplete configurations.
> Upgrade dependencies of Apache commons pool, and dbcp2 to latest version

- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/xml/schema/XMLSchemaInfoSet.java
The updated [INSPIRE schemas](https://github.com/INSPIRE-MIF/application-schemas/releases) references schemas in different versions. The namespace urls are bound to the same prefix. E.g: https://inspire.ec.europa.eu/schemas/us-govserv/5.0/GovernmentalServices.xsd
contains
```
<schema  xmlns:au="http://inspire.ec.europa.eu/schemas/au/5.0" ...>
...
<import namespace="http://inspire.ec.europa.eu/schemas/ad/4.0" schemaLocation="https://inspire.ec.europa.eu/schemas/ad/4.0/Addresses.xsd"/>
<import namespace="http://inspire.ec.europa.eu/schemas/au/5.0" schemaLocation="https://inspire.ec.europa.eu/schemas/au/5.0/AdministrativeUnits.xsd"/>
```
The referenced https://inspire.ec.europa.eu/schemas/ad/4.0/Addresses.xsd uses  version 4.0 of AdministrativeUnits:
```
<schema …
```
> Enhanced GmlTool to support multiple namespaces with same prefix in one application schema (3.5)

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/ddl/PostGISDDLCreator.java
The schema name in the CREATE INDEX statement was missing:
```
SELECT ADDGEOMETRYCOLUMN('xplansyn', 'xplan_bp_schutzpflegeentwicklungsmassnahme','xplan_position','25832','GEOMETRY', 2);
CREATE INDEX spidx_xplan_bp_schutzgebiet_xplan_position ON xplan_bp_schutzgebiet USING GIST (xplan_position ); ;
```
Expected:
```
SELECT ADDGEOMETRYCOLUMN('xplansyn', 'xplan_bp_schutzpflegeentwicklungsmassnahme','xplan_position','25832','GEOMETRY', 2);
CREATE INDEX spidx_xplan_bp_schutzgebiet_xplan_position ON xplansyn.xplan_bp_schutzgebiet USING GIST (xplan_position ); ;
```
> Added schema to table name to create the index 

- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/query/QueryAnalyzer.java
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
If a StoredQuery with `srsName` is configured
```
<wfs:Query srsName="${srsName}" >
```
the GetFeature-StoredQueries works fine if the srsName is passed but fails if not. 
This PR replaces ${srsName} with the default CRS if no srsName is provided by the request.
By that, optional WFS Parameter srsName is usable in StoredQueries.
> Add support of srsName in StoredQueries

- deegree-core/deegree-core-sqldialect/deegree-sqldialect-postgis/src/main/java/org/deegree/sqldialect/postgis/PostGISDialect.java
- deegree-services/deegree-services-wpvs/src/main/java/org/deegree/services/wpvs/io/db/PostgisBackend.java
- deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/coverage/gridifier/index/MultiLevelMemoryTileGridIndex.java
- deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/coverage/gridifier/index/PostGISRasterTileIndex.java
- pom.xml
This PR upgrade the PostGIS JDBC driver to the latest version with Java 9+ support.
See https://github.com/postgis/postgis-java/releases for list of changes
> Upgraded PostGIS JDBC driver to v2023.1.0 with support for Java 9+

- deegree-services/deegree-webservices-handbook/src/main/asciidoc/javamodules.adoc
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/serverconnections.adoc
This PR enhances the documention with examples how to configure different connection pool provider such as hikariCP, c3p0, and the PostgreSQL JDBC driver build-in DataSource. Also fixed config examples for MS SQL Server and aligned the description of Apache DBCP2 connection pool properties.
> Enhanced documention with examples how to configure different connection pool provider

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/ddl/DDLCreator.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/ddl/PostGISDDLCreator.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/AppSchemaMapper.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/java/org/deegree/feature/persistence/sql/mapper/AppSchemaMapperTest.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/config/FeatureStoreConfigWriter.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/config/LoadParameter.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/config/LoadParameterBuilder.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/config/SqlFeatureStoreConfigCreatorConfiguration.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/config/SqlFeatureStoreConfigCreatorUsagePrinter.java
This PR extends the SqlFeatureStoreConfigCreator by the new Parameter `-dbschema=test`. The passed db schema is written into the SQLFeatureStore configuration as well as the generated SQL Statements.
> Enhanced SqlFeatureStoreConfigCreator to support new parameter dbschema (3.5)

- deegree-core/deegree-core-sqldialect/deegree-sqldialect-oracle/pom.xml
- deegree-datastores/deegree-coveragestores/deegree-coveragestore-oracle-georaster/pom.xml
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/javamodules.adoc
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/serverconnections.adoc
- deegree-services/deegree-webservices/pom.xml
- pom.xml
This PR upgrades the oracle libraries to a recent version.
The required private libraries have been uploaded to the private repository.
Tests have been made with a docker setup using the container `tomcat:10-jdk11` and `container-registry.oracle.com/database/free:23.4.0.0` as the database.
Vector and raster (GeoRaster) access has been tested against a sample dataset.
fixes #1475
References:
- #1475
> Upgrade oracle driver to 23

- .github/workflows/maven.yml
- .mvn/wrapper/maven-wrapper.properties
- mvnw
- mvnw.cmd
This PR adds [Apache Maven wrapper](https://maven.apache.org/wrapper/). The wrapper should work with different operating systems such as:
-   Linux
-  OSX
-  Windows
You can run maven goals like this for the Unix system:
`./mvnw clean install`
> Add maven wrapper

- deegree-services/deegree-webservices/pom.xml
- deegree-tests/deegree-compliance-tests/pom.xml
- deegree-tests/deegree-integration-tests/pom.xml
- deegree-tests/deegree-wms-remoteows-tests/pom.xml
- deegree-tests/deegree-wms-similarity-tests/pom.xml
- deegree-tests/deegree-wmts-tests/pom.xml
- deegree-tests/deegree-workspace-tests/pom.xml
- deegree-tools/deegree-tools-3d/pom.xml
- deegree-tools/deegree-tools-base/pom.xml
- pom.xml
PR changes the SLF4J implementation of log4j2, to the one for SLF4J v2.x, as there are two different implementations available.
SLF4J was updated in #1669
References:
- #1669
> Change SLF4J implementation of log4j2 to be compatible to SLF4J 2.x

- deegree-client/deegree-jsf-core/src/main/java/org/deegree/client/core/debug/DebugPhaseListener.java
- deegree-client/deegree-jsf-core/src/main/resources/META-INF/beans.xml
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/connection/remoteows/CreateRemoteOwsBean.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/connection/sql/ConnectionTester.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/connection/sql/CreateSqlConnectionBean.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/datastore/coverage/CreateCoverageBean.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/datastore/feature/CreateFeatureStoreBean.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/datastore/feature/MappingWizardSQL.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/datastore/metadata/CreateMetadataStoreBean.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/datastore/tile/CreateTileStoreBean.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/layer/layer/CreateLayerBean.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/layer/style/CreateStyleBean.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/layer/theme/CreateThemeBean.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/process/CreateProcessBean.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/proxy/ProxyBean.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/webservices/CreateServiceBean.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/webservices/wps/ProcessExecutionsBean.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/webservices/wps/WPSBean.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/workspace/CreateWorkspaceBean.java
- deegree-services/deegree-webservices/src/main/resources/META-INF/beans.xml
> Fix deegree admin console: scan beans, implement serializable

- deegree-core/deegree-core-base/src/test/java/org/deegree/gml/feature/GMLFeatureWriterTest.java
- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/utils/StringUtils.java
- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/xml/schema/RedirectingEntityResolver.java
- deegree-core/deegree-core-commons/src/test/java/org/deegree/commons/utils/StringToolsTest.java
- deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/rangeset/Interval.java
- deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/cache/CacheRasterReader.java
- deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/data/info/BandType.java
- deegree-core/deegree-core-coverage/src/main/java/org/deegree/coverage/raster/interpolation/InterpolationType.java
- deegree-core/deegree-core-cs/src/main/java/org/deegree/cs/configuration/wkt/WKTParser.java
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-commons/src/main/java/org/deegree/sqldialect/filter/AbstractWhereBuilder.java
- deegree-core/deegree-core-style/src/main/java/org/deegree/style/styling/wkn/TrueTypeFontLoader.java
- deegree-datastores/deegree-mdstores/deegree-mdstore-iso/src/main/java/org/deegree/metadata/iso/persistence/inspectors/IdUtils.java
- deegree-datastores/deegree-mdstores/deegree-mdstore-iso/src/main/java/org/deegree/metadata/iso/persistence/sql/AbstractSqlHelper.java
- deegree-services/deegree-services-commons/src/main/java/org/deegree/services/metadata/provider/DefaultOwsMetadataProviderBuilder.java
- deegree-services/deegree-services-wcs/src/main/java/org/deegree/services/wcs/capabilities/Capabilities100XMLAdapter.java
- deegree-services/deegree-services-wcs/src/main/java/org/deegree/services/wcs/describecoverage/CoverageDescription100XMLAdapter.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/WebFeatureService.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/theme/DatasetMetadataFactory.java
- deegree-tools/deegree-tools-3d/src/main/java/org/deegree/tools/rendering/manager/buildings/BuildingManager.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/config/FeatureStoreConfigWriter.java
This PR is a rebased version of #1639 which resolved the conflicts.
Original Text:
> Proposal for replacing pattern compiles in degree for methods: String.replaceFirst and String.replaceAll
Closes #1639
Fixes #1633
References:
* #1633 
* #1639
> Replace String.replaceAll and String.replaceFirst with precompiled java.util.regex.Pattern to speed up String replacements

- deegree-services/deegree-webservices/src/main/java/org/deegree/console/Config.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/connection/sql/ConnectionTester.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/connection/sql/JdbcBean.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/datastore/feature/FeatureStoreConfig.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/datastore/feature/MappingWizardSQL.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/datastore/metadata/MetadataStoreConfig.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/generic/Connection.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/generic/XmlEditorBean.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/moduleinfo/ModulesBean.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/workspace/WorkspaceBean.java
- deegree-services/deegree-webservices/src/main/webapp/console/generic/sql.xhtml
> Several bug fixes for the admin console (Faces 4.0)

- deegree-services/deegree-webservices/pom.xml
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/security/LogBean.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/security/PasswordFile.java
- deegree-services/deegree-webservices/src/main/java/org/deegree/console/security/SaltedPassword.java
- deegree-services/deegree-webservices/src/test/java/org/deegree/console/security/PasswordFileTest.java
- deegree-services/deegree-webservices/src/test/java/org/deegree/console/security/SaltedPasswordTest.java
Fixes #1616. This PR introduces the UNIX crypt extended password format for the file console.pw. It will introduce a breaking change to the file format of the console.pw file. Users need to re-create their password when upgrading to deegree 3.6.
> Changing format of password stored in console.pw to UNIX crypt extended format

- pom.xml
This PR fixes the typo in maven project root POM https://github.com/deegree/deegree3/blob/main/pom.xml#L1235
> Fixed typo in maven property axiom.version

- pom.xml
- src/site/site.xml
This PR covers only two instances, a lot of license headers of .java files still refer to the HTTP address.
> Remove links to HTTP and replace them with HTTPS

- deegree-services/deegree-services-commons/src/main/resources/META-INF/schemas/services/metadata/example.xml
The information was changed so it matches the information of already adjusted example templates.
This PR closes issue #1551.
> Adjust the information displayed in the service metadata example of deegree

- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/Capabilities130XMLAdapter.java
Write schemaLocation with https in WMS 1.1.3 capabilities.
> Write schemaLocation with https in WMS 1.1.3 capabilities (3.5)

- pom.xml
PR upgrades dependencies to fit with Spring Boot Version 3.3.0, see issue #1718 for more information.
> Upgraded dependencies to fit with Spring Boot 3.3.0 

- deegree-core/deegree-core-commons/pom.xml
- deegree-core/deegree-core-geometry/pom.xml
- deegree-core/deegree-core-style/pom.xml
- deegree-services/deegree-services-commons/pom.xml
- deegree-services/deegree-webservices/pom.xml
- deegree-services/deegree-webservices/src/test/java/org/deegree/console/security/PasswordFileTest.java
- deegree-services/deegree-webservices/src/test/java/org/deegree/console/security/SaltedPasswordTest.java
- deegree-tools/deegree-tools-gml/pom.xml
- pom.xml
This PR moves the import of the Spring Boot BOM in the dependencyManagement section of the root POM into the submodule deegree-tools-gml. As a result several dependencies were required to be added to some sub modules.
See #1718 for more information.
> Moving Spring Boot BOM into submodule deegree-tools-gml

- deegree-tests/deegree-integration-tests/pom.xml
- deegree-tests/pom.xml
- pom.xml
This PR upgrades the maven plugins used for running the integration tests to their latest bugfix version:
- bumbed jetty to 11.0.24
- bumbed soapui to 5.7.2
Also removed outdated config option for jetty plugin.
> Upgraded jetty and soapUI maven plugins to latest bugfix version

- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/feature/GMLFeatureWriter.java
nilReason was previously true:
```
<ef:operationalActivityPeriod xsi:nil="true" nilReason="true"/>
```
With the fix the value from the database is used:
```
<ef:operationalActivityPeriod xsi:nil="true" nilReason="other:unpopulated"/>
```
PR with backport for 3.5 #1744
> Fixed value of nilReason (3.6)

- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/feature/GMLFeatureWriter.java
nilReason was previously true:
```
<ef:operationalActivityPeriod xsi:nil="true" nilReason="true"/>
```
With the fix the value from the database is used:
```
<ef:operationalActivityPeriod xsi:nil="true" nilReason="other:unpopulated"/>
```
> Fixed value of nilReason (3.5)

- deegree-services/deegree-services-commons/src/api/java/org/deegree/services/controller/OGCFrontController.java
- deegree-services/deegree-services-commons/src/test/java/org/deegree/services/controller/OGCFrontControllerTest.java
When deegree is used behind a proxy or load balancer, the initial `Host` header gets passed as `X-Forwarded-Host`.
Along the `X-Forwarded-Host` most proxies also pass the `X-Forwarded-Port` header.
As `X-Forwarded-Host`  is not strictly defined by a standard (see [1]/[2] ) it is possible that the proxy also includes the port.
This results in an exception if the WFS capabilities are requested.
See #1756 for backport to 3.5.
Example Request to trigger this:
```bash
curl --request GET \
--url 'https://demo.deegree.org/inspire-workspace/services?SERVICE=WFS&REQUEST=GetCapabilities' \
--header 'Host: demo.deegree.org:443'
```
Response (shortened):
```xml
<WFS_Capabilities version="2.0.0" xmlns="http://www.opengis.net/wfs/2.0" …
```
> Fix URL creation when header X-Forwarded-Port and X-Forwarded-Host with port are used (3.6)

- deegree-services/deegree-services-commons/src/api/java/org/deegree/services/controller/OGCFrontController.java
- deegree-services/deegree-services-commons/src/test/java/org/deegree/services/controller/OGCFrontControllerTest.java
Backport of #1755
Description of #1755:
When deegree is used behind a proxy or load balancer, the initial `Host` header gets passed as `X-Forwarded-Host`.
Along the `X-Forwarded-Host` most proxies also pass the `X-Forwarded-Port` header.
As `X-Forwarded-Host`  is not strictly defined by a standard (see [1]/[2] ) it is possible that the proxy also includes the port.
This results in an exception if the WFS capabilities are requested.
Example Request to trigger this:
```bash
curl --request GET \
--url 'https://demo.deegree.org/inspire-workspace/services?SERVICE=WFS&REQUEST=GetCapabilities' \
--header 'Host: demo.deegree.org:443'
```
Response (shortened):
```xml
<WFS_Capabilities version="2.0.0" xmlns="http://www.opengis.net/wfs/2.0" …
```
> Fix URL creation when header X-Forwarded-Port and X-Forwarded-Host with port are used (3.5)

- pom.xml
This PR upgrades imageio-ext libs to latest version 1.4.12: https://github.com/geosolutions-it/imageio-ext/releases/tag/1.4.12
Changes since v1.1.29: https://github.com/geosolutions-it/imageio-ext/compare/1.1.29...1.4.12
> Upgraded to imageio-ext to latest version 1.4.12

- deegree-services/deegree-webservices/pom.xml
- deegree-tests/pom.xml
- pom.xml
This PR added property to reuse add-opens, add-export values, removed illegal-access=permit arg which was dropped with JDK 17, removed unsupported jetty plugin property
> Added property with add-opens, add-exports JVM arguments

- deegree-services/deegree-webservices/pom.xml
- pom.xml
This PR fixes a critical issue in primeface CVSS 10 and also extra-enforcer-rules, commons-io and other.
> Upgraded Primefaces and other dependencies to latest bugfix version (3.6)

- pom.xml
This PR upgrades Spring Boot to v3.3.5: https://github.com/spring-projects/spring-boot/releases/tag/v3.3.5
> Upgraded Spring Boot to v3.3.5

- deegree-tools/deegree-tools-gml/pom.xml
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/GmlLoaderConfiguration.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/ReportWriter.java
- deegree-tools/deegree-tools-gml/src/test/java/org/deegree/tools/featurestoresql/loader/GmlLoaderConfigurationTest.java
- deegree-tools/deegree-tools-gml/src/test/java/org/deegree/tools/featurestoresql/loader/ReportWriterTest.java
This PR fixes an exception caused by a missing JobBuilderFactory bean in the GmlLoaderConfiguration class.
The initial stack trace of the exception that was thrown when using the GmlLoader:
```
024-11-06 13:08:24 [main] WARN o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'gmlLoaderConfiguration': Unsatisfied dependency expressed through field 'jobBuilderFactory': No qualifying bean of type 'org.springframework.batch.core.configuration.annotation.JobBuilderFactory' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: …
```
> Fix missing JobBuilderFactory bean in GmlLoaderConfiguration

- pom.xml
PR upgrades:
- commons-io
- commons-codec
- h2
- gson 
- log4j
to latest bugfix version.
> Upgrade commons-io, commons-codec, h2, gson, log4j.version (3.6)

- deegree-core/deegree-core-sqldialect/deegree-sqldialect-postgis/src/main/java/org/deegree/sqldialect/postgis/PostGISDialect.java
- deegree-services/deegree-services-wpvs/src/main/java/org/deegree/services/wpvs/io/db/PostgisBackend.java
- deegree-services/deegree-webservices/pom.xml
- deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/coverage/gridifier/index/MultiLevelMemoryTileGridIndex.java
- deegree-tools/deegree-tools-base/src/main/java/org/deegree/tools/coverage/gridifier/index/PostGISRasterTileIndex.java
- pom.xml
This PR upgrades 
- postgis to v2024.1.0 which fixes known CVE's, 
- postgresql to v42.7.4, 
- and downgrades primefaces to v13.0.10 to resolve #1772.
> Upgraded dependencies to latest bugfix versions

- pom.xml
PR upgrades json-smart to latest version 2.5.2
Backport: PR for `3.5-main`: #1780
> Upgraded dependency json-smart to v2.5.2 (3.6)

- pom.xml
This PR upgrades json-smart to latest bugfix version v2.5.2 which fixes https://github.com/advisories/GHSA-pq2g-wx69-c263
- https://github.com/netplex/json-smart-v2/releases/tag/2.5.2
Also postgresql upgraded to postgresql to 42.7.5 and commons-codes as in PR #1779, owasp dependency-check-maven updated to [12.1.0](https://github.com/jeremylong/DependencyCheck/releases/tag/v12.1.0)
> Upgraded dependencies: json-smart to v2.5.2, postgresql to v42.7.5 (3.5)

- pom.xml
This PR upgrades the OWASP dependency-check-maven plugin to [12.1.0](https://github.com/jeremylong/DependencyCheck/releases/tag/v12.1.0).
> Upgraded OWASP maven plugin to v12.1.0

- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/xml/schema/RedirectingEntityResolver.java
This PR fixes the unit test error when resolving CityGML schema and its parts due to change from http to https in namespace url.
See issue #1796 for more information which solution is preferred.
Backport for 3.5: #1797
> Fixed error when resolving CityGML schema and its parts (3.6)

- pom.xml
This PR fixes issue #1800 by setting the spotbugs-maven-plugin to version 4.9.3.0 to resolve the build issue during pipeline step "Quality Checks".
> Upgraded spotbugs-maven-plugin to 4.9.3.0

- Jenkinsfile
This PR fixes #1800 by setting the fixed version 4.8.6.0 for the spotbugs maven plugin to avoid in incompatibility with doxia when executing quality goal in Jenkins pipeline. PR #1801 set the plugin version for maven profile "site-all-reports" only.
> Fixed version for spotbugs maven plugin in Jenkins pipeline

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/AppSchemaMapper.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/java/org/deegree/feature/persistence/sql/mapper/AppSchemaMapperTest.java
Using the SqlFeatureStoreConfigCreator with the following command results in an uncomplete mapping:
`java -jar deegree-tools-gml-3.5.8.jar SqlFeatureStoreConfigCreator -format=all -srid=25833 -idtype=uuid -mapping=relational -dialect=postgis -schemaUrl=https://inspire.ec.europa.eu/schemas/lcv/5.0/LandCoverVector.xsd -referenceData=refData.gml -useRefDataProps=true`
The elements, e.g. `lcv:extent` und `lcv:nomenclatureDocumentation` are missing because of their complexity.
This PR applies `useRefDataProps=true` to complex xml elements.
> Enhance SqlFeatureStoreConfigCreator to apply useRefDataProps to complex xml elements (3.5)

- deegree-core/deegree-core-cs/src/main/resources/org/deegree/cs/persistence/deegree/d3/config/crs-definitions.xml
This PR adds http://www.opengis.net/def/crs/EPSG/0/XXX notation to EPSG:5554, EPSG:5555 and EPSG:5556
Required for OGC API for Features.
Backport #1806
> Added http notation to EPSG:5554,5555,5556 (3.6)

- deegree-core/deegree-core-cs/src/main/resources/org/deegree/cs/persistence/deegree/d3/config/crs-definitions.xml
This PR adds http://www.opengis.net/def/crs/EPSG/0/XXX notation to EPSG:5554, EPSG:5555 and EPSG:5556
Required for OGC API for Features.
> Added http notation to EPSG:5554,5555,5556 (3.5)

- deegree-core/deegree-core-sqldialect/deegree-sqldialect-commons/src/main/java/org/deegree/sqldialect/filter/AbstractWhereBuilder.java
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-commons/src/main/java/org/deegree/sqldialect/filter/PropertyNameMapper.java
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-mssql/src/main/java/org/deegree/sqldialect/mssql/MSSQLWhereBuilder.java
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-mssql/src/test/java/org/deegree/sqldialect/mssql/MSSQLWhereBuilderTest.java
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-oracle/src/main/java/org/deegree/sqldialect/oracle/OracleWhereBuilder.java
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-postgis/src/main/java/org/deegree/sqldialect/postgis/PostGISWhereBuilder.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-shape/src/main/java/org/deegree/feature/persistence/shape/H2WhereBuilder.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStore.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLPropertyNameMapper.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/xpath/MappedXPath.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/java/org/deegree/feature/persistence/sql/SQLPropertyNameMapperTest.java
- deegree-datastores/deegree-mdstores/deegree-mdstore-ebrim-eo/src/main/java/org/deegree/metadata/persistence/ebrim/eo/mapping/EOPropertyNameMapper.java
- deegree-datastores/deegree-mdstores/deegree-mdstore-iso/src/main/java/org/deegree/metadata/iso/persistence/ISOPropertyNameMapper.java
- deegree-documentation/src/main/asciidoc/appendix.adoc
> Enhanced bbox requests without geometry property to consider all geometry properties (3.6)

- deegree-services/deegree-services-wfs/pom.xml
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/WebFeatureService.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/gml/GmlFormat.java
- pom.xml
This PR migrates `commons-lang:commons-lang:2.6` to `org.apache.commons:commons-lang3:3.18.0` using [org.openrewrite.apache.commons.lang.UpgradeApacheCommonsLang_2_3](https://docs.openrewrite.org/recipes/apache/commons/lang/upgradeapachecommonslang_2_3) 
This upgrade fixes CVE-2025-48924.
> Migrate to Apache Commons Lang 3 

- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/context/ImageRenderContext.java
- deegree-core/deegree-core-style/src/main/java/org/deegree/style/utils/ImageUtils.java
This fix re-enables JPEG output and correct handling of the `transparent` and `bgcolor` WMS parameters for remote WMS and GDAL layers.
For both layer types deegree tries to reuse an existing `BufferedImage` (provided by the WMS client or by GDAL) and this fails when this image has an alpha layer and JPEG output is requested or transparency is not enabled in the request.
> Fixed non-transparant WMS output for remote WMS and GDAL layers

- deegree-datastores/deegree-featurestores/deegree-featurestore-shape/src/main/java/org/deegree/feature/persistence/shape/H2WhereBuilder.java
Fixes #1854 
This PR fixes the GFI of a shapefile datasource. As the 'mapper' in the H2WhereBuilder is null an unexpected  NPE occured. By throwing an (expected) UnmappableException a post fiter is used.
> Fix GetFeatureInfo on SHP datasource

- deegree-core/deegree-core-base/src/main/java/org/deegree/geojson/GeoJsonGeometryWriter.java
- deegree-core/deegree-core-base/src/main/java/org/deegree/geojson/GeoJsonWriter.java
- deegree-core/deegree-core-base/src/test/java/org/deegree/geojson/GeoJsonFeatureWriterTest.java
This PR follows up on #1830 and resolves an issue with transforming the additional WKT geometry (when enabled) if a different CRS is requested.
PR with backport for 3.5: #1853
GeoJSON output with of an WKT geometry under `EPSG:5555`:
```
"boreholePath": "LINESTRING (476589.310000 5970112.160000 6.020000,476589.310000 5970112.160000 -10.480000)"
```
GeoJSON output of the same WKT geometry under `EPSG:5554`:
```
"boreholePath": "LINESTRING (476589.310000 5970112.160000 6.020000,476589.310000 5970112.160000 -10.480000)"
```
* The WKT geometry is not transformed :x: 
GeoJSON output of the same  WKT geometry under `EPSG:5554`:
```
"boreholePath": "LINESTRING (870843.268878 5984827.566754 6.025525,870843.268878 5984827.566755 -10.474475)"
```
* The WKT geometry is successfully transformed …
> Fix WKT geometry transformation in GeoJSON for non-default CRS requests (3.6)

- deegree-documentation/src/main/asciidoc/webservices.adoc
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/Wms130SoapExtendedCapabilitesWriter.java
- deegree-services/deegree-services-wms/src/test/resources/org/deegree/services/wms/controller/capabilities/soapwms.xsd
deegree is using a wrong namespace for SOAP WMS. It starts with http**s** instead of http.
This was fixed and, now, the namespace aligns to the one used in the uploaded schema: https://schemas.deegree.org/extensions/services/wms/1.3.0/soapwms.xsd
Backport for 3.5: #1860
> Fix SOAP WMS namespace (3.6)

- deegree-services/deegree-webservices/pom.xml
- deegree-tools/deegree-tools-gml/pom.xml
- pom.xml
PR includes
- Upgraded required maven version to 3.9
- Upgraded maven plugins to latest bugfix version
- Cleaned up spring dependencies, using spring-boot dependencies only
- Bumped spring-boot-dependencies to 3.4.9
- Bumped commons-io to 2.20.0
- Bumped commons-codec to 1.19.0
- Bumped commons-csv to 1.14.1
- Bumped ehcache to 3.11.0
- Bumped jsonsmart to 2.6.0
- Bumped primefaces to 14.0.14-LTS
- Bumped jakarta-mail to 2.1.4
> Upgraded maven dependencies and plugins to latest version

- deegree-documentation/src/main/asciidoc/gdal.adoc
- pom.xml
This PR upgrades  GDAL JAR to 3.11.0 and adds some more information to the documentation how to configure the gdal options. Link to GDAL documentation was fixed.
> Upgraded GDAL to 3.11.0 and updated documentation

- .mvn/wrapper/maven-wrapper.properties
Upgrade Maven wrapper after #1857 changed the minimal required version.
Command used to create this PR:
`./mvnw wrapper:wrapper -Dmaven=3.9.11`
> Upgrade Maven wrapper
