deegree/deegree3

- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/context/DefaultRenderContext.java
- deegree-core/deegree-core-style/src/main/java/org/deegree/style/utils/ColorQuantizer.java
- deegree-core/deegree-core-style/src/main/java/org/deegree/style/utils/DiffusionFilterOp.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/WMSController.java
Adds png 8bit support with indexed color model.
> PNG 8bit support

- deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/standard/primitive/DefaultRing.java
Here's an example of such a beast:
```xml
<gml:Ring>
<gml:curveMember xlink:type="simple">
<gml:Curve xsi:type="aixm:CurveType" srsName="urn:ogc:def:crs:EPSG::4326" gml:id="uuid.d90d567d-d04d-45ac-bd17-6e033d126031">
<gml:segments>
<gml:GeodesicString interpolation="geodesic">
<gml:posList>47.83222222222223 7.556666666666667 ...</gml:posList>
</gml:GeodesicString>
</gml:segments>
</gml:Curve>
</gml:curveMember>
<gml:curveMember xlink:type="simple" xlink:href="urn:uuid:afac8ce6-c743-47d3-9584-8ff9a05df125"/>
<gml:curveMember xlink:type="simple">
<gml:Curve xsi:type="aixm:CurveType" srsName="urn:ogc:def:crs:EPSG::4326" gml:id="uuid.ffbf75d9-019e-430d-abd6-8ad6f2c86d23">
<gml:segments>
<gml:GeodesicString interpolation="geodesic">
<gml:posList>47.58996944444445 7.589102777777778 …
```
> Allow creation of GML rings with unresolvable member references

- deegree-core/deegree-core-protocol/deegree-protocol-wmts/src/main/java/org/deegree/protocol/wmts/ops/GetFeatureInfo.java
- deegree-core/deegree-core-protocol/deegree-protocol-wmts/src/main/java/org/deegree/protocol/wmts/ops/GetTile.java
- deegree-core/deegree-core-tile/src/main/java/org/deegree/tile/TileDataLevel.java
- deegree-datastores/deegree-tilestores/deegree-tilestore-cache/src/main/java/org/deegree/tile/persistence/cache/CachingTileMatrix.java
- deegree-datastores/deegree-tilestores/deegree-tilestore-filesystem/src/main/java/org/deegree/tile/persistence/filesystem/FileSystemTileDataLevel.java
- deegree-datastores/deegree-tilestores/deegree-tilestore-gdal/src/main/java/org/deegree/tile/persistence/gdal/GdalTileDataLevel.java
- deegree-datastores/deegree-tilestores/deegree-tilestore-geotiff/src/main/java/org/deegree/tile/persistence/geotiff/GeoTIFFTileDataLevel.java
- deegree-datastores/deegree-tilestores/deegree-tilestore-merge/src/main/java/org/deegree/tile/persistence/merge/MergingTileDataLevel.java
- deegree-datastores/deegree-tilestores/deegree-tilestore-remotewms/src/main/java/org/deegree/tile/persistence/remotewms/RemoteWMSTileDataLevel.java
- deegree-datastores/deegree-tilestores/deegree-tilestore-remotewmts/src/main/java/org/deegree/tile/persistence/remotewmts/RemoteWMTSTileDataLevel.java
- deegree-services/deegree-services-wmts/src/main/java/org/deegree/services/wmts/controller/FeatureInfoFetcher.java
- deegree-services/deegree-services-wmts/src/main/java/org/deegree/services/wmts/controller/FeatureInfoHandler.java
- deegree-services/deegree-services-wmts/src/main/java/org/deegree/services/wmts/controller/TileHandler.java
- deegree-services/deegree-services-wmts/src/main/java/org/deegree/services/wmts/controller/WmtsRequestDispatcher.java
This pull request fixes the following issues:
Fixes #416, #417, #418, #419, #420, #421, #424, #425, #426, #434, #435, #436
> Bugfix: WMTS 1.0.0 Issues fixed

- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/geometry/GML3GeometryWriter.java
- deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/primitive/segments/ArcByCenterPoint.java
This occurred for instances with NULL start or end angles
> GML-Writer: Fix NPE when exporting CircleByCenterPoint

- deegree-core/deegree-core-rendering-2d/src/main/java/org/deegree/rendering/r2d/context/ImageRenderContext.java
- deegree-core/deegree-core-style/src/main/java/org/deegree/style/utils/ColorQuantizer.java
- deegree-core/deegree-core-style/src/main/java/org/deegree/style/utils/DiffusionFilterOp.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/WMSController.java
- deegree-services/deegree-services-wms/src/main/resources/META-INF/schemas/services/wms/3.4.0/wms_configuration.xsd
- deegree-services/deegree-webservices-handbook/src/main/sphinx/webservices.rst
Manually merged #481 and #428.
These pull requests conflicted with #469.
> Manual merge #481 #428

- deegree-core/deegree-core-protocol/deegree-protocol-wfs/src/main/java/org/deegree/protocol/wfs/transaction/xml/TransactionXmlReader200.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-commons/src/main/java/org/deegree/feature/persistence/transaction/FeatureUpdater.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-commons/src/main/java/org/deegree/feature/persistence/transaction/IdChecker.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-memory/src/main/java/org/deegree/feature/persistence/memory/MemoryFeatureStoreTransaction.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-memory/src/main/java/org/deegree/feature/persistence/memory/StoredFeatures.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStore.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStoreTransaction.java
Outfactored and re-used feature modification code from MemoryFeatureStore into FeatureUpdater.
> SQLFeatureStore: Add support for update transactions in BLOB mode

- deegree-layers/deegree-layers-coverage/src/main/java/org/deegree/layer/persistence/coverage/CoverageLayerData.java
This pull requests makes two optimizations to the CoverageLayerData to achieve a faster rendering if a large coverages or a high number of coverages are asigned to a single wms GetMap Operation.
This is achieved by:
* only rendering raster which intersects with the requested bbox
* not holding the transformed request for the current CoverageLayerData in memory until the requests ends
For Example: 
A WMS-GetMap request of 2000x2000 pixel against 200 coverages holds a peak of ~ 3000 MB (4 byter per pixel) at the last processed CoverageLayerData in the heap instead of ~ 32 MB after the patch.
> 3.4 Coverage Layer Heap Enhancement / Rendering Performance Enhancement

- deegree-core/deegree-core-cs/src/main/resources/org/deegree/cs/persistence/deegree/d3/config/crs-definitions.xml
- deegree-core/deegree-core-cs/src/main/resources/org/deegree/cs/persistence/deegree/d3/config/projection-definitions.xml
- deegree-core/deegree-core-cs/src/test/java/org/deegree/cs/persistence/deegree/d3/DeegreeCRSStoreProviderTest.java
- deegree-core/deegree-core-cs/src/test/java/org/deegree/cs/persistence/deegree/d3/Epsg5650Test.java
This pull requests added the configuration of epsg:5650 as specified in [1]. Furthermore it updates the area of use of the coordinate systems epsg:25828 to epsg:25837. The area of use was updated in [1] at 2014-05-01.
[1] ​http://www.epsg-registry.org/
> Added CRS epsg:5650 and updated area of use for epsg:25828 to epsg:25837

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/rules/FeatureBuilderRelational.java
Is the output required for logging? If so it should be changed to use log4j.
> Removed System.out from FeatureBuilderRelational

- deegree-services/deegree-webservices-handbook/src/main/sphinx/layers.rst
I have updated the documentation for layer configuration with a full example.
(New Pull Request - regarding https://github.com/deegree/deegree3/pull/535)
> Improve layer documentation with full example

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/rules/FeatureBuilderRelational.java
This pull requests fixes the Bug reported in #612 by adding an instanceof check for TimeObject.
> Performance improvement for SQLFeatureStore fixing #612

- deegree-services/deegree-services-wfs/src/main/resources/org/deegree/services/wfs/query/idquery.xml
- deegree-services/deegree-services-wfs/src/main/resources/org/deegree/services/wfs/query/typequery.xml
This pull requests adds a title and abstract to the parameter of the StoredQueriesDescriptions.
> Improved configuration of the integrated StoredQueriesDescriptions

- deegree-core/deegree-core-db/src/main/java/org/deegree/db/ConnectionProviderManager.java
This pull request is a possible soultion to prevent dangerous classloader usage and targetes as an alternative to pr #572.
The provided solution is to follow the commonly used method to only use jdbc drivers which are available either by the system (shared or server libraries) or by the application (WEB-INF/lib).
This pull would remove the code which would register jdbc drivers available in the modules folder.
So the need to deregister jdbc drivers (and to fix resulting classloader issues) is not needed any more.
After the talks about the problem with @tfr42 and @hwbllmnn at the FossGIS Hacking Event yesterday, i came to the conclusion that a testing of the most commonly use cases will be required.
So the test scenario may could look like N (20?) iterations of the following:
- (re)load …
> Remove the possibility to load jdbc drivers from modules 

- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/schema/GMLSchemaInfoSet.java
GMLSchemaInfoSet: deegree identified wrongly some Feature Type as Feature Collection.
See issue #552
Please note that the integration tests are already broken on the deegree:master
> Improved the check for GML 3.2 feature collections

- deegree-core/deegree-core-sqldialect/deegree-sqldialect-oracle/src/main/java/org/deegree/sqldialect/oracle/sdo/SDOGeometryConverter.java
This pull request proposes to ignore any LRS information while converting an Oracle SDO (= JDBC STRUCT) to a deegree Geometry.
Currently trying to convert such a STRUCT into a deegree Geometry results in an exception explaining that LRS handling is not supported by deegree.
Unfortunately it is no trivial matter (as far as I know) to properly map an Oracle SDO with LRS information onto the deegree geometry model. Nevertheless, deegree should be able to process the non LRS part of the data. Therefore I would like to suggest to ignore the LRS dimension and treat the remaining dimensions as usual.
The change is implemented by complementing existing code in order to prevent accidentally breaking something.
> Ignore Oracle SDO LRS (Linear Referencing System)

- deegree-core/deegree-core-base/src/main/java/org/deegree/feature/stream/EmptyFeatureInputStream.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStore.java
deegree WFS 2.0.0 returns an exception if a GetFeature request with ResourceId is send where the rid could not be mapped to a FeatureType:
Request: http://localhost:8080/deegree-webservices/services/wfs?service=WFS&version=2.0.0&request=GetFeature&count=10&startindex=0&typenames=ns2:TransactionTest&namespaces=xmlns%28xml,http://www.w3.org/XML/1998/namespace%29,xmlns%28ns2,http://www.deegree.org/app%29,xmlns%28wfs,http://www.opengis.net/wfs/2.0%29&resourceid=test-b5862433-6aa6-44fe-8269-1a2eb8ecc966
Exception:
```xml
<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd" …
```
> Fixed unexpected exception if the rid could not be parsed

- deegree-datastores/deegree-mdstores/deegree-mdstore-iso/src/main/resources/org/deegree/metadata/iso/persistence/postgis/create.sql
> changed srid from text to integer

- deegree-services/deegree-webservices-handbook/src/main/sphinx/webservices.rst
> Removed deegree version from handbook content (CSW JSON functionality)

- pom.xml
Fix for #729 as described there.
> Travis CI Workaround: Increased Heap Size in surefire plugin 

- pom.xml
Fix for #729 as described there.
> 3.3: Travis CI Workaround: Increased Heap Size in surefire plugin

- deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/io/WKBWriter.java
- deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/io/WKTWriter.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/config/MappedSchemaBuilderGML.java
Bakcport of https://github.com/deegree/deegree3/pull/693
Added check for crs-dimension before writing.
> Fix to allow inserting 3d - backport to 3.3

- deegree-core/deegree-core-theme/src/main/resources/META-INF/schemas/themes/3.4.0/themes.xsd
- deegree-datastores/deegree-tilestores/deegree-tilestore-filesystem/src/main/resources/META-INF/schemas/datasource/tile/filesystem/3.4.0/filesystem.xsd
- deegree-layers/deegree-layers-coverage/src/main/resources/META-INF/schemas/layers/coverage/3.4.0/coverage.xsd
- deegree-layers/deegree-layers-feature/src/main/resources/META-INF/schemas/layers/feature/3.4.0/feature.xsd
- deegree-layers/deegree-layers-gdal/src/main/resources/META-INF/schemas/layers/gdal/3.4.0/gdal.xsd
This pull request fixes missed schema imports which were not updated to 3.4.0 in the past pull request #751
> 3.4 change missed schema imports to 3.4.0

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/pom.xml
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/config/SQLFeatureStoreConfigWriter.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/java/org/deegree/feature/persistence/sql/org/deegree/feature/persistence/sql/config/SQLFeatureStoreConfigWriterIT.java
> Fixed SQLFeatureStoreConfigWriter to write config version 3.4.0 

- deegree-services/deegree-webservices-handbook/src/main/sphinx/webservices.rst
The documentation of WFS and WMS was improved regarding the configuration of extended capabilities. 
See #782
> Improved documentation regarding extended capabilities

- deegree-core/deegree-core-protocol/deegree-protocol-commons/src/test/resources/org/deegree/protocol/wps/client/curve.xml
Same as #792 but for the stable deegree version.
> Stable version; Avoid usage of default namespace in curve.xml

- deegree-client/deegree-wps-webclient/src/main/java/org/deegree/wpsclient/controller/ProcessExecuter.java
- deegree-core/deegree-core-protocol/deegree-protocol-commons/src/main/java/org/deegree/protocol/wps/client/input/BinaryInput.java
- deegree-core/deegree-core-protocol/deegree-protocol-commons/src/main/java/org/deegree/protocol/wps/client/input/ExecutionInput.java
- deegree-core/deegree-core-protocol/deegree-protocol-commons/src/main/java/org/deegree/protocol/wps/client/input/XMLInput.java
- deegree-core/deegree-core-protocol/deegree-protocol-commons/src/main/java/org/deegree/protocol/wps/client/process/AbstractProcessExecution.java
- deegree-core/deegree-core-protocol/deegree-protocol-commons/src/main/java/org/deegree/protocol/wps/client/wps100/ExecuteRequest100Writer.java
- deegree-core/deegree-core-protocol/deegree-protocol-commons/src/test/java/org/deegree/protocol/wps/client/WPSClientTest.java
See issue #788. It's indeed possible to use URI instead of URL - and since no maintainers objected, I went ahead and implemented it.
> Make the WPS client use URI instead of URL

- deegree-client/deegree-wps-webclient/src/main/java/org/deegree/wpsclient/controller/ProcessExecuter.java
- deegree-core/deegree-core-protocol/deegree-protocol-commons/src/main/java/org/deegree/protocol/wps/client/input/BinaryInput.java
- deegree-core/deegree-core-protocol/deegree-protocol-commons/src/main/java/org/deegree/protocol/wps/client/input/ExecutionInput.java
- deegree-core/deegree-core-protocol/deegree-protocol-commons/src/main/java/org/deegree/protocol/wps/client/input/XMLInput.java
- deegree-core/deegree-core-protocol/deegree-protocol-commons/src/main/java/org/deegree/protocol/wps/client/process/AbstractProcessExecution.java
- deegree-core/deegree-core-protocol/deegree-protocol-commons/src/main/java/org/deegree/protocol/wps/client/wps100/ExecuteRequest100Writer.java
- deegree-core/deegree-core-protocol/deegree-protocol-commons/src/test/java/org/deegree/protocol/wps/client/WPSClientTest.java
Same as #794 but for the stable branch.
> Stable version: Make the WPS client use URI instead of URL

- deegree-datastores/deegree-featurestores/deegree-featurestore-memory/src/main/java/org/deegree/feature/persistence/memory/MemoryFeatureStoreTransaction.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStoreTransaction.java
- deegree-services/deegree-webservices-handbook/src/main/sphinx/webservices.rst
This Pull Request replaces #807 as it extends with backported changes from #709.
> Add support for Replace action in SQLFeatureStoreTransaction 3.3 [REWORK]

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStoreTransaction.java
Following commit on 3.3-branch:
https://github.com/deegree/deegree3/commit/0c03f3abd95f02a41ce9e5655c880c340c5463b1
> Add support for Replace action in SQLFeatureStoreTransaction 3.3

- .travis.yml
- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/utils/ArrayUtils.java
- deegree-core/deegree-core-commons/src/test/java/org/deegree/commons/utils/ArrayUtilsTest.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/id/IdAnalyzer.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/java/org/deegree/feature/persistence/sql/id/IdAnalyzerTest.java
Same as PR #867, backported to deegree 3.3.
> Fix #848 [SQLFeatureStore] Deleting features fails for certain feature type prefix configurations (3.3-backport)

- deegree-core/deegree-core-geometry/pom.xml
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-oracle/pom.xml
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-postgis/pom.xml
- deegree-datastores/deegree-coveragestores/deegree-coveragestore-oracle-georaster/pom.xml
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/WMSControllerBase.java
- deegree-services/deegree-webservices-handbook/src/main/sphinx/featurestores.rst
- deegree-services/deegree-webservices-handbook/src/main/sphinx/installation.rst
- deegree-services/deegree-webservices-handbook/src/main/sphinx/javamodules.rst
- deegree-services/deegree-webservices-handbook/src/main/sphinx/metadatastores.rst
- deegree-services/deegree-webservices-handbook/src/main/sphinx/serverconnections.rst
- deegree-services/deegree-webservices/pom.xml
- deegree-tests/deegree-csw-bkg/pom.xml
- pom.xml
> Java 8 Updates

- deegree-services/deegree-webservices-tomcat-bundle/pom.xml
Upgraded assembly plugin to 2.6
> Fixing travis-ci build error  failed to download tomcat artifact

- deegree-services/deegree-services-commons/src/main/resources/META-INF/schemas/services/metadata/3.4.0/example.xml
- deegree-services/deegree-webservices-handbook/src/main/sphinx/conf.py
- deegree-services/deegree-webservices-tomcat-bundle/pom.xml
- pom.xml
> Removed real person names from service metadata

- CONTRIB.md
- README.md
Removed all references to subversion and related procedures. Contents with first level headlines added as well as link to OSGeo Code of Conduct. Added link in README.md to CONTRIB.md
> #603 Improved Contribution Guidelines

- deegree-core/deegree-core-geometry/pom.xml
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-postgis/pom.xml
- deegree-services/deegree-webservices-handbook/src/main/sphinx/serverconnections.rst
- pom.xml
Upgrade to most recent Version of PostgreSQL JDBC Driver supporting Java 8 with JDBC 4.2 (compatible to PostgreSQL DBMS 8.2 or newer).
> Upgraded PostgreSQL JDBC Driver to 42.2.5

- CONTRIB.md
Updated contribution guidelines removing references to old infrastructure and fixing formatting for git commands
> Updated contribution guidelines

- deegree-services/deegree-webservices-handbook/src/main/sphinx/installation.rst
- deegree-services/deegree-webservices-handbook/src/main/sphinx/intro.rst
- deegree-services/deegree-webservices-handbook/src/main/sphinx/restapi.rst
Fixes #943 and #942  Added  new section to handbook on how to run securely deegree in production environments.
> Updating handbook with security how to

- deegree-services/deegree-services-commons/src/main/java/org/deegree/services/ows/capabilities/OWSCapabilitiesXMLAdapter.java
> Fixed NPE if ServiceProvider is missing

- deegree-services/deegree-webservices-handbook/src/main/sphinx/xml/wfs_gmlformat.xml
> Fixed position of DecimalCoordinateFormatter

- deegree-services/deegree-webservices-handbook/src/main/asciidoc/gdal.adoc
> #994 Upgrade gdal version in handbook too

- deegree-services/deegree-webservices-handbook/src/main/asciidoc/layers.adoc
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
- deegree-workspaces/deegree-workspace-utah/src/main/workspace/layers/layer_feature_utah_airports.xml
- deegree-workspaces/deegree-workspace-utah/src/main/workspace/layers/layer_feature_utah_stateboundary.xml
was NEAREST_NEIGHBOUR before, correct is NEARESTNEIGHBOUR
> Fixes wrong name for Interpolation option NEARESTNEIGHBOUR

- deegree-services/deegree-webservices-handbook/src/main/asciidoc/serverconnections.adoc
- pom.xml
supporting PG 9.4 and PGIS 2.3 and higher
> Upgrade Postgres JDBC Driver to 42.2.8 and PostGIS 2.3.0

- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/gml/request/GmlGetFeatureHandler.java
If response paging is activated in WFS (service configuration contains `<EnableResponsePaging>true</EnableResponsePaging>`  and resultType="hits" is used in a GetFeature request (and the request contains the count parameter), it is expected that the next URL points to the first subset of response features.
WFS 2.0 specification say following:
```
7.7.4.2 numberMatched parameter
By setting the value of the resultType parameter (see 7.6.3.6) to "hits" a count of the total number of features
or values that an operation would return can be obtained without having to incur the cost of transmitting the
result set. For servers that support response paging (see 7.7.4.4) the value of the next parameter shall be set
to then fetch the first subset of response features or values.
A.2.19.2.2.2 Paging …
```
> Enhanced Response Paging regarding resultType="hits"

- deegree-core/deegree-core-sqldialect/deegree-sqldialect-commons/src/main/java/org/deegree/sqldialect/SQLDialect.java
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-mssql/src/main/java/org/deegree/sqldialect/mssql/MSSQLDialect.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-commons/src/main/java/org/deegree/feature/persistence/FeatureStore.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-commons/src/main/java/org/deegree/feature/persistence/query/Query.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-memory/src/main/java/org/deegree/feature/persistence/memory/MemoryFeatureStore.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-remotewfs/src/main/java/org/deegree/feature/persistence/remotewfs/RemoteWFSFeatureStore.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-shape/src/main/java/org/deegree/feature/persistence/shape/ShapeFeatureStore.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-simplesql/src/main/java/org/deegree/feature/persistence/simplesql/SimpleSQLFeatureStore.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStore.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/gml/request/GmlGetFeatureHandler.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/query/QueryAnalyzer.java
> Revert "Enhanced implementation for WFS 2.0 response paging"

- Jenkinsfile
- deegree-tests/deegree-compliance-tests/pom.xml
- deegree-tests/deegree-csw-bkg/pom.xml
- deegree-tests/deegree-wms-similarity-tests/pom.xml
- deegree-tests/deegree-wms-tiling-tests/pom.xml
- deegree-tests/deegree-wmts-tests/pom.xml
- deegree-tests/deegree-workspace-tests/pom.xml
- pom.xml
This shall support a multi branch pipeline build on the deegree build server http://buildserver.deegree.org/
Plugins are installed and a job is configured to test: http://buildserver.deegree.org/view/misc/job/deegree%20PR/
> Add Jenkinsfile for Jenkins CI to repository

- pom.xml
Upgrade required to enable support for builds with JDK 9/10/11
> Upgraded compiler plugin to 3.8.1 

- pom.xml
This PR upgrades the reflection dependency to 0.9.11 used.
This PR is required to support Java 11 (#857)
> Upgrade org.reflections:reflections to 0.9.11

- Jenkinsfile
fixes wrong integration build report file name and added when-check for steps following integration tests
> #1050 fixing buildpipeline

- Jenkinsfile
Improved step quality check without site but with plugins
> #1051 Fixing build pipeline

- deegree-services/deegree-webservices-tomcat-bundle/pom.xml
- deegree-tools/pom.xml
This PR upgrades the bundle of Apache Tomcat to 8.5 line. 8.0 line has reached end-of-live.
> Upgrades Tomcat bundle to 8.5.x line since 8.0.x line has reached EOL.

- deegree-core/deegree-core-style/src/main/java/org/deegree/style/persistence/sld/SldStyleStoreBuilder.java
- deegree-core/deegree-core-workspace/src/main/java/org/deegree/workspace/ResourceLocation.java
- deegree-core/deegree-core-workspace/src/main/java/org/deegree/workspace/standard/DefaultLocationHandler.java
- deegree-core/deegree-core-workspace/src/main/java/org/deegree/workspace/standard/DefaultResourceLocation.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SqlFeatureStoreBuilder.java
This  PRs allows the administrator of a deegree worksapce to organize  SQLFeatureStoreConfigurations in subfolders.
> Support of SQLFeatureStore configurations in subfolders

- deegree-tests/deegree-compliance-tests/pom.xml
> Fixed growing size of the deegree-compliance-tests web app

- CONTRIB.md
see https://github.com/deegree/deegree3/issues/1149
> change to libera.chat

- deegree-datastores/deegree-tilestores/deegree-tilestore-geotiff/src/main/java/org/deegree/tile/persistence/geotiff/GeoTiffUtils.java
- deegree-datastores/deegree-tilestores/deegree-tilestore-geotiff/src/main/java/org/deegree/tile/tilematrixset/geotiff/GeoTiffTileMatrixSetBuilder.java
> Keep configured CRS

- deegree-workspaces/deegree-workspace-csw/src/main/resources/jdbc/conn1.xml
Adjust configuration as set in https://github.com/deegree/deegree-workspaces/blob/main/deegree-workspace-csw/jdbc/conn1.xml.
These are the values used by the demo.
> Configure JDBC connection of deegree-workspace-csw

- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/GetCapabilitiesHandler.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/query/StoredQueryHandler.java
Fixes the capabilities document when ManageStoredQueries is deactivated (constraint and listed operations).
For details please see #1140.
Fixes #1140
> Fix disabling of ManageStoredQueries

- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/WMSController.java
- deegree-services/deegree-services-wms/src/main/resources/META-INF/schemas/services/wms/3.4.0/wms_configuration.xsd
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
Fixes #1224 
This PR based on PR #1218. The new configuration option is used to enable this strict behavior. Previous behavior is preserved otherwise.
> Add check of service parameter

- deegree-core/deegree-core-protocol/deegree-protocol-wms/src/main/java/org/deegree/protocol/wms/ops/GetMap.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/WMSController.java
- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/WMSControllerBase.java
Fixes #1182.
Please see #1182 for further details.
> Fix exception type for WMS

- deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
The deegree WMTS documentation has been enhanced, since users have asked for a more complete documentation how to setup deegree WMTS.
> Enhancement of the deegree WMTS documentation

- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/WMSController.java
Description of bug: #1236
Fixes #1236.
> WMS 1.3: Throw exception when using invalid service parameter in GetCapabilities request

- deegree-core/deegree-core-sqldialect/deegree-sqldialect-commons/src/main/java/org/deegree/sqldialect/SQLDialect.java
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-mssql/src/main/java/org/deegree/sqldialect/mssql/MSSQLDialect.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-commons/src/main/java/org/deegree/feature/persistence/FeatureStore.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-commons/src/main/java/org/deegree/feature/persistence/query/Query.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-memory/src/main/java/org/deegree/feature/persistence/memory/MemoryFeatureStore.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-remotewfs/src/main/java/org/deegree/feature/persistence/remotewfs/RemoteWFSFeatureStore.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-shape/src/main/java/org/deegree/feature/persistence/shape/ShapeFeatureStore.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-simplesql/src/main/java/org/deegree/feature/persistence/simplesql/SimpleSQLFeatureStore.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStore.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/format/gml/request/GmlGetFeatureHandler.java
- deegree-services/deegree-services-wfs/src/main/java/org/deegree/services/wfs/query/QueryAnalyzer.java
Renews reverted pull request #1004
> Enhanced implementation for WFS 2.0 response paging

- deegree-core/deegree-core-gdal/src/main/java/org/deegree/commons/gdal/GdalSettings.java
- deegree-layers/deegree-layers-gdal/src/main/java/org/deegree/layer/persistence/gdal/GdalLayerData.java
This pull request enables support of CRS:84 in GdalLayer.
> Support of CRS:84 in GdalLayer

- pom.xml
This PR upgrades reflection to v0.9.12 reported security vulnerability by owasp
> Upgrades reflections to v0.9.12

- Jenkinsfile
This PR disables concurrent builds.
> Disabling concurrent builds

- deegree-core/deegree-core-geometry/src/main/resources/META-INF/schemas/commons/spatialmetadata/3.4.0/spatialmetadata.xsd
- deegree-core/deegree-core-geometry/src/test/java/org/deegree/geometry/metadata/SpatialMetadataConverterTest.java
- deegree-core/deegree-core-geometry/src/test/resources/org/deegree/geometry/metadata/envelope.xml
Updated XSD to fix conversion exception.
> Fix bug occuring when configuring envelope in theme or layer

- deegree-datastores/deegree-tilestores/deegree-tilestore-geotiff/src/main/java/org/deegree/tile/persistence/geotiff/GeoTIFFTileDataLevel.java
- deegree-datastores/deegree-tilestores/deegree-tilestore-geotiff/src/main/java/org/deegree/tile/persistence/geotiff/GeoTiffTileDataSetBuilder.java
- deegree-datastores/deegree-tilestores/deegree-tilestore-geotiff/src/main/resources/META-INF/schemas/datasource/tile/geotiff/3.4.0/geotiff.xsd
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/tilestores.adoc
Improves performance of GeoTIFFTileStore.
> Instantiate GenericObjectPool of GeoTIFFTileStore with configuration option maxActive

- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/utils/TunableParameter.java
- deegree-datastores/deegree-tilestores/deegree-tilestore-geotiff/src/main/java/org/deegree/tile/persistence/geotiff/GeoTIFFTile.java
- deegree-datastores/deegree-tilestores/deegree-tilestore-geotiff/src/main/java/org/deegree/tile/persistence/geotiff/GeoTIFFTileDataLevel.java
- deegree-datastores/deegree-tilestores/deegree-tilestore-geotiff/src/main/java/org/deegree/tile/persistence/geotiff/GeoTiffTileDataSetBuilder.java
- deegree-datastores/deegree-tilestores/deegree-tilestore-geotiff/src/main/java/org/deegree/tile/persistence/geotiff/GeoTiffUtils.java
- deegree-datastores/deegree-tilestores/deegree-tilestore-geotiff/src/main/java/org/deegree/tile/persistence/geotiff/ImageReaderFactory.java
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/basics.adoc
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/coveragestores.adoc
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/featurestores.adoc
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/gdal.adoc
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/layers.adoc
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/metadatastores.adoc
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/processproviders.adoc
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/serverconnections.adoc
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/themes.adoc
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/tilestores.adoc
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
- deegree-tests/pom.xml
- pom.xml
Included features:
- remove configVersion occurrences from handbook
- add exclusion for commons-logging
- add enforcer configuration to bann specific dependencies (commons-logging)
> Remove unused references from handbook and build fixes

- deegree-workspaces/deegree-workspace-aixm/pom.xml
- deegree-workspaces/deegree-workspace-compliance-tests/pom.xml
- deegree-workspaces/deegree-workspace-csw-memory-tests/pom.xml
- deegree-workspaces/deegree-workspace-csw/pom.xml
- deegree-workspaces/deegree-workspace-geosciml/pom.xml
- deegree-workspaces/deegree-workspace-utah/pom.xml
- deegree-workspaces/deegree-workspace-wcts/pom.xml
- deegree-workspaces/deegree-workspace-wps/pom.xml
- deegree-workspaces/pom.xml
- pom.xml
- src/main/assembly/schemas.xml
This creates an single artifact to help with publishing of schemas.deegree.org
> Create schema assembly as single zip artifact

- pom.xml
- uncoupled/deegree-jaxb-resolver/pom.xml
- uncoupled/deegree-jaxb-resolver/src/main/java/org/deegree/uncoupled/jaxb/CatalogResolver.java
Use non-snapshot version required for release of RC
> Update jaxb resolver to version 1.1

- uncoupled/deegree-jaxb-resolver/pom.xml
This reverts commit 68d0a4416a78972f1d9ba32cb1bcd75c726c25bf.
> Revert failed release of jaxb-resolver

- Jenkinsfile
- README.md
- SECURITY.md
Applied changes to re-named branch from master to main. Added 3.5 line to README and SECURITY files
> Prepare pipeline for v3.5

- deegree-services/deegree-webservices-handbook/src/main/asciidoc/intro.adoc
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/metadatastores.adoc
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/serverconnections.adoc
Update version in documentation to 3.5 and changed configVersion attribute from 3.4.0 to 3.5.0 (optional)
Fixes #1120
> Update version in documentation to 3.5

- deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/standard/points/JTSPoints.java
Fixes a bug by recreating a new DefaultPoint for each next call.
> Ensure creation of new default points to avoid unexpected JTS Geometries

- pom.xml
> Upgrade JTS to 1.19.0

- pom.xml
Upgrades maven surefire, failsafe, compiler, jaxb2 and jar plugins to most recent version, supports compile with JDK 17+
> Upgrades maven surefire, failsafe, compiler, jaxb2 and jar plugins

- pom.xml
> Upgrades maven enforcer plugin and extra rules

- deegree-core/deegree-core-base/src/main/java/org/deegree/gml/feature/GMLFeatureWriter.java
> Write nil and nilReason with namespaces to avoid invalid XML

- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/utils/test/IntegrationTestUtils.java
- deegree-core/deegree-core-rendering-2d/src/test/java/org/deegree/rendering/r2d/AbstractSimilarityTest.java
- deegree-core/deegree-core-rendering-2d/src/test/java/org/deegree/rendering/r2d/Java2DRendererTest.java
- deegree-tests/deegree-wms-remoteows-tests/src/test/java/org/deegree/services/wms/RemoteWMSIntegrationTest.java
- deegree-tests/deegree-wms-similarity-tests/src/test/java/org/deegree/services/wms/WMSSimilarityIntegrationTest.java
- deegree-tests/deegree-wms-tiling-tests/src/test/java/org/deegree/services/wms/TileLayerIntegrationTest.java
- deegree-tests/deegree-wmts-tests/src/test/java/org/deegree/services/wmts/WmtsGetTileSimilarityIT.java
Extend the testing functionality to allow upload of failed images to pastebin server.
> Enhance image similarity test

- deegree-tests/deegree-integration-tests/pom.xml
- deegree-tests/deegree-integration-tests/src/test/resources/deegree-acceptance-tests-soapui-project.xml
- deegree-tests/deegree-integration-tests/src/test/resources/log4j2.properties
- deegree-tests/deegree-wms-remoteows-tests/pom.xml
- deegree-tests/deegree-workspace-tests/pom.xml
- deegree-tests/pom.xml
- pom.xml
> Upgrade maven jetty plugin to 10.0.12

- deegree-services/deegree-services-config/src/main/java/org/deegree/services/config/actions/ListFonts.java
- deegree-services/deegree-services-config/src/main/java/org/deegree/services/config/servlet/ConfigServlet.java
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/restapi.adoc
This PR is a (smal) reworked part of the larger PR #1204
> Adds endpoint to REST API to list available fonts on the server

- deegree-services/deegree-webservices-handbook/src/main/asciidoc/renderstyles.adoc
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/webservices.adoc
In this PR the issue #1374 is resolved. Furthermore the chapter regarding the reported URLs in deegree was enhanced.
A review of the sentence regarding DCP HTTP is appreciated.
Closes #1374.
> Update the documentation of deegree

- deegree-core/deegree-core-protocol/deegree-protocol-wms/src/main/java/org/deegree/protocol/wms/client/WMSCapabilitiesAdapter.java
- deegree-layers/deegree-layers-remotewms/src/main/java/org/deegree/layer/persistence/remotewms/RemoteWmsLayerBuilder.java
- deegree-layers/deegree-layers-remotewms/src/main/resources/META-INF/schemas/layers/remotewms/remotewms.xsd
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/layers.adoc
> Enhanced configuration of RemoteWMS Layer by legend graphics

- deegree-core/deegree-core-theme/src/main/java/org/deegree/theme/persistence/standard/StandardThemeBuilder.java
- deegree-core/deegree-core-theme/src/main/resources/META-INF/schemas/themes/themes.xsd
- deegree-services/deegree-webservices-handbook/src/main/asciidoc/themes.adoc
> Add configuration of legends for group layer

- deegree-services/deegree-webservices-handbook/src/main/asciidoc/featurestores.adoc
- pom.xml
Fixes #1066.
Update documentation how to retrieve and store schema files locally when using schema-driven SQLFeatureStore configurations.
> Improved documentation how to configure deegree for offline startup with schema-driven feature stores

- Jenkinsfile
Release pipeline updated in #1501, DyRun was successful: https://buildserver.deegree.org/view/Failing%20Jobs/job/deegree-3.4/job/deegree-3.4-release-pipeline/794/
> Enabled release build for 3.4

- Jenkinsfile
Reworked release pipeline as in #1501 for 3.4.
Closes #1155  (replaces).
> 3.5 main release pipeline 

- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/FeatureStoreWriter.java
This PR adds a additonal log statement to show the number of processed features.
> GmlLoader: Added log statement

- deegree-services/deegree-webservices/src/main/java/org/deegree/console/workspace/WorkspaceBean.java
> Remove the option to import the deegree-workspace-inspire from the official workspaces in the console

- deegree-processproviders/deegree-processprovider-fme/src/main/resources/META-INF/schemas/processes/fme/example.xml
> Fix FME-Server process provider template

- pom.xml
Remove (hopefully) unused dependency.
> Remove netty dependency

- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/DryRunReferenceCheck.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/GmlLoaderConfiguration.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/ReferenceCheckListener.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/TransactionHandler.java
This PR enables the combination of parameter 'skipReferenceCheck=true' and 'dryRun=true' in the deegree GmlLoader.
> Support combination of parameter 'skipReferenceCheck=true' and 'dryRun=true' for the GmlLoader

- deegree-services/deegree-webservices-handbook/src/main/asciidoc/cli-utility.adoc
See #1595 for more information.
> Fix documentation for SqlFeatureStoreConfigCreator options

- pom.xml
Upgrades a bunch of maven plugins to latest version, including upgrade of jaxb and jax-ws dependencies
> Upgrade of Maven plugins

- .github/workflows/maven.yml
This PR re-activates the GitHub action to build the project on GitHub with a fail fast strategy.
> Re-activate GitHub actions

- uncoupled/deegree-jaxb-resolver/pom.xml
- uncoupled/deegree-jaxb-resolver/src/main/java/org/deegree/uncoupled/jaxb/CatalogResolver.java
Update the dependencies for Jakarta EE
> Update catalog resolver for Jakarta EE

- deegree-client/deegree-jsf-core/pom.xml
- deegree-client/deegree-jsf-core/src/main/resources/META-INF/deegree.taglib.xml
- deegree-client/deegree-jsf-core/src/main/resources/META-INF/faces-config.xml
- deegree-services/deegree-webservices/src/main/webapp/WEB-INF/faces-config.xml
- deegree-services/deegree-webservices/src/main/webapp/WEB-INF/web.xml
- deegree-services/deegree-webservices/src/main/webapp/index.xhtml
- deegree-services/deegree-webservices/src/main/webapp/layout.xhtml
- pom.xml
This PR updates the web.xml and faces-config.xml deployment descriptors to Faces 4.0, and adds Weld CDI implementation and upgraded commons-io dependency to webservices WAR file.
> Fixed web.xml and faces-config.xml deployment descriptor

- pom.xml
> Upgrade PostgreSQL jdbc driver to v42.5.5

- deegree-services/deegree-webservices/pom.xml
- pom.xml
This PR upgrades dependencies to latest bugfix versions:
- comons-codec: 1.16.1
- postgresql: 42.7.2
- spring-framework: 5.3.32
- primefaces: 13.0.6
> Upgraded dependencies to latest bugfix versions (3.6)

- deegree-services/deegree-webservices/pom.xml
- pom.xml
This PR upgrades dependencies to latest bugfix versions:
- comons-codec: 1.16.1
- postgresql: 42.7.2 (fixes CVE)
- spring-framework: 5.3.32
- primefaces: 13.0.6
> Upgraded dependencies to latest bugfix versions (3.5)

- deegree-services/deegree-webservices/pom.xml
- deegree-tools/deegree-tools-gml/pom.xml
- pom.xml
This PR upgrades dependencies to latest bugfix versions:
- postgresql: 42.4.4 (fixes critical CVE)
- spring-framework: 5.3.32
- spring-batch: 4.3.10
- jaxb-impl: 2.3.9
- primefaces: 8.0
This PR is intended to create a 3.4 release version to be used in the docker build providing an image without critical CVEs.
> Upgraded dependencies to latest bugfix versions (3.4)

- deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/standard/primitive/DefaultSurface.java
A JTS MultiPolygon is created if a DefaultSurface contains multiple patches.
> Added support of patches in DefaultSurface.buildJTSGeometry() (3.5)

- deegree-core/deegree-core-geometry/src/main/java/org/deegree/geometry/standard/primitive/DefaultSurface.java
A JTS MultiPolygon is created if a DefaultSurface contains multiple patches.
> Added support of patches in DefaultSurface.buildJTSGeometry() (3.6)

- pom.xml
This PR upgrades dependencies and maven plugins to latest version including `gson` and `commons-collections`.
> Upgrade dependencies gson, commons-collections4 and maven plugins (3.5)

- deegree-core/deegree-core-filterfunctions/src/main/java/org/deegree/filter/function/geometry/IsCurve.java
- deegree-core/deegree-core-filterfunctions/src/main/java/org/deegree/filter/function/geometry/IsPoint.java
- deegree-core/deegree-core-filterfunctions/src/main/java/org/deegree/filter/function/geometry/IsSurface.java
Fixes #1576 by returning false if the requested geometry does not exists.
> Return false is geometry property does not exists (3.6)

- deegree-core/deegree-core-commons/pom.xml
- pom.xml
> Upgrade json path library to latest version (3.5)

- deegree-core/deegree-core-commons/pom.xml
- pom.xml
Upgrading json-path library.
PR with 3.5 backport: #1672
> Upgrade json path library to latest version

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/AppSchemaMapper.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/CycleAnalyser.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/GmlReferenceData.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/PathStep.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/ReferenceData.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/java/org/deegree/feature/persistence/sql/mapper/AppSchemaMapperTest.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/java/org/deegree/feature/persistence/sql/mapper/GmlReferenceDataTest.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/resources/org/deegree/feature/persistence/sql/mapper/data/Inspire-MineralResources.xml
This PR fixes the evaluation of reference data. Type definitions are skipped to detect the correct number of features. Furthermore support of GenericFeature was added.
PR with 3.5 Backport: https://github.com/deegree/deegree3/pull/1667
Replaces #1666
> Fixed evaluation of reference data (3.6)

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/ddl/DDLCreator.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/ddl/PostGISDDLCreator.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/mapper/AppSchemaMapper.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/test/java/org/deegree/feature/persistence/sql/mapper/AppSchemaMapperTest.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/config/FeatureStoreConfigWriter.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/config/LoadParameter.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/config/LoadParameterBuilder.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/config/SqlFeatureStoreConfigCreatorConfiguration.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/config/SqlFeatureStoreConfigCreatorUsagePrinter.java
Backport for 3.5: #1678 (contains description)
> Enhanced SqlFeatureStoreConfigCreator to support new parameter dbschema (3.6)

- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/xml/XsltUtils.java
> Enable FEATURE_SECURE_PROCESSING

- deegree-services/deegree-webservices/src/main/java/org/deegree/console/datastore/feature/MappingWizardSQL.java
This PR applies the code formatting.
> Fixed code formatting

- Jenkinsfile
Upgrade to Java 17 as required by #1690
References:
* #1690
> Upgrade Jenkinsfile  to temurin 17 / Java 17

- deegree-services/deegree-webservices/src/main/java/org/deegree/console/generic/XmlEditorBean.java
- deegree-services/deegree-webservices/src/main/webapp/WEB-INF/web.xml
- deegree-services/deegree-webservices/src/main/webapp/layout.xhtml
This PR fixes some more faces errors.
> Fix some faces errors in admin console

- deegree-tools/deegree-tools-gml/pom.xml
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/GmlToolsApp.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/JobRepositoryConfiguration.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/SubcommandApp.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/config/FeatureStoreConfigWriter.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/config/SqlFeatureStoreConfigCreatorApp.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/config/SqlFeatureStoreConfigCreatorConfiguration.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/FeatureStoreWriter.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/GmlLoaderApp.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/NullWriter.java
- deegree-tools/deegree-tools-gml/src/main/java/org/deegree/tools/featurestoresql/loader/ReportWriter.java
- deegree-tools/deegree-tools-gml/src/test/java/org/deegree/tools/featurestoresql/GmlToolsAppTest.java
- deegree-tools/deegree-tools-gml/src/test/java/org/deegree/tools/featurestoresql/config/SqlFeatureStoreConfigCreatorAppTest.java
- deegree-tools/deegree-tools-gml/src/test/java/org/deegree/tools/featurestoresql/loader/FeatureReferencesParserTest.java
- deegree-tools/deegree-tools-gml/src/test/java/org/deegree/tools/featurestoresql/loader/FeatureReferencesParserTestConfig.java
- deegree-tools/deegree-tools-gml/src/test/java/org/deegree/tools/featurestoresql/loader/GmlLoaderAppTest.java
- pom.xml
Fixes #1690. This PR includes the upgrade from JDK 11 to JDK 17.
> Upgrading Spring Boot to v3.3 with Spring Framework 6.1 and Spring Batch 5.1 with JDK 17

- deegree-client/deegree-jsf-core/src/main/java/org/deegree/client/core/utils/ActionParams.java
Fixing downloading workspaces from repo in console.
> Fixed workspace download in admin console

- deegree-services/deegree-webservices/pom.xml
This PR upgrades primefaces to version 13.0.10/11 to resolve CVE-2024-34342(10.0), CVE-2024-4367(10.0)
> Upgraded primefaces to version 13.0.10/11

- pom.xml
This PR upgrades the maven plugins to latest version.
> Upgraded maven plugins to latest version

- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/Capabilities130XMLAdapter.java
> Write schemaLocation with https in WMS 1.1.3 capabilities (3.6)

- deegree-client/deegree-jsf-core/pom.xml
- deegree-services/deegree-webservices/pom.xml
- pom.xml
PR upgrades dependencies:
- jts: https://github.com/locationtech/jts/releases/tag/1.20.0
- primefaces: https://github.com/primefaces/primefaces/releases/tag/14.0.4
- weld: https://weld.cdi-spec.org/news/2024/08/27/weld-513Final/
- slf4j
- xmlunit-matchers
> Upgraded dependencies: jts, slf4j, extra-enforcer-rules, xmlunit-matchers

- deegree-services/deegree-webservices/pom.xml
- pom.xml
This PR fixes a critical issue in primeface CVSS 10 and also
- upgrades Spring Framework to latest bugfix release
- upgrades OWASP Maven plugin to latest version
> Upgraded Primefaces to latest bugfix version 14.0.6 to resolve critical CVE (3.5)

- Jenkinsfile
This PR applies the similar changes to the Jenkinsfile pipeline as in PR #1768 for branch `3.5-main`.
> Fixed release pipeline to use managed credentials from jenkins (3.5)

- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/Wms130SoapExtendedCapabilitesWriter.java
> Fix external URL of soapwms schema

- pom.xml
> Upgrade log4j.version to 2.24.3

- pom.xml
Upgrade of commons-codec and postgresql
> Upgrades dependencies commons-codec to 1.17.2 and postgresql to 42.7.5 (3.6)

- deegree-client/deegree-jsf-core/pom.xml
- deegree-services/deegree-webservices/pom.xml
- pom.xml
This PR updates
* commons-pool2
* primefaces
* jakarta.faces
* weld-servlet-shaded
> Upgraded dependencies to latest bugfix versions 

- deegree-core/deegree-core-commons/src/main/java/org/deegree/commons/xml/schema/RedirectingEntityResolver.java
This PR is the back-port of #1795
> Fixed error when resolving CityGML schema and its parts (3.5)

- Jenkinsfile
This PR splits the pipeline step for release prepare and release perform.
> Split pipeline step for release prepare and release perform (3.6)

- Jenkinsfile
This PR splits the  pipeline step for release prepare and release perform.
Back-port of #1798
> Split pipeline step for release prepare and release perform (3.5)

- .github/workflows/maven.yml
Switches from Java 11 to Java 17
> Fixed ghaction to use java version 17 for main branch

- pom.xml
* commons-io
* jakarta.faces
* it.geosolutions.imageio-ext
* logback
> Upgraded dependencies to latest minor/bugfix version

- pom.xml
> Upgraded JDBC driver for MS SQL Server to v12.10 (3.5)

- deegree-core/deegree-core-sqldialect/deegree-sqldialect-commons/src/main/java/org/deegree/sqldialect/SQLDialect.java
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-mssql/src/main/java/org/deegree/sqldialect/mssql/MSSQLDialect.java
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-oracle/src/main/java/org/deegree/sqldialect/oracle/OracleDialect.java
- deegree-core/deegree-core-sqldialect/deegree-sqldialect-postgis/src/main/java/org/deegree/sqldialect/postgis/PostGISDialect.java
- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/SQLFeatureStore.java
This PR is a backport for 3.5 line of PR #1818
> Fixed SQL Server dialect for statements using paging (3.5)

- deegree-datastores/deegree-featurestores/deegree-featurestore-sql/src/main/java/org/deegree/feature/persistence/sql/rules/FeatureBuilderRelational.java
> Fixes missing nil property (3.5)

- deegree-layers/deegree-layers-remotewms/src/main/java/org/deegree/layer/persistence/remotewms/RemoteWmsLayerBuilder.java
This PR fixes a ConcurrentModifiationException in a RemoteWMS configuration with explicitly configured styles.
> Fix ConcurrentModifiationException (3.6)

- deegree-core/deegree-core-base/src/main/java/org/deegree/geojson/GeoJsonGeometryWriter.java
- deegree-core/deegree-core-base/src/main/java/org/deegree/geojson/GeoJsonWriter.java
- deegree-core/deegree-core-base/src/test/java/org/deegree/geojson/GeoJsonFeatureWriterTest.java
> Fix WKT geometry transformation in GeoJSON for non-default CRS requests (3.5)

- deegree-services/deegree-services-wms/src/main/java/org/deegree/services/wms/controller/capabilities/Wms130SoapExtendedCapabilitesWriter.java
> Fix external URL of soapwms schema (3.5)

- SECURITY.md
This PR updates the [Security Policy](https://github.com/deegree/deegree3/security/policy) for version 3.6.
> Updated security policy
